// Generated by rapidprotoc. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/arena_runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>
#include <type_traits>

#include "rapidproto/arena_runtime.hpp"
#include "arena_unknown.rp.common.hpp"  // IWYU pragma: export

namespace au {

class Flag;
class Holder;

class Flag {
 public:
  bool value() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0; }
  bool has_unknown_fields() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 1)) != 0; }
  [[nodiscard]] static const Flag* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Flag& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  template <class RpT> friend void ::rapidproto::arena_detail::wrap(RpT&, bool, bool) noexcept;
  static Flag rp_wrap(bool value, bool unknown) noexcept { Flag w{}; w.m_rp_mask = static_cast<std::uint8_t>(0 | (value ? (std::uint8_t{1} << 0) : 0) | (unknown ? (std::uint8_t{1} << 1) : 0)); return w; }
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<Flag>);

class Holder {
 public:
  bool has_flag() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0; }
  ::au::Flag flag() const noexcept { ::au::Flag rp_w{}; ::rapidproto::arena_detail::wrap(rp_w, (m_rp_mask & (std::uint8_t{1} << 1)) != 0, (m_rp_mask & (std::uint8_t{1} << 2)) != 0); return rp_w; }
  std::int32_t n() const noexcept { return m_n; }
  bool has_unknown_fields() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 3)) != 0; }
  [[nodiscard]] static const Holder* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Holder& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  std::int32_t m_n;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<Holder>);

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool Flag::rp_decode_into([[maybe_unused]] Flag& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          if (::rapidproto::varint_to_bool(*rp_v)) { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0)); } else { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask & static_cast<std::uint8_t>(~(std::uint8_t{1} << 0))); }
          continue;
        }
        break;
      }
      default: { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 1)); break; }
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const Flag* Flag::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  Flag* const rp_root = arena.create<Flag>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool Holder::rp_decode_into([[maybe_unused]] Holder& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          bool rp_w = false;
          ::rapidproto::WireReader rp_wr{*rp_v};
          while (!rp_wr.at_end()) {
            const auto rp_wt = rp_wr.read_tag();
            if (!rp_wt) { ::rapidproto::rp_fail_wire(err, rp_wr); return false; }
            if (rp_wt->field_number == 1 && rp_wt->wire_type == ::rapidproto::WireType::Varint) {
              const auto rp_wv = rp_wr.read_varint();
              if (!rp_wv) { ::rapidproto::rp_fail_wire(err, rp_wr); return false; }
              rp_w = ::rapidproto::varint_to_bool(*rp_wv);
            } else {
              if (rp_wt->field_number != 1) { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 2)); }
              if (!rp_wr.skip(rp_wt->wire_type, rp_wt->field_number)) { ::rapidproto::rp_fail_wire(err, rp_wr); return false; }
            }
          }
          if (rp_w) { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 1)); } else { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask & static_cast<std::uint8_t>(~(std::uint8_t{1} << 1))); }
          out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0));
          continue;
        }
        break;
      }
      case 2: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_n = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        break;
      }
      default: { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 3)); break; }
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const Holder* Holder::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  Holder* const rp_root = arena.create<Holder>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

}  // namespace au
