// Generated by rapidprotoc 0.2.0. DO NOT EDIT.
// Shared schema types (enums) for the generated decoders (Apache-2.0).
#pragma once

#include <cstdint>

namespace al {

enum class Color : std::int32_t {
  RED = 0,
  GREEN = 1,
  BLUE = 2,
  rp_known_min = 0,
  rp_known_max = 2,
  rp_non_exhaustive_min = INT32_MIN,
  rp_non_exhaustive_max = INT32_MAX,
};

}  // namespace al
