// Generated by rapidprotoc. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/arena_runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>
#include <type_traits>

#include "rapidproto/arena_runtime.hpp"
#include "arena_layout.rp.common.hpp"  // IWYU pragma: export

namespace al {

class Point;
class Big;
class HasString;
class BoolWrap;
class SelfRef;
class Layout;

class Point {
 public:
  std::int32_t x() const noexcept { return m_x; }
  std::int32_t y() const noexcept { return m_y; }
  [[nodiscard]] static const Point* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Point& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  std::int32_t m_x;
  std::int32_t m_y;
};
static_assert(::std::is_trivially_destructible_v<Point>);

class Big {
 public:
  std::uint64_t a() const noexcept { return m_a; }
  std::uint64_t b() const noexcept { return m_b; }
  std::uint64_t c() const noexcept { return m_c; }
  [[nodiscard]] static const Big* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Big& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  std::uint64_t m_a;
  std::uint64_t m_b;
  std::uint64_t m_c;
};
static_assert(::std::is_trivially_destructible_v<Big>);

class HasString {
 public:
  std::string_view s() const noexcept { return m_s.view(); }
  [[nodiscard]] static const HasString* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(HasString& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  ::rapidproto::ArenaString m_s;
};
static_assert(::std::is_trivially_destructible_v<HasString>);

class BoolWrap {
 public:
  bool value() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0; }
  [[nodiscard]] static const BoolWrap* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(BoolWrap& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  template <class RpT> friend void ::rapidproto::arena_detail::wrap(RpT&, bool) noexcept;
  static BoolWrap rp_wrap(bool value) noexcept { BoolWrap w{}; w.m_rp_mask = static_cast<std::uint8_t>(0 | (value ? (std::uint8_t{1} << 0) : 0)); return w; }
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<BoolWrap>);

class SelfRef {
 public:
  const ::al::SelfRef* next() const noexcept { return m_next; }
  std::int32_t v() const noexcept { return m_v; }
  [[nodiscard]] static const SelfRef* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(SelfRef& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  const ::al::SelfRef* m_next;
  std::int32_t m_v;
};
static_assert(::std::is_trivially_destructible_v<SelfRef>);

class Layout {
 public:
  enum class ChoiceCase : std::uint8_t {
    kNotSet = 0,
    kCi = 1,
    kCs = 2,
    kCp = 3,
  };
  union rp_choice_union {
    std::int32_t ci;
    ::rapidproto::ArenaString cs;
    ::al::Point cp;
    rp_choice_union() noexcept {}
  };
  struct CountsEntry {
    std::string_view key() const noexcept { return rp_key.view(); }
    std::int32_t value() const noexcept { return rp_value; }
    friend class Layout;
   private:
    ::rapidproto::ArenaString rp_key;
    std::int32_t rp_value;
  };
  struct GridEntry {
    std::int32_t key() const noexcept { return rp_key; }
    const ::al::Point* value() const noexcept { return &rp_value; }
    friend class Layout;
   private:
    ::al::Point rp_value;
    std::int32_t rp_key;
  };
  bool b1() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0; }
  std::int64_t big() const noexcept { return m_big; }
  bool b2() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 1)) != 0; }
  std::int32_t small() const noexcept { return m_small; }
  bool has_opt() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 2)) != 0; }
  std::int32_t opt() const noexcept { return m_opt; }
  std::string_view name() const noexcept { return m_name.view(); }
  bool has_oname() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 3)) != 0; }
  std::string_view oname() const noexcept { return m_oname.view(); }
  ::al::Color color() const noexcept { return m_color; }
  bool has_pt() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 4)) != 0; }
  const ::al::Point* pt() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 4)) != 0 ? &m_pt : nullptr; }
  const ::al::Big* bg() const noexcept { return m_bg; }
  const ::al::HasString* hs() const noexcept { return m_hs; }
  bool has_flag() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 5)) != 0; }
  ::al::BoolWrap flag() const noexcept { ::al::BoolWrap rp_w{}; ::rapidproto::arena_detail::wrap(rp_w, (m_rp_mask & (std::uint8_t{1} << 6)) != 0); return rp_w; }
  ::rapidproto::ArrayView<std::int32_t> nums() const noexcept { return m_nums; }
  ::rapidproto::ArrayView<::al::Point> points() const noexcept { return m_points; }
  ::rapidproto::StringArrayView labels() const noexcept { return ::rapidproto::StringArrayView(m_labels); }
  ::rapidproto::MapView<CountsEntry> counts() const noexcept { return m_counts; }
  ::rapidproto::MapView<GridEntry> grid() const noexcept { return m_grid; }
  ChoiceCase choice_case() const noexcept { return static_cast<ChoiceCase>(m_rp_choice_case); }
  std::int32_t ci() const noexcept { return choice_case() == ChoiceCase::kCi ? m_rp_choice.ci : std::int32_t{}; }
  std::string_view cs() const noexcept { return choice_case() == ChoiceCase::kCs ? m_rp_choice.cs.view() : std::string_view{}; }
  const ::al::Point* cp() const noexcept { return choice_case() == ChoiceCase::kCp ? &m_rp_choice.cp : nullptr; }
  [[nodiscard]] static const Layout* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Layout& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  ::rapidproto::ArenaString m_name;
  ::rapidproto::ArenaString m_oname;
  ::rapidproto::ArrayView<std::int32_t> m_nums;
  ::rapidproto::ArrayView<::al::Point> m_points;
  ::rapidproto::MapView<CountsEntry> m_counts;
  ::rapidproto::MapView<GridEntry> m_grid;
  rp_choice_union m_rp_choice;
  ::rapidproto::ArrayView<::rapidproto::ArenaString> m_labels;
  std::int64_t m_big;
  const ::al::Big* m_bg;
  const ::al::HasString* m_hs;
  ::al::Point m_pt;
  std::int32_t m_small;
  std::int32_t m_opt;
  ::al::Color m_color;
  std::uint8_t m_rp_choice_case;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<Layout>);

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool Point::rp_decode_into([[maybe_unused]] Point& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_x = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        break;
      }
      case 2: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_y = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const Point* Point::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  Point* const rp_root = arena.create<Point>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool Big::rp_decode_into([[maybe_unused]] Big& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::I64) {
          const auto rp_v = reader.read_fixed64();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_a = *rp_v;
          continue;
        }
        break;
      }
      case 2: {
        if (rp_tag->wire_type == ::rapidproto::WireType::I64) {
          const auto rp_v = reader.read_fixed64();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_b = *rp_v;
          continue;
        }
        break;
      }
      case 3: {
        if (rp_tag->wire_type == ::rapidproto::WireType::I64) {
          const auto rp_v = reader.read_fixed64();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_c = *rp_v;
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const Big* Big::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  Big* const rp_root = arena.create<Big>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool HasString::rp_decode_into([[maybe_unused]] HasString& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_s = ::rapidproto::ArenaString::make(*rp_v, arena);
          if (!rp_v->empty() && (out.m_s).empty()) { ::rapidproto::rp_fail_string(err, *rp_v); return false; }
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const HasString* HasString::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  HasString* const rp_root = arena.create<HasString>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool BoolWrap::rp_decode_into([[maybe_unused]] BoolWrap& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          if (::rapidproto::varint_to_bool(*rp_v)) { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0)); } else { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask & static_cast<std::uint8_t>(~(std::uint8_t{1} << 0))); }
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const BoolWrap* BoolWrap::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  BoolWrap* const rp_root = arena.create<BoolWrap>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool SelfRef::rp_decode_into([[maybe_unused]] SelfRef& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          if (out.m_next != nullptr) { ::rapidproto::rp_fail_repeated_singular(err, 1); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::al::SelfRef* const rp_sub = arena.create<::al::SelfRef>();
          if (rp_sub == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          if (!::rapidproto::arena_detail::decode_into(*rp_sub, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_next = rp_sub;
          continue;
        }
        break;
      }
      case 2: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_v = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const SelfRef* SelfRef::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  SelfRef* const rp_root = arena.create<SelfRef>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool Layout::rp_decode_into([[maybe_unused]] Layout& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  std::int32_t* rp_acc_nums = nullptr;
  std::size_t rp_n_nums = 0;
  std::size_t rp_cap_nums = 0;
  const auto rp_slot_nums = [&]() noexcept -> std::int32_t* {
    if (rp_n_nums == rp_cap_nums) {
      const std::size_t rp_nc = rp_cap_nums == 0 ? std::size_t{4} : rp_cap_nums * 2;
      std::int32_t* const rp_nb = arena.allocate_array<std::int32_t>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_nums; ++rp_i) { rp_nb[rp_i] = rp_acc_nums[rp_i]; }
      rp_acc_nums = rp_nb;
      rp_cap_nums = rp_nc;
    }
    return &rp_acc_nums[rp_n_nums++];
  };
  ::al::Point* rp_acc_points = nullptr;
  std::size_t rp_n_points = 0;
  std::size_t rp_cap_points = 0;
  const auto rp_slot_points = [&]() noexcept -> ::al::Point* {
    if (rp_n_points == rp_cap_points) {
      const std::size_t rp_nc = rp_cap_points == 0 ? std::size_t{4} : rp_cap_points * 2;
      ::al::Point* const rp_nb = arena.allocate_array<::al::Point>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_points; ++rp_i) { rp_nb[rp_i] = rp_acc_points[rp_i]; }
      rp_acc_points = rp_nb;
      rp_cap_points = rp_nc;
    }
    return &rp_acc_points[rp_n_points++];
  };
  ::rapidproto::ArenaString* rp_acc_labels = nullptr;
  std::size_t rp_n_labels = 0;
  std::size_t rp_cap_labels = 0;
  const auto rp_slot_labels = [&]() noexcept -> ::rapidproto::ArenaString* {
    if (rp_n_labels == rp_cap_labels) {
      const std::size_t rp_nc = rp_cap_labels == 0 ? std::size_t{4} : rp_cap_labels * 2;
      ::rapidproto::ArenaString* const rp_nb = arena.allocate_array<::rapidproto::ArenaString>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_labels; ++rp_i) { rp_nb[rp_i] = rp_acc_labels[rp_i]; }
      rp_acc_labels = rp_nb;
      rp_cap_labels = rp_nc;
    }
    return &rp_acc_labels[rp_n_labels++];
  };
  CountsEntry* rp_acc_counts = nullptr;
  std::size_t rp_n_counts = 0;
  std::size_t rp_cap_counts = 0;
  const auto rp_slot_counts = [&]() noexcept -> CountsEntry* {
    if (rp_n_counts == rp_cap_counts) {
      const std::size_t rp_nc = rp_cap_counts == 0 ? std::size_t{4} : rp_cap_counts * 2;
      CountsEntry* const rp_nb = arena.allocate_array<CountsEntry>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_counts; ++rp_i) { rp_nb[rp_i] = rp_acc_counts[rp_i]; }
      rp_acc_counts = rp_nb;
      rp_cap_counts = rp_nc;
    }
    return &rp_acc_counts[rp_n_counts++];
  };
  GridEntry* rp_acc_grid = nullptr;
  std::size_t rp_n_grid = 0;
  std::size_t rp_cap_grid = 0;
  const auto rp_slot_grid = [&]() noexcept -> GridEntry* {
    if (rp_n_grid == rp_cap_grid) {
      const std::size_t rp_nc = rp_cap_grid == 0 ? std::size_t{4} : rp_cap_grid * 2;
      GridEntry* const rp_nb = arena.allocate_array<GridEntry>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_grid; ++rp_i) { rp_nb[rp_i] = rp_acc_grid[rp_i]; }
      rp_acc_grid = rp_nb;
      rp_cap_grid = rp_nc;
    }
    return &rp_acc_grid[rp_n_grid++];
  };
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          if (::rapidproto::varint_to_bool(*rp_v)) { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0)); } else { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask & static_cast<std::uint8_t>(~(std::uint8_t{1} << 0))); }
          continue;
        }
        break;
      }
      case 2: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_big = ::rapidproto::varint_to_int64(*rp_v);
          continue;
        }
        break;
      }
      case 3: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          if (::rapidproto::varint_to_bool(*rp_v)) { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 1)); } else { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask & static_cast<std::uint8_t>(~(std::uint8_t{1} << 1))); }
          continue;
        }
        break;
      }
      case 4: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_small = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        break;
      }
      case 5: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_opt = ::rapidproto::varint_to_int32(*rp_v);
          out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 2));
          continue;
        }
        break;
      }
      case 6: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_name = ::rapidproto::ArenaString::make(*rp_v, arena);
          if (!rp_v->empty() && (out.m_name).empty()) { ::rapidproto::rp_fail_string(err, *rp_v); return false; }
          continue;
        }
        break;
      }
      case 7: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_oname = ::rapidproto::ArenaString::make(*rp_v, arena);
          if (!rp_v->empty() && (out.m_oname).empty()) { ::rapidproto::rp_fail_string(err, *rp_v); return false; }
          out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 3));
          continue;
        }
        break;
      }
      case 8: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_color = static_cast<::al::Color>(::rapidproto::varint_to_int32(*rp_v));
          continue;
        }
        break;
      }
      case 9: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          if ((out.m_rp_mask & (std::uint8_t{1} << 4)) != 0) { ::rapidproto::rp_fail_repeated_singular(err, 9); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          if (!::rapidproto::arena_detail::decode_into(out.m_pt, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 4));
          continue;
        }
        break;
      }
      case 10: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          if (out.m_bg != nullptr) { ::rapidproto::rp_fail_repeated_singular(err, 10); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::al::Big* const rp_sub = arena.create<::al::Big>();
          if (rp_sub == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          if (!::rapidproto::arena_detail::decode_into(*rp_sub, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_bg = rp_sub;
          continue;
        }
        break;
      }
      case 11: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          if (out.m_hs != nullptr) { ::rapidproto::rp_fail_repeated_singular(err, 11); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::al::HasString* const rp_sub = arena.create<::al::HasString>();
          if (rp_sub == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          if (!::rapidproto::arena_detail::decode_into(*rp_sub, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_hs = rp_sub;
          continue;
        }
        break;
      }
      case 12: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          bool rp_w = false;
          ::rapidproto::WireReader rp_wr{*rp_v};
          while (!rp_wr.at_end()) {
            const auto rp_wt = rp_wr.read_tag();
            if (!rp_wt) { ::rapidproto::rp_fail_wire(err, rp_wr); return false; }
            if (rp_wt->field_number == 1 && rp_wt->wire_type == ::rapidproto::WireType::Varint) {
              const auto rp_wv = rp_wr.read_varint();
              if (!rp_wv) { ::rapidproto::rp_fail_wire(err, rp_wr); return false; }
              rp_w = ::rapidproto::varint_to_bool(*rp_wv);
            } else if (!rp_wr.skip(rp_wt->wire_type, rp_wt->field_number)) { ::rapidproto::rp_fail_wire(err, rp_wr); return false; }
          }
          if (rp_w) { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 6)); } else { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask & static_cast<std::uint8_t>(~(std::uint8_t{1} << 6))); }
          out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 5));
          continue;
        }
        break;
      }
      case 13: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          std::int32_t* const rp_slot = rp_slot_nums();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_p = reader.read_length_delimited();
          if (!rp_p) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::rapidproto::WireReader rp_pr{*rp_p};
          while (!rp_pr.at_end()) {
            std::int32_t* const rp_slot = rp_slot_nums();
            if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
            const auto rp_v = rp_pr.read_varint();
            if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_pr); return false; }
            *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          }
          continue;
        }
        break;
      }
      case 14: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          ::al::Point* const rp_slot = rp_slot_points();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          *rp_slot = ::al::Point{};
          if (!::rapidproto::arena_detail::decode_into(*rp_slot, *rp_v, arena, depth + 1, err)) { return false; }
          continue;
        }
        break;
      }
      case 20: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          ::rapidproto::ArenaString* const rp_slot = rp_slot_labels();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          *rp_slot = ::rapidproto::ArenaString::make(*rp_v, arena);
          if (!rp_v->empty() && (*rp_slot).empty()) { ::rapidproto::rp_fail_string(err, *rp_v); return false; }
          continue;
        }
        break;
      }
      case 15: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_ent = reader.read_length_delimited();
          if (!rp_ent) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          CountsEntry* const rp_slot = rp_slot_counts();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          *rp_slot = CountsEntry{};
          ::rapidproto::WireReader rp_er{*rp_ent};
          while (!rp_er.at_end()) {
            const auto rp_et = rp_er.read_tag();
            if (!rp_et) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
            if (rp_et->field_number == 1 && rp_et->wire_type == ::rapidproto::WireType::Len) {
              const auto rp_v = rp_er.read_length_delimited();
              if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
              rp_slot->rp_key = ::rapidproto::ArenaString::make(*rp_v, arena);
              if (!rp_v->empty() && (rp_slot->rp_key).empty()) { ::rapidproto::rp_fail_string(err, *rp_v); return false; }
            } else if (rp_et->field_number == 2 && rp_et->wire_type == ::rapidproto::WireType::Varint) {
              const auto rp_v = rp_er.read_varint();
              if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
              rp_slot->rp_value = ::rapidproto::varint_to_int32(*rp_v);
            } else if (!rp_er.skip(rp_et->wire_type, rp_et->field_number)) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
          }
          continue;
        }
        break;
      }
      case 16: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_ent = reader.read_length_delimited();
          if (!rp_ent) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          GridEntry* const rp_slot = rp_slot_grid();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          *rp_slot = GridEntry{};
          ::rapidproto::WireReader rp_er{*rp_ent};
          while (!rp_er.at_end()) {
            const auto rp_et = rp_er.read_tag();
            if (!rp_et) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
            if (rp_et->field_number == 1 && rp_et->wire_type == ::rapidproto::WireType::Varint) {
              const auto rp_v = rp_er.read_varint();
              if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
              rp_slot->rp_key = ::rapidproto::varint_to_int32(*rp_v);
            } else if (rp_et->field_number == 2 && rp_et->wire_type == ::rapidproto::WireType::Len) {
              const auto rp_v = rp_er.read_length_delimited();
              if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
              if (!::rapidproto::arena_detail::decode_into(rp_slot->rp_value, *rp_v, arena, depth + 1, err)) { return false; }
            } else if (!rp_er.skip(rp_et->wire_type, rp_et->field_number)) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
          }
          continue;
        }
        break;
      }
      case 17: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_rp_choice.ci = ::rapidproto::varint_to_int32(*rp_v);
          out.m_rp_choice_case = 1;
          continue;
        }
        break;
      }
      case 18: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_rp_choice.cs = ::rapidproto::ArenaString::make(*rp_v, arena);
          if (!rp_v->empty() && (out.m_rp_choice.cs).empty()) { ::rapidproto::rp_fail_string(err, *rp_v); return false; }
          out.m_rp_choice_case = 2;
          continue;
        }
        break;
      }
      case 19: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_rp_choice.cp = ::al::Point{};
          if (!::rapidproto::arena_detail::decode_into(out.m_rp_choice.cp, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_rp_choice_case = 3;
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  out.m_nums = ::rapidproto::ArrayView<std::int32_t>(rp_acc_nums, rp_n_nums);
  out.m_points = ::rapidproto::ArrayView<::al::Point>(rp_acc_points, rp_n_points);
  out.m_labels = ::rapidproto::ArrayView<::rapidproto::ArenaString>(rp_acc_labels, rp_n_labels);
  out.m_counts = ::rapidproto::MapView<CountsEntry>(::rapidproto::ArrayView<CountsEntry>(rp_acc_counts, rp_n_counts));
  out.m_grid = ::rapidproto::MapView<GridEntry>(::rapidproto::ArrayView<GridEntry>(rp_acc_grid, rp_n_grid));
  return true;
}
inline const Layout* Layout::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  Layout* const rp_root = arena.create<Layout>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

}  // namespace al
