// Generated by rapidprotoc 0.2.4. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/arena_runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <optional>
#include <string_view>
#include <type_traits>
#include <variant>

#include "rapidproto/arena_runtime.hpp"
#include "arena_unknown.rp.common.hpp"  // IWYU pragma: export

namespace au {

class Flag;
class Holder;

class Flag {
 public:
  bool value() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0; }
  bool has_unknown_fields() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 1)) != 0; }
  [[nodiscard]] static const Flag* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Flag& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<Flag>);

class Holder {
 public:
  const ::au::Flag* flag() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0 ? &m_flag : nullptr; }
  std::int32_t n() const noexcept { return m_n; }
  bool has_unknown_fields() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 1)) != 0; }
  [[nodiscard]] static const Holder* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Holder& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  std::int32_t m_n;
  ::au::Flag m_flag;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<Holder>);

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
RP_FLATTEN inline bool Flag::rp_decode_into([[maybe_unused]] Flag& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  ::rapidproto::Tag rp_tag;
  for (;;) {
    if (reader.at_end()) { break; }
    switch (reader.peek_byte()) {
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): {
        reader.consume_tag_byte();
        const auto rp_v = reader.read_varint();
        if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
        if (::rapidproto::varint_to_bool(*rp_v)) { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0)); } else { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask & static_cast<std::uint8_t>(~(std::uint8_t{1} << 0))); }
        continue;
      }
      default: break;
    }
    const auto rp_state = reader.read_tag_or_end(rp_tag);
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::End) { break; }
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::Error) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag.field_number) {
      case 1: break;
      default: { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 1)); break; }
    }
    if (!reader.skip(rp_tag.wire_type, rp_tag.field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const Flag* Flag::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  Flag* const rp_root = arena.create<Flag>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
RP_FLATTEN inline bool Holder::rp_decode_into([[maybe_unused]] Holder& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  ::rapidproto::Tag rp_tag;
  for (;;) {
    if (reader.at_end()) { break; }
    switch (reader.peek_byte()) {
      case ::rapidproto::raw_tag(2, ::rapidproto::WireType::Varint): {
        reader.consume_tag_byte();
        const auto rp_v = reader.read_varint();
        if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
        out.m_n = ::rapidproto::varint_to_int32(*rp_v);
        continue;
      }
      default: break;
    }
    const auto rp_state = reader.read_tag_or_end(rp_tag);
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::End) { break; }
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::Error) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag.field_number) {
      case 1: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          if ((out.m_rp_mask & (std::uint8_t{1} << 0)) != 0) { ::rapidproto::rp_fail_repeated_singular(err, 1); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          if (!::rapidproto::arena_detail::decode_into(out.m_flag, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0));
          continue;
        }
        break;
      }
      case 2: break;
      default: { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 1)); break; }
    }
    if (!reader.skip(rp_tag.wire_type, rp_tag.field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const Holder* Holder::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  Holder* const rp_root = arena.create<Holder>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

}  // namespace au
