// Generated by rapidprotoc 0.2.3. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/arena_runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <optional>
#include <string_view>
#include <type_traits>
#include <variant>

#include "rapidproto/arena_runtime.hpp"
#include "editions2023.rp.common.hpp"  // IWYU pragma: export

namespace ed23 {

class M;

class M {
 public:
  enum class Inner : std::int32_t {
    ZERO = 0,
    rp_known_min = 0,
    rp_known_max = 0,
    rp_non_exhaustive_min = INT32_MIN,
    rp_non_exhaustive_max = INT32_MAX,
  };
  std::int32_t implicit_scalar() const noexcept { return m_implicit_scalar; }
  std::optional<std::int32_t> explicit_scalar() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0 ? std::optional<std::int32_t>(m_explicit_scalar) : std::nullopt; }
  const ::ed23::M* child() const noexcept { return m_child; }
  ::rapidproto::ArrayView<std::int32_t> packed_nums() const noexcept { return m_packed_nums; }
  ::rapidproto::ArrayView<std::int32_t> expanded_nums() const noexcept { return m_expanded_nums; }
  const ::ed23::M* delim() const noexcept { return m_delim; }
  [[nodiscard]] static const M* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(M& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  ::rapidproto::ArrayView<std::int32_t> m_packed_nums;
  ::rapidproto::ArrayView<std::int32_t> m_expanded_nums;
  const ::ed23::M* m_child;
  const ::ed23::M* m_delim;
  std::int32_t m_implicit_scalar;
  std::int32_t m_explicit_scalar;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<M>);

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool M::rp_decode_into([[maybe_unused]] M& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  std::int32_t* rp_acc_packed_nums = nullptr;
  std::size_t rp_n_packed_nums = 0;
  std::size_t rp_cap_packed_nums = 0;
  const auto rp_slot_packed_nums = [&]() noexcept -> std::int32_t* {
    if (rp_n_packed_nums == rp_cap_packed_nums) {
      const std::size_t rp_nc = rp_cap_packed_nums == 0 ? std::size_t{4} : rp_cap_packed_nums * 2;
      std::int32_t* const rp_nb = arena.allocate_array<std::int32_t>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_packed_nums; ++rp_i) { rp_nb[rp_i] = rp_acc_packed_nums[rp_i]; }
      rp_acc_packed_nums = rp_nb;
      rp_cap_packed_nums = rp_nc;
    }
    return &rp_acc_packed_nums[rp_n_packed_nums++];
  };
  std::int32_t* rp_acc_expanded_nums = nullptr;
  std::size_t rp_n_expanded_nums = 0;
  std::size_t rp_cap_expanded_nums = 0;
  const auto rp_slot_expanded_nums = [&]() noexcept -> std::int32_t* {
    if (rp_n_expanded_nums == rp_cap_expanded_nums) {
      const std::size_t rp_nc = rp_cap_expanded_nums == 0 ? std::size_t{4} : rp_cap_expanded_nums * 2;
      std::int32_t* const rp_nb = arena.allocate_array<std::int32_t>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_expanded_nums; ++rp_i) { rp_nb[rp_i] = rp_acc_expanded_nums[rp_i]; }
      rp_acc_expanded_nums = rp_nb;
      rp_cap_expanded_nums = rp_nc;
    }
    return &rp_acc_expanded_nums[rp_n_expanded_nums++];
  };
  ::rapidproto::WireReader reader{body};
  ::rapidproto::Tag rp_tag;
  for (;;) {
    const auto rp_state = reader.read_tag_or_end(rp_tag);
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::End) { break; }
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::Error) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag.field_number) {
      case 1: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_implicit_scalar = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        break;
      }
      case 2: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_explicit_scalar = ::rapidproto::varint_to_int32(*rp_v);
          out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0));
          continue;
        }
        break;
      }
      case 3: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          if (out.m_child != nullptr) { ::rapidproto::rp_fail_repeated_singular(err, 3); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::ed23::M* const rp_sub = arena.create<::ed23::M>();
          if (rp_sub == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          if (!::rapidproto::arena_detail::decode_into(*rp_sub, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_child = rp_sub;
          continue;
        }
        break;
      }
      case 4: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Varint) {
          std::int32_t* const rp_slot = rp_slot_packed_nums();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          const auto rp_p = reader.read_length_delimited();
          if (!rp_p) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::rapidproto::WireReader rp_pr{*rp_p};
          while (!rp_pr.at_end()) {
            std::int32_t* const rp_slot = rp_slot_packed_nums();
            if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
            const auto rp_v = rp_pr.read_varint();
            if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_pr); return false; }
            *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          }
          continue;
        }
        break;
      }
      case 5: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Varint) {
          std::int32_t* const rp_slot = rp_slot_expanded_nums();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          const auto rp_p = reader.read_length_delimited();
          if (!rp_p) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::rapidproto::WireReader rp_pr{*rp_p};
          while (!rp_pr.at_end()) {
            std::int32_t* const rp_slot = rp_slot_expanded_nums();
            if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
            const auto rp_v = rp_pr.read_varint();
            if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_pr); return false; }
            *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          }
          continue;
        }
        break;
      }
      case 6: {
        if (rp_tag.wire_type == ::rapidproto::WireType::SGroup) {
          if (out.m_delim != nullptr) { ::rapidproto::rp_fail_repeated_singular(err, 6); return false; }
          const auto rp_v = reader.read_group(rp_tag.field_number);
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::ed23::M* const rp_sub = arena.create<::ed23::M>();
          if (rp_sub == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          if (!::rapidproto::arena_detail::decode_into(*rp_sub, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_delim = rp_sub;
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag.wire_type, rp_tag.field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  out.m_packed_nums = ::rapidproto::ArrayView<std::int32_t>(rp_acc_packed_nums, rp_n_packed_nums);
  out.m_expanded_nums = ::rapidproto::ArrayView<std::int32_t>(rp_acc_expanded_nums, rp_n_expanded_nums);
  return true;
}
inline const M* M::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  M* const rp_root = arena.create<M>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

}  // namespace ed23
