// Generated by rapidprotoc. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/arena_runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <optional>
#include <string_view>
#include <type_traits>

#include "rapidproto/arena_runtime.hpp"
#include "proto3.rp.common.hpp"  // IWYU pragma: export

namespace p3 {

class Msg;

class Msg {
 public:
  enum class PickCase : std::uint8_t {
    kNotSet = 0,
    kA = 1,
    kB = 2,
  };
  union rp_pick_union {
    std::int32_t a;
    ::rapidproto::ArenaString b;
    rp_pick_union() noexcept {}
  };
  struct CountsEntry {
    std::string_view key() const noexcept { return rp_key.view(); }
    std::int32_t value() const noexcept { return rp_value; }
    friend class Msg;
   private:
    ::rapidproto::ArenaString rp_key;
    std::int32_t rp_value;
  };
  std::int32_t implicit_i() const noexcept { return m_implicit_i; }
  std::optional<std::int32_t> explicit_i() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0 ? std::optional<std::int32_t>(m_explicit_i) : std::nullopt; }
  std::string_view name() const noexcept { return m_name.view(); }
  ::p3::State state() const noexcept { return m_state; }
  const ::p3::Msg* self() const noexcept { return m_self; }
  ::rapidproto::ArrayView<std::int32_t> nums() const noexcept { return m_nums; }
  ::rapidproto::ArrayView<std::int32_t> unpacked() const noexcept { return m_unpacked; }
  ::rapidproto::ArrayView<::p3::State> states() const noexcept { return m_states; }
  ::rapidproto::MapView<CountsEntry> counts() const noexcept { return m_counts; }
  PickCase pick_case() const noexcept { return static_cast<PickCase>(m_rp_pick_case); }
  std::int32_t a() const noexcept { return pick_case() == PickCase::kA ? m_rp_pick.a : std::int32_t{}; }
  std::string_view b() const noexcept { return pick_case() == PickCase::kB ? m_rp_pick.b.view() : std::string_view{}; }
  [[nodiscard]] static const Msg* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Msg& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  ::rapidproto::ArenaString m_name;
  ::rapidproto::ArrayView<std::int32_t> m_nums;
  ::rapidproto::ArrayView<std::int32_t> m_unpacked;
  ::rapidproto::ArrayView<::p3::State> m_states;
  ::rapidproto::MapView<CountsEntry> m_counts;
  rp_pick_union m_rp_pick;
  const ::p3::Msg* m_self;
  std::int32_t m_implicit_i;
  std::int32_t m_explicit_i;
  ::p3::State m_state;
  std::uint8_t m_rp_pick_case;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<Msg>);

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool Msg::rp_decode_into([[maybe_unused]] Msg& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  std::int32_t* rp_acc_nums = nullptr;
  std::size_t rp_n_nums = 0;
  std::size_t rp_cap_nums = 0;
  const auto rp_slot_nums = [&]() noexcept -> std::int32_t* {
    if (rp_n_nums == rp_cap_nums) {
      const std::size_t rp_nc = rp_cap_nums == 0 ? std::size_t{4} : rp_cap_nums * 2;
      std::int32_t* const rp_nb = arena.allocate_array<std::int32_t>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_nums; ++rp_i) { rp_nb[rp_i] = rp_acc_nums[rp_i]; }
      rp_acc_nums = rp_nb;
      rp_cap_nums = rp_nc;
    }
    return &rp_acc_nums[rp_n_nums++];
  };
  std::int32_t* rp_acc_unpacked = nullptr;
  std::size_t rp_n_unpacked = 0;
  std::size_t rp_cap_unpacked = 0;
  const auto rp_slot_unpacked = [&]() noexcept -> std::int32_t* {
    if (rp_n_unpacked == rp_cap_unpacked) {
      const std::size_t rp_nc = rp_cap_unpacked == 0 ? std::size_t{4} : rp_cap_unpacked * 2;
      std::int32_t* const rp_nb = arena.allocate_array<std::int32_t>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_unpacked; ++rp_i) { rp_nb[rp_i] = rp_acc_unpacked[rp_i]; }
      rp_acc_unpacked = rp_nb;
      rp_cap_unpacked = rp_nc;
    }
    return &rp_acc_unpacked[rp_n_unpacked++];
  };
  ::p3::State* rp_acc_states = nullptr;
  std::size_t rp_n_states = 0;
  std::size_t rp_cap_states = 0;
  const auto rp_slot_states = [&]() noexcept -> ::p3::State* {
    if (rp_n_states == rp_cap_states) {
      const std::size_t rp_nc = rp_cap_states == 0 ? std::size_t{4} : rp_cap_states * 2;
      ::p3::State* const rp_nb = arena.allocate_array<::p3::State>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_states; ++rp_i) { rp_nb[rp_i] = rp_acc_states[rp_i]; }
      rp_acc_states = rp_nb;
      rp_cap_states = rp_nc;
    }
    return &rp_acc_states[rp_n_states++];
  };
  CountsEntry* rp_acc_counts = nullptr;
  std::size_t rp_n_counts = 0;
  std::size_t rp_cap_counts = 0;
  const auto rp_slot_counts = [&]() noexcept -> CountsEntry* {
    if (rp_n_counts == rp_cap_counts) {
      const std::size_t rp_nc = rp_cap_counts == 0 ? std::size_t{4} : rp_cap_counts * 2;
      CountsEntry* const rp_nb = arena.allocate_array<CountsEntry>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_counts; ++rp_i) { rp_nb[rp_i] = rp_acc_counts[rp_i]; }
      rp_acc_counts = rp_nb;
      rp_cap_counts = rp_nc;
    }
    return &rp_acc_counts[rp_n_counts++];
  };
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_implicit_i = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        break;
      }
      case 2: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_explicit_i = ::rapidproto::varint_to_int32(*rp_v);
          out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0));
          continue;
        }
        break;
      }
      case 3: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_name = ::rapidproto::ArenaString::make(*rp_v, arena);
          if (!rp_v->empty() && (out.m_name).empty()) { ::rapidproto::rp_fail_string(err, *rp_v); return false; }
          continue;
        }
        break;
      }
      case 4: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_state = static_cast<::p3::State>(::rapidproto::varint_to_int32(*rp_v));
          continue;
        }
        break;
      }
      case 5: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          if (out.m_self != nullptr) { ::rapidproto::rp_fail_repeated_singular(err, 5); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::p3::Msg* const rp_sub = arena.create<::p3::Msg>();
          if (rp_sub == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          if (!::rapidproto::arena_detail::decode_into(*rp_sub, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_self = rp_sub;
          continue;
        }
        break;
      }
      case 6: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          std::int32_t* const rp_slot = rp_slot_nums();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_p = reader.read_length_delimited();
          if (!rp_p) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::rapidproto::WireReader rp_pr{*rp_p};
          while (!rp_pr.at_end()) {
            std::int32_t* const rp_slot = rp_slot_nums();
            if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
            const auto rp_v = rp_pr.read_varint();
            if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_pr); return false; }
            *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          }
          continue;
        }
        break;
      }
      case 7: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          std::int32_t* const rp_slot = rp_slot_unpacked();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_p = reader.read_length_delimited();
          if (!rp_p) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::rapidproto::WireReader rp_pr{*rp_p};
          while (!rp_pr.at_end()) {
            std::int32_t* const rp_slot = rp_slot_unpacked();
            if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
            const auto rp_v = rp_pr.read_varint();
            if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_pr); return false; }
            *rp_slot = ::rapidproto::varint_to_int32(*rp_v);
          }
          continue;
        }
        break;
      }
      case 8: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          ::p3::State* const rp_slot = rp_slot_states();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          *rp_slot = static_cast<::p3::State>(::rapidproto::varint_to_int32(*rp_v));
          continue;
        }
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_p = reader.read_length_delimited();
          if (!rp_p) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::rapidproto::WireReader rp_pr{*rp_p};
          while (!rp_pr.at_end()) {
            ::p3::State* const rp_slot = rp_slot_states();
            if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
            const auto rp_v = rp_pr.read_varint();
            if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_pr); return false; }
            *rp_slot = static_cast<::p3::State>(::rapidproto::varint_to_int32(*rp_v));
          }
          continue;
        }
        break;
      }
      case 9: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_ent = reader.read_length_delimited();
          if (!rp_ent) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          CountsEntry* const rp_slot = rp_slot_counts();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          *rp_slot = CountsEntry{};
          ::rapidproto::WireReader rp_er{*rp_ent};
          while (!rp_er.at_end()) {
            const auto rp_et = rp_er.read_tag();
            if (!rp_et) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
            if (rp_et->field_number == 1 && rp_et->wire_type == ::rapidproto::WireType::Len) {
              const auto rp_v = rp_er.read_length_delimited();
              if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
              rp_slot->rp_key = ::rapidproto::ArenaString::make(*rp_v, arena);
              if (!rp_v->empty() && (rp_slot->rp_key).empty()) { ::rapidproto::rp_fail_string(err, *rp_v); return false; }
            } else if (rp_et->field_number == 2 && rp_et->wire_type == ::rapidproto::WireType::Varint) {
              const auto rp_v = rp_er.read_varint();
              if (!rp_v) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
              rp_slot->rp_value = ::rapidproto::varint_to_int32(*rp_v);
            } else if (!rp_er.skip(rp_et->wire_type, rp_et->field_number)) { ::rapidproto::rp_fail_wire(err, rp_er); return false; }
          }
          continue;
        }
        break;
      }
      case 10: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_rp_pick.a = ::rapidproto::varint_to_int32(*rp_v);
          out.m_rp_pick_case = 1;
          continue;
        }
        break;
      }
      case 11: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_rp_pick.b = ::rapidproto::ArenaString::make(*rp_v, arena);
          if (!rp_v->empty() && (out.m_rp_pick.b).empty()) { ::rapidproto::rp_fail_string(err, *rp_v); return false; }
          out.m_rp_pick_case = 2;
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  out.m_nums = ::rapidproto::ArrayView<std::int32_t>(rp_acc_nums, rp_n_nums);
  out.m_unpacked = ::rapidproto::ArrayView<std::int32_t>(rp_acc_unpacked, rp_n_unpacked);
  out.m_states = ::rapidproto::ArrayView<::p3::State>(rp_acc_states, rp_n_states);
  out.m_counts = ::rapidproto::MapView<CountsEntry>(::rapidproto::ArrayView<CountsEntry>(rp_acc_counts, rp_n_counts));
  return true;
}
inline const Msg* Msg::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  Msg* const rp_root = arena.create<Msg>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

}  // namespace p3
