// Generated by rapidprotoc 0.4.0. DO NOT EDIT.
// Shared schema types (enums) for the generated decoders (Apache-2.0).
#pragma once

#include <cstdint>

namespace rp::common::rapidproto {

enum class WireType : std::int32_t {
  A = 0,
  rp_known_min = 0,
  rp_known_max = 0,
  rp_non_exhaustive_min = INT32_MIN,
  rp_non_exhaustive_max = INT32_MAX,
};

enum class DecodeStatus : std::int32_t {
  A = 0,
  rp_known_min = 0,
  rp_known_max = 0,
  rp_non_exhaustive_min = INT32_MIN,
  rp_non_exhaustive_max = INT32_MAX,
};

}  // namespace rp::common::rapidproto
