// Generated by rapidprotoc 0.2.4. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/arena_runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <optional>
#include <string_view>
#include <type_traits>
#include <variant>

#include "rapidproto/arena_runtime.hpp"
#include "weakdep.rp.common.hpp"  // IWYU pragma: export

namespace wd {

class WDep;

class WDep {
 public:
  std::optional<std::int32_t> v() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0 ? std::optional<std::int32_t>(m_v) : std::nullopt; }
  [[nodiscard]] static const WDep* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(WDep& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  std::int32_t m_v;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<WDep>);

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
RP_FLATTEN inline bool WDep::rp_decode_into([[maybe_unused]] WDep& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  const std::uint8_t* rp_c = ::rapidproto::byte_ptr(body);
  const std::uint8_t* const rp_cend = rp_c + body.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { break; }
    switch (*rp_c) {  // peek the 1-byte tag without consuming
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): {
        ++rp_c;  // consume the peeked 1-byte tag
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::vt_read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::byte_ptr(body))); return false; }
        rp_c = rp_np;
        out.m_v = ::rapidproto::varint_to_int32(rp_raw);
        out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0));
        continue;
      }
      default: break;
    }
    ::rapidproto::VtTagState rp_state = ::rapidproto::VtTagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::vt_read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::VtTagState::End) { break; }
    if (rp_state == ::rapidproto::VtTagState::Error) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::byte_ptr(body))); return false; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: break;
      default: break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::vt_skip_value(rp_c, rp_cend, ::rapidproto::byte_ptr(body), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, rp_fo); return false; }
    rp_c = rp_sp;
  }
  return true;
}
inline const WDep* WDep::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  WDep* const rp_root = arena.create<WDep>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

}  // namespace wd
