// Generated by rapidprotoc 0.4.0. DO NOT EDIT.
// Shared schema types (enums) for the generated decoders (Apache-2.0).
#pragma once

#include <cstdint>
#include "deep.rp.common.hpp"

namespace rp::common::other {

}  // namespace rp::common::other
