// Generated by rapidprotoc 0.2.4 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "arena_naming.rp.hpp"  // IWYU pragma: export
#include "rapidproto/debug_runtime.hpp"

namespace rapidproto::debug {

}  // namespace rapidproto::debug

namespace an {

inline void rp_debug_write(const ::an::Collide::FooEntry& m, ::rapidproto::debug::Writer& w);
inline void rp_debug_write(const ::an::Collide& m, ::rapidproto::debug::Writer& w);

inline void rp_debug_write(const ::an::Collide::FooEntry& m, ::rapidproto::debug::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.a(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("a");
      w.os() << rp_v;
    }
    (void)rp_first;
  });
}

inline void rp_debug_write(std::ostream& rp_os, const ::an::Collide::FooEntry& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::debug::Writer w(rp_os, rp_width);
  rp_debug_write(m, w);
}

inline std::string rp_debug_string(const ::an::Collide::FooEntry& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_debug_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_debug_write(const ::an::Collide& m, ::rapidproto::debug::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.x()) {
      w.entry_sep(rp_first); w.key("x");
      w.os() << *rp_v;
    }
    if (const auto rp_v = m.has_x(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("has_x");
      w.os() << rp_v;
    }
    if (const auto rp_v = m.pick_case(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("pick_case");
      w.os() << rp_v;
    }
    if (const auto rp_v = m.decode_(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("decode");
      w.os() << rp_v;
    }
    if (const auto& rp_mp = m.foo(); !rp_mp.empty()) {
      w.entry_sep(rp_first); w.key("foo");
      w.group('{', '}', [&] {
        bool rp_efirst = true;
        for (const auto& rp_ent : rp_mp) {
          w.entry_sep(rp_efirst);
          w.os() << '"'; ::rapidproto::debug::write_json_escaped(w.os(), rp_ent.key()); w.os() << "\": ";
          w.os() << rp_ent.value();
          if (w.overflowed()) { break; }
        }
      });
    }
    m.pick([&](auto rp_tag, const auto& rp_v) {
      using RpTag = std::decay_t<decltype(rp_tag)>;
      if constexpr (std::is_same_v<RpTag, ::an::Collide::Pick::p1>) {
        w.entry_sep(rp_first); w.key("p1");
        w.os() << rp_v;
      }
      if constexpr (std::is_same_v<RpTag, ::an::Collide::Pick::p2>) {
        w.entry_sep(rp_first); w.key("p2");
        w.os() << rp_v;
      }
    });
    m.letters([&](auto rp_tag, const auto& rp_v) {
      using RpTag = std::decay_t<decltype(rp_tag)>;
      if constexpr (std::is_same_v<RpTag, ::an::Collide::Letters::a>) {
        w.entry_sep(rp_first); w.key("a");
        w.os() << rp_v;
      }
      if constexpr (std::is_same_v<RpTag, ::an::Collide::Letters::A>) {
        w.entry_sep(rp_first); w.key("A");
        w.os() << rp_v;
      }
    });
    (void)rp_first;
  });
}

inline void rp_debug_write(std::ostream& rp_os, const ::an::Collide& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::debug::Writer w(rp_os, rp_width);
  rp_debug_write(m, w);
}

inline std::string rp_debug_string(const ::an::Collide& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_debug_write(rp_ss, m, rp_width); return rp_ss.str();
}

}  // namespace an
