// Generated by rapidprotoc 0.2.4. DO NOT EDIT.
// Shared schema types (enums) for the generated decoders (Apache-2.0).
#pragma once

#include <cstdint>
#include "weakdep.rp.common.hpp"

namespace wm {

}  // namespace wm
