// Generated by rapidprotoc 0.2.4 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "weakmain.rp.hpp"  // IWYU pragma: export
#include "rapidproto/debug_runtime.hpp"
#include "weakdep.rp.debug.hpp"

namespace rapidproto::debug {

}  // namespace rapidproto::debug

namespace wm {

inline void rp_debug_write(const ::wm::WMain& m, ::rapidproto::debug::Writer& w);

inline void rp_debug_write(const ::wm::WMain& m, ::rapidproto::debug::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.d()) {
      w.entry_sep(rp_first); w.key("d");
      rp_debug_write(*rp_p, w);
    }
    (void)rp_first;
  });
}

inline void rp_debug_write(std::ostream& rp_os, const ::wm::WMain& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::debug::Writer w(rp_os, rp_width);
  rp_debug_write(m, w);
}

inline std::string rp_debug_string(const ::wm::WMain& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_debug_write(rp_ss, m, rp_width); return rp_ss.str();
}

}  // namespace wm
