// Generated by rapidprotoc. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>

#include "rapidproto/runtime.hpp"
#include "dep.rp.common.hpp"  // IWYU pragma: export

namespace dep::stream {

using ::dep::DepEnum;

struct Dep;

struct Dep {
  explicit Dep(::rapidproto::ByteView bytes) noexcept : m_bytes(bytes) {}

  struct v { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "v"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... callbacks) const;
 private:
  ::rapidproto::ByteView m_bytes;
};

template <class... Callbacks>
::rapidproto::DecodeStatus Dep::decode(Callbacks&&... callbacks) const {
  [[maybe_unused]] auto dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(callbacks)...);
  ::rapidproto::WireReader reader{m_bytes};
  while (!reader.at_end()) {
    const auto tag = reader.read_tag();
    if (!tag) { return ::rapidproto::DecodeStatus::from_reader(reader); }
    switch (tag->field_number) {
      case v::kNumber:
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, v, v::Value>)) <= 1U, "field 'v' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, v, v::Value>)) <= 1U, "field 'v' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, v, v::Value>), "a callback for field 'v' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, v, v::Value> && !::rapidproto::specifically_handles<Callbacks, v, v::Value>)), "a callback for field 'v' has the wrong value type (expected v::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, v, v::Value>)) {
          if (tag->wire_type == ::rapidproto::WireType::Varint) {
            const auto value = reader.read_varint();
            if (!value) { return ::rapidproto::DecodeStatus::from_reader(reader); }
            if (const auto status = ::rapidproto::invoke_field(dispatch, v{}, ::rapidproto::varint_to_int32(*value)); !status.ok()) {
              return status;
            }
            continue;
          }
        }
        break;
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const auto rp_value_start = reader.position();
          if (!reader.skip(tag->wire_type, tag->field_number)) { return ::rapidproto::DecodeStatus::from_reader(reader); }
          if (const auto status = ::rapidproto::invoke_unknown(dispatch, ::rapidproto::UnknownField{tag->field_number, tag->wire_type, m_bytes.substr(rp_value_start, reader.position() - rp_value_start)}); !status.ok()) {
            return status;
          }
          continue;
        }
        break;
    }
    if (!reader.skip(tag->wire_type, tag->field_number)) { return ::rapidproto::DecodeStatus::from_reader(reader); }
  }
  return ::rapidproto::DecodeStatus::success();
}

}  // namespace dep::stream
