// Generated by rapidprotoc 0.2.2. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>

#include "rapidproto/runtime.hpp"
#include "editions2024.rp.common.hpp"  // IWYU pragma: export

namespace ed24::stream {

struct M;

struct M {
  explicit M(::rapidproto::ByteView bytes) noexcept : m_bytes(bytes) {}
  ::rapidproto::ByteView rp_bytes() const noexcept { return m_bytes; }

  struct a { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "a"; };
  struct b { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 2; static constexpr std::string_view kName = "b"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView m_bytes;
};

template <class... Callbacks>
::rapidproto::DecodeStatus M::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, a, b>), "a callback matches no field of 'M' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  ::rapidproto::WireReader rp_reader{m_bytes};
  while (!rp_reader.at_end()) {
    const auto rp_tag = rp_reader.read_tag();
    if (!rp_tag) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
    switch (rp_tag->field_number) {
      case a::kNumber:
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, a, a::Value>)) <= 1U, "field 'a' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, a, a::Value>)) <= 1U, "field 'a' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, a, a::Value>), "a callback for field 'a' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, a, a::Value> && !::rapidproto::specifically_handles<Callbacks, a, a::Value>)), "a callback for field 'a' has the wrong value type (expected a::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, a, a::Value>)) {
          if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
            const auto rp_value = rp_reader.read_varint();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, a{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
              return rp_status;
            }
            continue;
          }
        }
        break;
      case b::kNumber:
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, b, b::Value>)) <= 1U, "field 'b' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, b, b::Value>)) <= 1U, "field 'b' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, b, b::Value>), "a callback for field 'b' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, b, b::Value> && !::rapidproto::specifically_handles<Callbacks, b, b::Value>)), "a callback for field 'b' has the wrong value type (expected b::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, b, b::Value>)) {
          if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
            const auto rp_value = rp_reader.read_varint();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, b{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
              return rp_status;
            }
            continue;
          }
          if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
            const auto rp_packed = rp_reader.read_length_delimited();
            if (!rp_packed) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            ::rapidproto::WireReader rp_elements{*rp_packed};
            while (!rp_elements.at_end()) {
              const auto rp_value = rp_elements.read_varint();
              if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_elements); }
              if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, b{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
                return rp_status;
              }
            }
            continue;
          }
        }
        break;
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const auto rp_value_start = rp_reader.position();
          if (!rp_reader.skip(rp_tag->wire_type, rp_tag->field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag->field_number, rp_tag->wire_type, m_bytes.substr(rp_value_start, rp_reader.position() - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    if (!rp_reader.skip(rp_tag->wire_type, rp_tag->field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
  }
  return ::rapidproto::DecodeStatus::success();
}

}  // namespace ed24::stream
