// Generated by rapidprotoc 0.2.3. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>

#include "rapidproto/runtime.hpp"
#include "naming.rp.common.hpp"  // IWYU pragma: export

namespace nm::stream {

using ::nm::E;

struct M;

struct M {
  explicit M(::rapidproto::ByteView bytes) noexcept : m_bytes(bytes) {}
  ::rapidproto::ByteView rp_bytes() const noexcept { return m_bytes; }

  struct int_;
  struct int_ {
    explicit int_(::rapidproto::ByteView bytes) noexcept : m_bytes(bytes) {}
    ::rapidproto::ByteView rp_bytes() const noexcept { return m_bytes; }

    struct x { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "x"; };

    template <class... Callbacks>
    [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
   private:
    ::rapidproto::ByteView m_bytes;
  };

  struct decode_ { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "decode"; };
  struct decode__ { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 2; static constexpr std::string_view kName = "decode_"; };
  struct int_field { using Value = ::nm::stream::M::int_; static constexpr std::uint32_t kNumber = 3; static constexpr std::string_view kName = "int_field"; };
  struct int__ { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 4; static constexpr std::string_view kName = "int_"; };
  struct e { using Value = ::nm::E; static constexpr std::uint32_t kNumber = 5; static constexpr std::string_view kName = "e"; };
  struct decode___ { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 6; static constexpr std::string_view kName = "decode__"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView m_bytes;
};

template <class... Callbacks>
::rapidproto::DecodeStatus M::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, decode_, decode__, int_field, int__, e, decode___>), "a callback matches no field of 'M' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  ::rapidproto::WireReader rp_reader{m_bytes};
  ::rapidproto::Tag rp_tag;
  for (;;) {
    if (rp_reader.at_end()) { return ::rapidproto::DecodeStatus::success(); }
    switch (rp_reader.peek_byte()) {
      case ::rapidproto::raw_tag(decode_::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, decode_, decode_::Value>)) <= 1U, "field 'decode_' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, decode_, decode_::Value>)) <= 1U, "field 'decode_' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, decode_, decode_::Value>), "a callback for field 'decode_' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, decode_, decode_::Value> && !::rapidproto::specifically_handles<Callbacks, decode_, decode_::Value>)), "a callback for field 'decode_' has the wrong value type (expected decode_::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, decode_, decode_::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, decode_{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(decode__::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, decode__, decode__::Value>)) <= 1U, "field 'decode__' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, decode__, decode__::Value>)) <= 1U, "field 'decode__' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, decode__, decode__::Value>), "a callback for field 'decode__' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, decode__, decode__::Value> && !::rapidproto::specifically_handles<Callbacks, decode__, decode__::Value>)), "a callback for field 'decode__' has the wrong value type (expected decode__::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, decode__, decode__::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, decode__{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(int_field::kNumber, ::rapidproto::WireType::Len):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, int_field, int_field::Value>)) <= 1U, "field 'int_field' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, int_field, int_field::Value>)) <= 1U, "field 'int_field' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, int_field, int_field::Value>), "a callback for field 'int_field' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, int_field, int_field::Value> && !::rapidproto::specifically_handles<Callbacks, int_field, int_field::Value>)), "a callback for field 'int_field' has the wrong value type (expected int_field::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, int_field, int_field::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_length_delimited();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, int_field{}, ::nm::stream::M::int_{*rp_value}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(int__::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, int__, int__::Value>)) <= 1U, "field 'int__' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, int__, int__::Value>)) <= 1U, "field 'int__' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, int__, int__::Value>), "a callback for field 'int__' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, int__, int__::Value> && !::rapidproto::specifically_handles<Callbacks, int__, int__::Value>)), "a callback for field 'int__' has the wrong value type (expected int__::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, int__, int__::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, int__{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(e::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, e, e::Value>)) <= 1U, "field 'e' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, e, e::Value>)) <= 1U, "field 'e' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, e, e::Value>), "a callback for field 'e' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, e, e::Value> && !::rapidproto::specifically_handles<Callbacks, e, e::Value>)), "a callback for field 'e' has the wrong value type (expected e::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, e, e::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, e{}, static_cast<::nm::E>(::rapidproto::varint_to_int32(*rp_value))); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(decode___::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, decode___, decode___::Value>)) <= 1U, "field 'decode___' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, decode___, decode___::Value>)) <= 1U, "field 'decode___' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, decode___, decode___::Value>), "a callback for field 'decode___' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, decode___, decode___::Value> && !::rapidproto::specifically_handles<Callbacks, decode___, decode___::Value>)), "a callback for field 'decode___' has the wrong value type (expected decode___::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, decode___, decode___::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, decode___{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      default: break;
    }
    const auto rp_state = rp_reader.read_tag_or_end(rp_tag);
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::Error) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
    switch (rp_tag.field_number) {
      case decode_::kNumber: break;
      case decode__::kNumber: break;
      case int_field::kNumber: break;
      case int__::kNumber: break;
      case e::kNumber: break;
      case decode___::kNumber: break;
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const auto rp_value_start = rp_reader.position();
          if (!rp_reader.skip(rp_tag.wire_type, rp_tag.field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, m_bytes.substr(rp_value_start, rp_reader.position() - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    if (!rp_reader.skip(rp_tag.wire_type, rp_tag.field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
  }
}

template <class... Callbacks>
::rapidproto::DecodeStatus M::int_::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, x>), "a callback matches no field of 'M::int_' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  ::rapidproto::WireReader rp_reader{m_bytes};
  ::rapidproto::Tag rp_tag;
  for (;;) {
    if (rp_reader.at_end()) { return ::rapidproto::DecodeStatus::success(); }
    switch (rp_reader.peek_byte()) {
      case ::rapidproto::raw_tag(x::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, x, x::Value>)) <= 1U, "field 'x' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, x, x::Value>)) <= 1U, "field 'x' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, x, x::Value>), "a callback for field 'x' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, x, x::Value> && !::rapidproto::specifically_handles<Callbacks, x, x::Value>)), "a callback for field 'x' has the wrong value type (expected x::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, x, x::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, x{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      default: break;
    }
    const auto rp_state = rp_reader.read_tag_or_end(rp_tag);
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::Error) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
    switch (rp_tag.field_number) {
      case x::kNumber: break;
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const auto rp_value_start = rp_reader.position();
          if (!rp_reader.skip(rp_tag.wire_type, rp_tag.field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, m_bytes.substr(rp_value_start, rp_reader.position() - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    if (!rp_reader.skip(rp_tag.wire_type, rp_tag.field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
  }
}

}  // namespace nm::stream
