// Generated by rapidprotoc 0.3.1. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>

#include "rapidproto/runtime.hpp"
#include "naming.rp.common.hpp"  // IWYU pragma: export

namespace nm::stream {

using ::nm::E;

struct M;
struct Outer;
struct m_bytes;
struct UsesMBytes;

struct M {
  explicit M(::rapidproto::ByteView bytes) noexcept : rp_span(bytes) {}
  ::rapidproto::ByteView rp_bytes() const noexcept { return rp_span; }

  struct int_;
  struct int_ {
    explicit int_(::rapidproto::ByteView bytes) noexcept : rp_span(bytes) {}
    ::rapidproto::ByteView rp_bytes() const noexcept { return rp_span; }

    struct x { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "x"; };

    template <class... Callbacks>
    [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
   private:
    ::rapidproto::ByteView rp_span;
  };

  struct decode_ { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "decode"; };
  struct decode__ { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 2; static constexpr std::string_view kName = "decode_"; };
  struct int_field { using Value = ::nm::stream::M::int_; static constexpr std::uint32_t kNumber = 3; static constexpr std::string_view kName = "int_field"; };
  struct int__ { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 4; static constexpr std::string_view kName = "int_"; };
  struct e { using Value = ::nm::E; static constexpr std::uint32_t kNumber = 5; static constexpr std::string_view kName = "e"; };
  struct decode___ { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 6; static constexpr std::string_view kName = "decode__"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView rp_span;
};

struct Outer {
  explicit Outer(::rapidproto::ByteView bytes) noexcept : rp_span(bytes) {}
  ::rapidproto::ByteView rp_bytes() const noexcept { return rp_span; }

  struct Outer_;
  struct Outer_ {
    explicit Outer_(::rapidproto::ByteView bytes) noexcept : rp_span(bytes) {}
    ::rapidproto::ByteView rp_bytes() const noexcept { return rp_span; }

    struct v { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "v"; };

    template <class... Callbacks>
    [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
   private:
    ::rapidproto::ByteView rp_span;
  };

  struct inner { using Value = ::nm::stream::Outer::Outer_; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "inner"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView rp_span;
};

struct m_bytes {
  explicit m_bytes(::rapidproto::ByteView bytes) noexcept : rp_span(bytes) {}
  ::rapidproto::ByteView rp_bytes() const noexcept { return rp_span; }

  struct v { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "v"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView rp_span;
};

struct UsesMBytes {
  explicit UsesMBytes(::rapidproto::ByteView bytes) noexcept : rp_span(bytes) {}
  ::rapidproto::ByteView rp_bytes() const noexcept { return rp_span; }

  struct m_bytes { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "m_bytes"; };
  struct other { using Value = std::string_view; static constexpr std::uint32_t kNumber = 2; static constexpr std::string_view kName = "other"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView rp_span;
};

template <class... Callbacks>
RP_FLATTEN ::rapidproto::DecodeStatus M::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, decode_, decode__, int_field, int__, e, decode___>), "a callback matches no field of 'M' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(rp_span);
  const std::uint8_t* const rp_cend = rp_c + rp_span.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { return ::rapidproto::DecodeStatus::success(); }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_1;
      case ::rapidproto::raw_tag(2, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_2;
      case ::rapidproto::raw_tag(3, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_3;
      case ::rapidproto::raw_tag(4, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_4;
      case ::rapidproto::raw_tag(5, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_5;
      case ::rapidproto::raw_tag(6, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_6;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, decode_, decode_::Value>)) <= 1U, "field 'decode_' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, decode_, decode_::Value>)) <= 1U, "field 'decode_' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, decode_, decode_::Value>), "a callback for field 'decode_' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, decode_, decode_::Value> && !::rapidproto::specifically_handles<Callbacks, decode_, decode_::Value>)), "a callback for field 'decode_' has the wrong value type (expected decode_::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, decode_, decode_::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, decode_{}, ::rapidproto::varint_to_int32(rp_raw)); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(2, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_2; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(3, ::rapidproto::WireType::Len)) { ++rp_c; goto rp_do_3; }
      continue;
    }
    rp_do_2: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, decode__, decode__::Value>)) <= 1U, "field 'decode__' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, decode__, decode__::Value>)) <= 1U, "field 'decode__' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, decode__, decode__::Value>), "a callback for field 'decode__' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, decode__, decode__::Value> && !::rapidproto::specifically_handles<Callbacks, decode__, decode__::Value>)), "a callback for field 'decode__' has the wrong value type (expected decode__::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, decode__, decode__::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, decode__{}, ::rapidproto::varint_to_int32(rp_raw)); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(3, ::rapidproto::WireType::Len)) { ++rp_c; goto rp_do_3; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(4, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_4; }
      continue;
    }
    rp_do_3: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, int_field, int_field::Value>)) <= 1U, "field 'int_field' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, int_field, int_field::Value>)) <= 1U, "field 'int_field' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, int_field, int_field::Value>), "a callback for field 'int_field' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, int_field, int_field::Value> && !::rapidproto::specifically_handles<Callbacks, int_field, int_field::Value>)), "a callback for field 'int_field' has the wrong value type (expected int_field::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, int_field, int_field::Value>)) {
        ::rapidproto::ByteView rp_val;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_val, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, int_field{}, ::nm::stream::M::int_{rp_val}); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        ::rapidproto::ByteView rp_skipview;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_skipview, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(4, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_4; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(5, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_5; }
      continue;
    }
    rp_do_4: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, int__, int__::Value>)) <= 1U, "field 'int__' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, int__, int__::Value>)) <= 1U, "field 'int__' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, int__, int__::Value>), "a callback for field 'int__' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, int__, int__::Value> && !::rapidproto::specifically_handles<Callbacks, int__, int__::Value>)), "a callback for field 'int__' has the wrong value type (expected int__::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, int__, int__::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, int__{}, ::rapidproto::varint_to_int32(rp_raw)); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(5, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_5; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(6, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_6; }
      continue;
    }
    rp_do_5: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, e, e::Value>)) <= 1U, "field 'e' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, e, e::Value>)) <= 1U, "field 'e' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, e, e::Value>), "a callback for field 'e' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, e, e::Value> && !::rapidproto::specifically_handles<Callbacks, e, e::Value>)), "a callback for field 'e' has the wrong value type (expected e::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, e, e::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, e{}, static_cast<::nm::E>(::rapidproto::varint_to_int32(rp_raw))); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(6, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_6; }
      continue;
    }
    rp_do_6: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, decode___, decode___::Value>)) <= 1U, "field 'decode___' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, decode___, decode___::Value>)) <= 1U, "field 'decode___' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, decode___, decode___::Value>), "a callback for field 'decode___' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, decode___, decode___::Value> && !::rapidproto::specifically_handles<Callbacks, decode___, decode___::Value>)), "a callback for field 'decode___' has the wrong value type (expected decode___::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, decode___, decode___::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, decode___{}, ::rapidproto::varint_to_int32(rp_raw)); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::wire::TagState::Error) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_1; } break; }
      case 2: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_2; } break; }
      case 3: { if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_3; } break; }
      case 4: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_4; } break; }
      case 5: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_5; } break; }
      case 6: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_6; } break; }
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const std::size_t rp_value_start = static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span));
          std::size_t rp_ufo = 0;
          const std::uint8_t* const rp_usp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_ufo);
          if (rp_usp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_ufo}; }
          rp_c = rp_usp;
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, rp_span.substr(rp_value_start, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span)) - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_fo}; }
    rp_c = rp_sp;
  }
}

template <class... Callbacks>
RP_FLATTEN ::rapidproto::DecodeStatus M::int_::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, x>), "a callback matches no field of 'M::int_' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(rp_span);
  const std::uint8_t* const rp_cend = rp_c + rp_span.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { return ::rapidproto::DecodeStatus::success(); }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_1;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, x, x::Value>)) <= 1U, "field 'x' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, x, x::Value>)) <= 1U, "field 'x' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, x, x::Value>), "a callback for field 'x' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, x, x::Value> && !::rapidproto::specifically_handles<Callbacks, x, x::Value>)), "a callback for field 'x' has the wrong value type (expected x::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, x, x::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, x{}, ::rapidproto::varint_to_int32(rp_raw)); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::wire::TagState::Error) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_1; } break; }
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const std::size_t rp_value_start = static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span));
          std::size_t rp_ufo = 0;
          const std::uint8_t* const rp_usp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_ufo);
          if (rp_usp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_ufo}; }
          rp_c = rp_usp;
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, rp_span.substr(rp_value_start, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span)) - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_fo}; }
    rp_c = rp_sp;
  }
}

template <class... Callbacks>
RP_FLATTEN ::rapidproto::DecodeStatus Outer::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, inner>), "a callback matches no field of 'Outer' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(rp_span);
  const std::uint8_t* const rp_cend = rp_c + rp_span.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { return ::rapidproto::DecodeStatus::success(); }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_1;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, inner, inner::Value>)) <= 1U, "field 'inner' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, inner, inner::Value>)) <= 1U, "field 'inner' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, inner, inner::Value>), "a callback for field 'inner' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, inner, inner::Value> && !::rapidproto::specifically_handles<Callbacks, inner, inner::Value>)), "a callback for field 'inner' has the wrong value type (expected inner::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, inner, inner::Value>)) {
        ::rapidproto::ByteView rp_val;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_val, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, inner{}, ::nm::stream::Outer::Outer_{rp_val}); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        ::rapidproto::ByteView rp_skipview;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_skipview, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::wire::TagState::Error) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_1; } break; }
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const std::size_t rp_value_start = static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span));
          std::size_t rp_ufo = 0;
          const std::uint8_t* const rp_usp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_ufo);
          if (rp_usp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_ufo}; }
          rp_c = rp_usp;
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, rp_span.substr(rp_value_start, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span)) - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_fo}; }
    rp_c = rp_sp;
  }
}

template <class... Callbacks>
RP_FLATTEN ::rapidproto::DecodeStatus Outer::Outer_::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, v>), "a callback matches no field of 'Outer::Outer_' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(rp_span);
  const std::uint8_t* const rp_cend = rp_c + rp_span.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { return ::rapidproto::DecodeStatus::success(); }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_1;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, v, v::Value>)) <= 1U, "field 'v' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, v, v::Value>)) <= 1U, "field 'v' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, v, v::Value>), "a callback for field 'v' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, v, v::Value> && !::rapidproto::specifically_handles<Callbacks, v, v::Value>)), "a callback for field 'v' has the wrong value type (expected v::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, v, v::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, v{}, ::rapidproto::varint_to_int32(rp_raw)); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::wire::TagState::Error) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_1; } break; }
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const std::size_t rp_value_start = static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span));
          std::size_t rp_ufo = 0;
          const std::uint8_t* const rp_usp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_ufo);
          if (rp_usp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_ufo}; }
          rp_c = rp_usp;
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, rp_span.substr(rp_value_start, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span)) - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_fo}; }
    rp_c = rp_sp;
  }
}

template <class... Callbacks>
RP_FLATTEN ::rapidproto::DecodeStatus m_bytes::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, v>), "a callback matches no field of 'm_bytes' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(rp_span);
  const std::uint8_t* const rp_cend = rp_c + rp_span.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { return ::rapidproto::DecodeStatus::success(); }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_1;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, v, v::Value>)) <= 1U, "field 'v' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, v, v::Value>)) <= 1U, "field 'v' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, v, v::Value>), "a callback for field 'v' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, v, v::Value> && !::rapidproto::specifically_handles<Callbacks, v, v::Value>)), "a callback for field 'v' has the wrong value type (expected v::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, v, v::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, v{}, ::rapidproto::varint_to_int32(rp_raw)); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::wire::TagState::Error) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_1; } break; }
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const std::size_t rp_value_start = static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span));
          std::size_t rp_ufo = 0;
          const std::uint8_t* const rp_usp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_ufo);
          if (rp_usp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_ufo}; }
          rp_c = rp_usp;
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, rp_span.substr(rp_value_start, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span)) - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_fo}; }
    rp_c = rp_sp;
  }
}

template <class... Callbacks>
RP_FLATTEN ::rapidproto::DecodeStatus UsesMBytes::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, m_bytes, other>), "a callback matches no field of 'UsesMBytes' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(rp_span);
  const std::uint8_t* const rp_cend = rp_c + rp_span.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { return ::rapidproto::DecodeStatus::success(); }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_1;
      case ::rapidproto::raw_tag(2, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_2;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, m_bytes, m_bytes::Value>)) <= 1U, "field 'm_bytes' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, m_bytes, m_bytes::Value>)) <= 1U, "field 'm_bytes' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, m_bytes, m_bytes::Value>), "a callback for field 'm_bytes' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, m_bytes, m_bytes::Value> && !::rapidproto::specifically_handles<Callbacks, m_bytes, m_bytes::Value>)), "a callback for field 'm_bytes' has the wrong value type (expected m_bytes::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, m_bytes, m_bytes::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, m_bytes{}, ::rapidproto::varint_to_int32(rp_raw)); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(2, ::rapidproto::WireType::Len)) { ++rp_c; goto rp_do_2; }
      continue;
    }
    rp_do_2: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, other, other::Value>)) <= 1U, "field 'other' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, other, other::Value>)) <= 1U, "field 'other' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, other, other::Value>), "a callback for field 'other' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, other, other::Value> && !::rapidproto::specifically_handles<Callbacks, other, other::Value>)), "a callback for field 'other' has the wrong value type (expected other::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, other, other::Value>)) {
        ::rapidproto::ByteView rp_val;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_val, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, other{}, rp_val); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        ::rapidproto::ByteView rp_skipview;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_skipview, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
        rp_c = rp_sp;
      }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::wire::TagState::Error) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span))}; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_1; } break; }
      case 2: { if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_2; } break; }
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const std::size_t rp_value_start = static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span));
          std::size_t rp_ufo = 0;
          const std::uint8_t* const rp_usp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_ufo);
          if (rp_usp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_ufo}; }
          rp_c = rp_usp;
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, rp_span.substr(rp_value_start, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(rp_span)) - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(rp_span), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_fo}; }
    rp_c = rp_sp;
  }
}

}  // namespace nm::stream
