// Generated by rapidprotoc 0.3.1. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>

#include "rapidproto/runtime.hpp"
#include "nopkg.rp.common.hpp"  // IWYU pragma: export

namespace stream {

struct Root;

struct Root {
  explicit Root(::rapidproto::ByteView bytes) noexcept : m_bytes(bytes) {}
  ::rapidproto::ByteView rp_bytes() const noexcept { return m_bytes; }

  struct Sub;
  struct Sub {
    explicit Sub(::rapidproto::ByteView bytes) noexcept : m_bytes(bytes) {}
    ::rapidproto::ByteView rp_bytes() const noexcept { return m_bytes; }

    struct y { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "y"; };

    template <class... Callbacks>
    [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
   private:
    ::rapidproto::ByteView m_bytes;
  };

  struct sub { using Value = ::stream::Root::Sub; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "sub"; };
  struct self { using Value = ::stream::Root; static constexpr std::uint32_t kNumber = 2; static constexpr std::string_view kName = "self"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView m_bytes;
};

template <class... Callbacks>
RP_FLATTEN ::rapidproto::DecodeStatus Root::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, sub, self>), "a callback matches no field of 'Root' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(m_bytes);
  const std::uint8_t* const rp_cend = rp_c + m_bytes.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { return ::rapidproto::DecodeStatus::success(); }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_1;
      case ::rapidproto::raw_tag(2, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_2;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, sub, sub::Value>)) <= 1U, "field 'sub' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, sub, sub::Value>)) <= 1U, "field 'sub' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, sub, sub::Value>), "a callback for field 'sub' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, sub, sub::Value> && !::rapidproto::specifically_handles<Callbacks, sub, sub::Value>)), "a callback for field 'sub' has the wrong value type (expected sub::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, sub, sub::Value>)) {
        ::rapidproto::ByteView rp_val;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_val, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, sub{}, ::stream::Root::Sub{rp_val}); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        ::rapidproto::ByteView rp_skipview;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_skipview, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
        rp_c = rp_sp;
      }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(2, ::rapidproto::WireType::Len)) { ++rp_c; goto rp_do_2; }
      continue;
    }
    rp_do_2: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, self, self::Value>)) <= 1U, "field 'self' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, self, self::Value>)) <= 1U, "field 'self' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, self, self::Value>), "a callback for field 'self' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, self, self::Value> && !::rapidproto::specifically_handles<Callbacks, self, self::Value>)), "a callback for field 'self' has the wrong value type (expected self::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, self, self::Value>)) {
        ::rapidproto::ByteView rp_val;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_val, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, self{}, ::stream::Root{rp_val}); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        ::rapidproto::ByteView rp_skipview;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_skipview, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
        rp_c = rp_sp;
      }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::wire::TagState::Error) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_1; } break; }
      case 2: { if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_2; } break; }
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const std::size_t rp_value_start = static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes));
          std::size_t rp_ufo = 0;
          const std::uint8_t* const rp_usp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(m_bytes), rp_tag, 0, &rp_we, &rp_ufo);
          if (rp_usp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_ufo}; }
          rp_c = rp_usp;
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, m_bytes.substr(rp_value_start, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes)) - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(m_bytes), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_fo}; }
    rp_c = rp_sp;
  }
}

template <class... Callbacks>
RP_FLATTEN ::rapidproto::DecodeStatus Root::Sub::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, y>), "a callback matches no field of 'Root::Sub' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(m_bytes);
  const std::uint8_t* const rp_cend = rp_c + m_bytes.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { return ::rapidproto::DecodeStatus::success(); }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_1;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, y, y::Value>)) <= 1U, "field 'y' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, y, y::Value>)) <= 1U, "field 'y' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, y, y::Value>), "a callback for field 'y' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, y, y::Value> && !::rapidproto::specifically_handles<Callbacks, y, y::Value>)), "a callback for field 'y' has the wrong value type (expected y::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, y, y::Value>)) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, y{}, ::rapidproto::varint_to_int32(rp_raw)); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        std::uint64_t rp_skip = 0;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_skip, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
        rp_c = rp_sp;
      }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::wire::TagState::Error) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_1; } break; }
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const std::size_t rp_value_start = static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes));
          std::size_t rp_ufo = 0;
          const std::uint8_t* const rp_usp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(m_bytes), rp_tag, 0, &rp_we, &rp_ufo);
          if (rp_usp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_ufo}; }
          rp_c = rp_usp;
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, m_bytes.substr(rp_value_start, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes)) - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(m_bytes), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_fo}; }
    rp_c = rp_sp;
  }
}

}  // namespace stream
