// Generated by rapidprotoc 0.1.0. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>

#include "rapidproto/runtime.hpp"
#include "packed.rp.common.hpp"  // IWYU pragma: export

namespace pk::stream {

struct Packed;

struct Packed {
  explicit Packed(::rapidproto::ByteView bytes) noexcept : m_bytes(bytes) {}

  struct pd { using Value = double; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "pd"; };
  struct psf { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 2; static constexpr std::string_view kName = "psf"; };
  struct pf { using Value = float; static constexpr std::uint32_t kNumber = 3; static constexpr std::string_view kName = "pf"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView m_bytes;
};

template <class... Callbacks>
::rapidproto::DecodeStatus Packed::decode(Callbacks&&... rp_callbacks) const {
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  ::rapidproto::WireReader rp_reader{m_bytes};
  while (!rp_reader.at_end()) {
    const auto rp_tag = rp_reader.read_tag();
    if (!rp_tag) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
    switch (rp_tag->field_number) {
      case pd::kNumber:
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, pd, pd::Value>)) <= 1U, "field 'pd' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, pd, pd::Value>)) <= 1U, "field 'pd' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, pd, pd::Value>), "a callback for field 'pd' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, pd, pd::Value> && !::rapidproto::specifically_handles<Callbacks, pd, pd::Value>)), "a callback for field 'pd' has the wrong value type (expected pd::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, pd, pd::Value>)) {
          if (rp_tag->wire_type == ::rapidproto::WireType::I64) {
            const auto rp_value = rp_reader.read_fixed64();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, pd{}, ::rapidproto::bit_cast_double(*rp_value)); !rp_status.ok()) {
              return rp_status;
            }
            continue;
          }
          if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
            const auto rp_packed = rp_reader.read_length_delimited();
            if (!rp_packed) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            ::rapidproto::WireReader rp_elements{*rp_packed};
            while (!rp_elements.at_end()) {
              const auto rp_value = rp_elements.read_fixed64();
              if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_elements); }
              if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, pd{}, ::rapidproto::bit_cast_double(*rp_value)); !rp_status.ok()) {
                return rp_status;
              }
            }
            continue;
          }
        }
        break;
      case psf::kNumber:
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, psf, psf::Value>)) <= 1U, "field 'psf' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, psf, psf::Value>)) <= 1U, "field 'psf' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, psf, psf::Value>), "a callback for field 'psf' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, psf, psf::Value> && !::rapidproto::specifically_handles<Callbacks, psf, psf::Value>)), "a callback for field 'psf' has the wrong value type (expected psf::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, psf, psf::Value>)) {
          if (rp_tag->wire_type == ::rapidproto::WireType::I32) {
            const auto rp_value = rp_reader.read_fixed32();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, psf{}, static_cast<std::int32_t>(*rp_value)); !rp_status.ok()) {
              return rp_status;
            }
            continue;
          }
          if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
            const auto rp_packed = rp_reader.read_length_delimited();
            if (!rp_packed) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            ::rapidproto::WireReader rp_elements{*rp_packed};
            while (!rp_elements.at_end()) {
              const auto rp_value = rp_elements.read_fixed32();
              if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_elements); }
              if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, psf{}, static_cast<std::int32_t>(*rp_value)); !rp_status.ok()) {
                return rp_status;
              }
            }
            continue;
          }
        }
        break;
      case pf::kNumber:
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, pf, pf::Value>)) <= 1U, "field 'pf' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, pf, pf::Value>)) <= 1U, "field 'pf' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, pf, pf::Value>), "a callback for field 'pf' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, pf, pf::Value> && !::rapidproto::specifically_handles<Callbacks, pf, pf::Value>)), "a callback for field 'pf' has the wrong value type (expected pf::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, pf, pf::Value>)) {
          if (rp_tag->wire_type == ::rapidproto::WireType::I32) {
            const auto rp_value = rp_reader.read_fixed32();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, pf{}, ::rapidproto::bit_cast_float(*rp_value)); !rp_status.ok()) {
              return rp_status;
            }
            continue;
          }
          if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
            const auto rp_packed = rp_reader.read_length_delimited();
            if (!rp_packed) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            ::rapidproto::WireReader rp_elements{*rp_packed};
            while (!rp_elements.at_end()) {
              const auto rp_value = rp_elements.read_fixed32();
              if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_elements); }
              if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, pf{}, ::rapidproto::bit_cast_float(*rp_value)); !rp_status.ok()) {
                return rp_status;
              }
            }
            continue;
          }
        }
        break;
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const auto rp_value_start = rp_reader.position();
          if (!rp_reader.skip(rp_tag->wire_type, rp_tag->field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag->field_number, rp_tag->wire_type, m_bytes.substr(rp_value_start, rp_reader.position() - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    if (!rp_reader.skip(rp_tag->wire_type, rp_tag->field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
  }
  return ::rapidproto::DecodeStatus::success();
}

}  // namespace pk::stream
