// Generated by rapidprotoc 0.2.3. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>

#include "rapidproto/runtime.hpp"
#include "proto3.rp.common.hpp"  // IWYU pragma: export

namespace p3::stream {

using ::p3::State;

struct Msg;

struct Msg {
  explicit Msg(::rapidproto::ByteView bytes) noexcept : m_bytes(bytes) {}
  ::rapidproto::ByteView rp_bytes() const noexcept { return m_bytes; }

  struct implicit_i { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "implicit_i"; };
  struct explicit_i { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 2; static constexpr std::string_view kName = "explicit_i"; };
  struct name { using Value = std::string_view; static constexpr std::uint32_t kNumber = 3; static constexpr std::string_view kName = "name"; };
  struct state { using Value = ::p3::State; static constexpr std::uint32_t kNumber = 4; static constexpr std::string_view kName = "state"; };
  struct self { using Value = ::p3::stream::Msg; static constexpr std::uint32_t kNumber = 5; static constexpr std::string_view kName = "self"; };
  struct nums { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 6; static constexpr std::string_view kName = "nums"; };
  struct unpacked { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 7; static constexpr std::string_view kName = "unpacked"; };
  struct states { using Value = ::p3::State; static constexpr std::uint32_t kNumber = 8; static constexpr std::string_view kName = "states"; };
  struct reals { using Value = double; static constexpr std::uint32_t kNumber = 12; static constexpr std::string_view kName = "reals"; };
  struct codes { using Value = std::uint32_t; static constexpr std::uint32_t kNumber = 13; static constexpr std::string_view kName = "codes"; };
  struct a { using Value = std::int32_t; static constexpr std::uint32_t kNumber = 10; static constexpr std::string_view kName = "a"; };
  struct b { using Value = std::string_view; static constexpr std::uint32_t kNumber = 11; static constexpr std::string_view kName = "b"; };
  struct counts { using Key = std::string_view; using Value = std::int32_t; static constexpr std::uint32_t kNumber = 9; static constexpr std::string_view kName = "counts"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView m_bytes;
};

template <class... Callbacks>
::rapidproto::DecodeStatus Msg::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, implicit_i, explicit_i, name, state, self, nums, unpacked, states, reals, codes, a, b, counts>), "a callback matches no field of 'Msg' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  ::rapidproto::WireReader rp_reader{m_bytes};
  ::rapidproto::Tag rp_tag;
  for (;;) {
    if (rp_reader.at_end()) { return ::rapidproto::DecodeStatus::success(); }
    switch (rp_reader.peek_byte()) {
      case ::rapidproto::raw_tag(implicit_i::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, implicit_i, implicit_i::Value>)) <= 1U, "field 'implicit_i' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, implicit_i, implicit_i::Value>)) <= 1U, "field 'implicit_i' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, implicit_i, implicit_i::Value>), "a callback for field 'implicit_i' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, implicit_i, implicit_i::Value> && !::rapidproto::specifically_handles<Callbacks, implicit_i, implicit_i::Value>)), "a callback for field 'implicit_i' has the wrong value type (expected implicit_i::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, implicit_i, implicit_i::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, implicit_i{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(explicit_i::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, explicit_i, explicit_i::Value>)) <= 1U, "field 'explicit_i' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, explicit_i, explicit_i::Value>)) <= 1U, "field 'explicit_i' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, explicit_i, explicit_i::Value>), "a callback for field 'explicit_i' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, explicit_i, explicit_i::Value> && !::rapidproto::specifically_handles<Callbacks, explicit_i, explicit_i::Value>)), "a callback for field 'explicit_i' has the wrong value type (expected explicit_i::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, explicit_i, explicit_i::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, explicit_i{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(name::kNumber, ::rapidproto::WireType::Len):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, name, name::Value>)) <= 1U, "field 'name' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, name, name::Value>)) <= 1U, "field 'name' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, name, name::Value>), "a callback for field 'name' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, name, name::Value> && !::rapidproto::specifically_handles<Callbacks, name, name::Value>)), "a callback for field 'name' has the wrong value type (expected name::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, name, name::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_length_delimited();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, name{}, *rp_value); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(state::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, state, state::Value>)) <= 1U, "field 'state' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, state, state::Value>)) <= 1U, "field 'state' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, state, state::Value>), "a callback for field 'state' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, state, state::Value> && !::rapidproto::specifically_handles<Callbacks, state, state::Value>)), "a callback for field 'state' has the wrong value type (expected state::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, state, state::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, state{}, static_cast<::p3::State>(::rapidproto::varint_to_int32(*rp_value))); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(self::kNumber, ::rapidproto::WireType::Len):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, self, self::Value>)) <= 1U, "field 'self' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, self, self::Value>)) <= 1U, "field 'self' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, self, self::Value>), "a callback for field 'self' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, self, self::Value> && !::rapidproto::specifically_handles<Callbacks, self, self::Value>)), "a callback for field 'self' has the wrong value type (expected self::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, self, self::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_length_delimited();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, self{}, ::p3::stream::Msg{*rp_value}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(nums::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, nums, nums::Value>)) <= 1U, "field 'nums' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, nums, nums::Value>)) <= 1U, "field 'nums' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, nums, nums::Value>), "a callback for field 'nums' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, nums, nums::Value> && !::rapidproto::specifically_handles<Callbacks, nums, nums::Value>)), "a callback for field 'nums' has the wrong value type (expected nums::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, nums, nums::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, nums{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(nums::kNumber, ::rapidproto::WireType::Len):
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, nums, nums::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_packed = rp_reader.read_length_delimited();
          if (!rp_packed) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          ::rapidproto::WireReader rp_elements{*rp_packed};
          while (!rp_elements.at_end()) {
            const auto rp_value = rp_elements.read_varint();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_elements); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, nums{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
              return rp_status;
            }
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(unpacked::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, unpacked, unpacked::Value>)) <= 1U, "field 'unpacked' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, unpacked, unpacked::Value>)) <= 1U, "field 'unpacked' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, unpacked, unpacked::Value>), "a callback for field 'unpacked' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, unpacked, unpacked::Value> && !::rapidproto::specifically_handles<Callbacks, unpacked, unpacked::Value>)), "a callback for field 'unpacked' has the wrong value type (expected unpacked::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, unpacked, unpacked::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, unpacked{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(unpacked::kNumber, ::rapidproto::WireType::Len):
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, unpacked, unpacked::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_packed = rp_reader.read_length_delimited();
          if (!rp_packed) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          ::rapidproto::WireReader rp_elements{*rp_packed};
          while (!rp_elements.at_end()) {
            const auto rp_value = rp_elements.read_varint();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_elements); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, unpacked{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
              return rp_status;
            }
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(states::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, states, states::Value>)) <= 1U, "field 'states' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, states, states::Value>)) <= 1U, "field 'states' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, states, states::Value>), "a callback for field 'states' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, states, states::Value> && !::rapidproto::specifically_handles<Callbacks, states, states::Value>)), "a callback for field 'states' has the wrong value type (expected states::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, states, states::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, states{}, static_cast<::p3::State>(::rapidproto::varint_to_int32(*rp_value))); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(states::kNumber, ::rapidproto::WireType::Len):
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, states, states::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_packed = rp_reader.read_length_delimited();
          if (!rp_packed) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          ::rapidproto::WireReader rp_elements{*rp_packed};
          while (!rp_elements.at_end()) {
            const auto rp_value = rp_elements.read_varint();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_elements); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, states{}, static_cast<::p3::State>(::rapidproto::varint_to_int32(*rp_value))); !rp_status.ok()) {
              return rp_status;
            }
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(reals::kNumber, ::rapidproto::WireType::I64):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, reals, reals::Value>)) <= 1U, "field 'reals' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, reals, reals::Value>)) <= 1U, "field 'reals' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, reals, reals::Value>), "a callback for field 'reals' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, reals, reals::Value> && !::rapidproto::specifically_handles<Callbacks, reals, reals::Value>)), "a callback for field 'reals' has the wrong value type (expected reals::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, reals, reals::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_fixed64();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, reals{}, ::rapidproto::bit_cast_double(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(reals::kNumber, ::rapidproto::WireType::Len):
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, reals, reals::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_packed = rp_reader.read_length_delimited();
          if (!rp_packed) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          ::rapidproto::WireReader rp_elements{*rp_packed};
          while (!rp_elements.at_end()) {
            const auto rp_value = rp_elements.read_fixed64();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_elements); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, reals{}, ::rapidproto::bit_cast_double(*rp_value)); !rp_status.ok()) {
              return rp_status;
            }
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(codes::kNumber, ::rapidproto::WireType::I32):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, codes, codes::Value>)) <= 1U, "field 'codes' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, codes, codes::Value>)) <= 1U, "field 'codes' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, codes, codes::Value>), "a callback for field 'codes' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, codes, codes::Value> && !::rapidproto::specifically_handles<Callbacks, codes, codes::Value>)), "a callback for field 'codes' has the wrong value type (expected codes::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, codes, codes::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_fixed32();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, codes{}, *rp_value); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(codes::kNumber, ::rapidproto::WireType::Len):
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, codes, codes::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_packed = rp_reader.read_length_delimited();
          if (!rp_packed) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          ::rapidproto::WireReader rp_elements{*rp_packed};
          while (!rp_elements.at_end()) {
            const auto rp_value = rp_elements.read_fixed32();
            if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_elements); }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, codes{}, *rp_value); !rp_status.ok()) {
              return rp_status;
            }
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(a::kNumber, ::rapidproto::WireType::Varint):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, a, a::Value>)) <= 1U, "field 'a' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, a, a::Value>)) <= 1U, "field 'a' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, a, a::Value>), "a callback for field 'a' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, a, a::Value> && !::rapidproto::specifically_handles<Callbacks, a, a::Value>)), "a callback for field 'a' has the wrong value type (expected a::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, a, a::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_varint();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, a{}, ::rapidproto::varint_to_int32(*rp_value)); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      case ::rapidproto::raw_tag(b::kNumber, ::rapidproto::WireType::Len):
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, b, b::Value>)) <= 1U, "field 'b' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, b, b::Value>)) <= 1U, "field 'b' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, b, b::Value>), "a callback for field 'b' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, b, b::Value> && !::rapidproto::specifically_handles<Callbacks, b, b::Value>)), "a callback for field 'b' has the wrong value type (expected b::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, b, b::Value>)) {
          rp_reader.consume_tag_byte();
          const auto rp_value = rp_reader.read_length_delimited();
          if (!rp_value) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, b{}, *rp_value); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
      default: break;
    }
    const auto rp_state = rp_reader.read_tag_or_end(rp_tag);
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::WireReader::TagOrEnd::Error) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
    switch (rp_tag.field_number) {
      case implicit_i::kNumber: break;
      case explicit_i::kNumber: break;
      case name::kNumber: break;
      case state::kNumber: break;
      case self::kNumber: break;
      case nums::kNumber: break;
      case unpacked::kNumber: break;
      case states::kNumber: break;
      case reals::kNumber: break;
      case codes::kNumber: break;
      case a::kNumber: break;
      case b::kNumber: break;
      case counts::kNumber:
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, counts, counts::Key, counts::Value>)) <= 1U, "map field 'counts' is handled by more than one callback");
        static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, counts, counts::Key, counts::Value>)) <= 1U, "map field 'counts' is matched by more than one catch-all callback");
        static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, counts, counts::Key, counts::Value>), "a callback for map field 'counts' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
        static_assert((true && ... && !(::rapidproto::targets<Callbacks, counts, counts::Key, counts::Value> && !::rapidproto::specifically_handles<Callbacks, counts, counts::Key, counts::Value>)), "a callback for map field 'counts' has the wrong value type (expected counts::Key, counts::Value)");
        if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, counts, counts::Key, counts::Value>)) {
          if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
            const auto rp_entry = rp_reader.read_length_delimited();
            if (!rp_entry) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
            counts::Key rp_key{};
            counts::Value rp_value{};
            ::rapidproto::WireReader rp_entry_reader{*rp_entry};
            ::rapidproto::Tag rp_et;
            for (;;) {
              const auto rp_es = rp_entry_reader.read_tag_or_end(rp_et);
              if (rp_es == ::rapidproto::WireReader::TagOrEnd::End) { break; }
              if (rp_es == ::rapidproto::WireReader::TagOrEnd::Error) { return ::rapidproto::DecodeStatus::from_reader(rp_entry_reader); }
              if (rp_et.field_number == 1 && rp_et.wire_type == ::rapidproto::WireType::Len) {
                const auto rp_v = rp_entry_reader.read_length_delimited();
                if (!rp_v) { return ::rapidproto::DecodeStatus::from_reader(rp_entry_reader); }
                rp_key = *rp_v;
              } else if (rp_et.field_number == 2 && rp_et.wire_type == ::rapidproto::WireType::Varint) {
                const auto rp_v = rp_entry_reader.read_varint();
                if (!rp_v) { return ::rapidproto::DecodeStatus::from_reader(rp_entry_reader); }
                rp_value = ::rapidproto::varint_to_int32(*rp_v);
              } else if (!rp_entry_reader.skip(rp_et.wire_type, rp_et.field_number)) {
                return ::rapidproto::DecodeStatus::from_reader(rp_entry_reader);
              }
            }
            if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, counts{}, rp_key, rp_value); !rp_status.ok()) {
              return rp_status;
            }
            continue;
          }
        }
        break;
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const auto rp_value_start = rp_reader.position();
          if (!rp_reader.skip(rp_tag.wire_type, rp_tag.field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, m_bytes.substr(rp_value_start, rp_reader.position() - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    if (!rp_reader.skip(rp_tag.wire_type, rp_tag.field_number)) { return ::rapidproto::DecodeStatus::from_reader(rp_reader); }
  }
}

}  // namespace p3::stream
