// Generated by rapidprotoc 0.3.1. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>

#include "rapidproto/runtime.hpp"
#include "xpkg.rp.common.hpp"  // IWYU pragma: export
#include "deep.rp.stream.hpp"

namespace other::stream {

struct Ref;

struct Ref {
  explicit Ref(::rapidproto::ByteView bytes) noexcept : m_bytes(bytes) {}
  ::rapidproto::ByteView rp_bytes() const noexcept { return m_bytes; }

  struct target { using Value = ::com::example::deep::stream::Outer; static constexpr std::uint32_t kNumber = 1; static constexpr std::string_view kName = "target"; };

  template <class... Callbacks>
  [[nodiscard]] ::rapidproto::DecodeStatus decode(Callbacks&&... rp_callbacks) const;
 private:
  ::rapidproto::ByteView m_bytes;
};

template <class... Callbacks>
RP_FLATTEN ::rapidproto::DecodeStatus Ref::decode(Callbacks&&... rp_callbacks) const {
  static_assert((true && ... && !::rapidproto::is_stray_callback<Callbacks, target>), "a callback matches no field of 'Ref' (and is not a catch-all or unknown-field handler)");
  [[maybe_unused]] auto rp_dispatch = ::rapidproto::combine(static_cast<Callbacks&&>(rp_callbacks)...);
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(m_bytes);
  const std::uint8_t* const rp_cend = rp_c + m_bytes.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { return ::rapidproto::DecodeStatus::success(); }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_1;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<Callbacks, target, target::Value>)) <= 1U, "field 'target' is handled by more than one callback");
      static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<Callbacks, target, target::Value>)) <= 1U, "field 'target' is matched by more than one catch-all callback");
      static_assert((true && ... && !::rapidproto::is_partial_generic<Callbacks, target, target::Value>), "a callback for field 'target' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
      static_assert((true && ... && !(::rapidproto::targets<Callbacks, target, target::Value> && !::rapidproto::specifically_handles<Callbacks, target, target::Value>)), "a callback for field 'target' has the wrong value type (expected target::Value)");
      if constexpr ((false || ... || ::rapidproto::handles_one<Callbacks, target, target::Value>)) {
        ::rapidproto::ByteView rp_val;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_val, &rp_we);
        if (rp_np == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
        rp_c = rp_np;
        if (const auto rp_status = ::rapidproto::invoke_field(rp_dispatch, target{}, ::com::example::deep::stream::Outer{rp_val}); !rp_status.ok()) {
          return rp_status;
        }
      } else {  // no callback for this field -> skip its value (compile-time wire)
        ::rapidproto::ByteView rp_skipview;
        const std::uint8_t* const rp_sp = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_skipview, &rp_we);
        if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
        rp_c = rp_sp;
      }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { return ::rapidproto::DecodeStatus::success(); }
    if (rp_state == ::rapidproto::wire::TagState::Error) { return ::rapidproto::DecodeStatus{rp_we, false, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes))}; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_1; } break; }
      default:
        if constexpr ((false || ... || ::rapidproto::specifically_handles_unknown<Callbacks>)) {
          const std::size_t rp_value_start = static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes));
          std::size_t rp_ufo = 0;
          const std::uint8_t* const rp_usp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(m_bytes), rp_tag, 0, &rp_we, &rp_ufo);
          if (rp_usp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_ufo}; }
          rp_c = rp_usp;
          if (const auto rp_status = ::rapidproto::invoke_unknown(rp_dispatch, ::rapidproto::UnknownField{rp_tag.field_number, rp_tag.wire_type, m_bytes.substr(rp_value_start, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(m_bytes)) - rp_value_start)}); !rp_status.ok()) {
            return rp_status;
          }
          continue;
        }
        break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(m_bytes), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { return ::rapidproto::DecodeStatus{rp_we, false, rp_fo}; }
    rp_c = rp_sp;
  }
}

}  // namespace other::stream
