// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Christian Vetter
//
// The one TU in the suite that holds BOTH models of the same schemas at once.
//
// That is the whole point of it. Every collision the per-model roots exist to close needs both
// headers present to be observable: with the models at `<pkg>::stream`, a top-level `message
// stream` made the arena class and the streaming namespace the same name, and a package like
// `sib.stream.logging.v1` landed on the parent package's streaming types. A test file that includes
// one model's goldens -- which is every other test file -- compiles happily through all of it.
//
// So the INCLUDES below are the test. The assertions only add what a compile cannot say by itself:
// that the two models' types are distinct, and that an enum is one shared type across them.

#include <catch_amalgamated.hpp>

#include <type_traits>

// From ONE golden dir generated by ONE invocation with both models -- a consumer's actual shape,
// and the only one with a single shared common header (see regen_goldens.sh [4b/5]).
#include "coexist_golden/rootenum.rp.hpp"
#include "coexist_golden/rootenum.rp.stream.hpp"
#include "coexist_golden/rootnames.rp.hpp"
#include "coexist_golden/rootnames.rp.stream.hpp"
#include "coexist_golden/sibparent.rp.hpp"
#include "coexist_golden/sibparent.rp.stream.hpp"
#include "coexist_golden/sibpkg.rp.hpp"
#include "coexist_golden/sibpkg.rp.stream.hpp"

TEST_CASE("coexistence: types named after the model roots", "[coexistence]") {
    // Messages named `stream` / `arena` / `enums`, both models in scope. Under the previous layout
    // the streaming header's `namespace rn::stream` and the arena header's `class rn::stream` were
    // the same name, and this TU did not compile.
    static_assert(!std::is_same_v<rp::arena::rn::stream, rp::stream::rn::stream>);
    static_assert(!std::is_same_v<rp::arena::rn::arena, rp::stream::rn::arena>);
    static_assert(!std::is_same_v<rp::arena::rn::enums, rp::stream::rn::enums>);
    // ...and a top-level enum of that name is ONE type, reached identically through either model.
    static_assert(std::is_same_v<rp::arena::re::stream, rp::stream::re::stream>);
    static_assert(std::is_same_v<rp::arena::re::arena, rp::enums::re::arena>);
    // A top-level enum named `rp`, the default prefix itself.
    static_assert(std::is_same_v<rp::arena::rn::rp, rp::enums::rn::rp>);
    CHECK(true);  // the compile is the assertion
}

TEST_CASE("coexistence: a package whose own name contains a model root", "[coexistence]") {
    // `sib` + `sib.stream.logging.v1`: the sub-package's namespace used to be opened exactly where
    // the parent's streaming types lived, so `sib::logging` and `sib::stream::logging` collided
    // between two different files' headers.
    static_assert(!std::is_same_v<rp::arena::sib::logging, rp::stream::sib::logging>);
    static_assert(std::is_class_v<rp::arena::sib::stream::logging::v1::Entry>);
    static_assert(std::is_class_v<rp::stream::sib::stream::logging::v1::Entry>);
    CHECK(true);
}
