#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Christian Vetter
"""The osmstat CTest: three assertions on the committed fixture.

1. testdata/mini.osm.pbf reproduces byte-identically from make_fixture.py (same discipline as
   the repo's goldens: a committed artifact must match its generator, or one of them changed
   without the other).
2. Both osmstat programs decode it successfully and print BYTE-IDENTICAL statistics on stdout
   (the two decode models must agree on what the file contains).
3. That output equals the golden below, hand-derived from what make_fixture.py encodes -- so a
   bug shared by BOTH models (which assertion 2 would miss) still fails.

Usage: check_fixture.py <fixture> <osmstat-arena> <osmstat-stream>
"""
import pathlib
import subprocess
import sys

# Derivation: entities 1001-1003 (dense) + 4001 (plain), way 2001 (3 refs), relation 3001
# (2 members); id sum 1001+1002+1003+2001+3001+4001 = 12009 = 0x2ee9. Tags: dense nodes carry
# highway=..., amenity=..., name=... (3), the plain node amenity=... (1), the way 2, the
# relation 1. Metadata: 3 DenseInfo rows + Info on the way and the plain node. Bbox: block 1 is
# granularity 100 with zero offsets over raw lat 530000000..530000020 / lon 88000000..88000020;
# block 2 is granularity 200, offsets +100/-100, raw lat 265000000 / lon 44000000.
GOLDEN = """\
blocks           2
nodes            4 (dense 3, plain 1)
ways             1 (refs 3)
relations        1 (members 2)
tags             7 (nodes 4, ways 2, relations 1)
metadata rows    5
id sum           0000000000002ee9
bbox             lat [53.0000000, 53.0000020]  lon [8.7999999, 8.8000020]
distinct keys    3
  key amenity                  3
  key highway                  2
  key name                     2
"""


def main() -> int:
    fixture, arena_bin, stream_bin = sys.argv[1], sys.argv[2], sys.argv[3]
    here = pathlib.Path(fixture).resolve().parent
    sys.path.insert(0, str(here))
    import make_fixture  # noqa: E402  (the generator next to the fixture)

    regenerated = make_fixture.build()
    committed = pathlib.Path(fixture).read_bytes()
    if regenerated != committed:
        print(f">> {fixture} does not reproduce from make_fixture.py "
              f"({len(committed)} committed vs {len(regenerated)} regenerated bytes) -- "
              "regenerate the fixture or revert the generator", file=sys.stderr)
        return 1

    outputs = {}
    for name, exe in (("arena", arena_bin), ("stream", stream_bin)):
        r = subprocess.run([exe, fixture], capture_output=True, text=True)
        if r.returncode != 0:
            print(f">> osmstat-{name} failed (exit {r.returncode}):\n{r.stderr}", file=sys.stderr)
            return 1
        outputs[name] = r.stdout

    if outputs["arena"] != outputs["stream"]:
        print(">> the two models disagree on the fixture:\n"
              f"--- arena ---\n{outputs['arena']}--- stream ---\n{outputs['stream']}",
              file=sys.stderr)
        return 1
    if outputs["arena"] != GOLDEN:
        print(f">> output does not match the golden:\n--- got ---\n{outputs['arena']}"
              f"--- expected ---\n{GOLDEN}", file=sys.stderr)
        return 1
    print("osmstat fixture ok (both models, golden output)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
