// Generated by rapidprotoc. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/arena_runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <string_view>
#include <type_traits>

#include "rapidproto/arena_runtime.hpp"
#include "xref.rp.common.hpp"  // IWYU pragma: export

namespace rp::xr {

class A;
class B;

class A {
 public:
  const ::rp::xr::B* b() const noexcept { return m_b; }
  std::int32_t id() const noexcept { return m_id; }
  [[nodiscard]] static const A* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(A& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  const ::rp::xr::B* m_b;
  std::int32_t m_id;
};
static_assert(::std::is_trivially_destructible_v<A>);

class B {
 public:
  const ::rp::xr::A* a() const noexcept { return m_a; }
  [[nodiscard]] static const B* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(B& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  const ::rp::xr::A* m_a;
};
static_assert(::std::is_trivially_destructible_v<B>);

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool A::rp_decode_into([[maybe_unused]] A& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          if (out.m_b != nullptr) { ::rapidproto::rp_fail_repeated_singular(err, 1); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::rp::xr::B* const rp_sub = arena.create<::rp::xr::B>();
          if (rp_sub == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          if (!::rapidproto::arena_detail::decode_into(*rp_sub, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_b = rp_sub;
          continue;
        }
        break;
      }
      case 2: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Varint) {
          const auto rp_v = reader.read_varint();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          out.m_id = ::rapidproto::varint_to_int32(*rp_v);
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const A* A::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  A* const rp_root = arena.create<A>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
inline bool B::rp_decode_into([[maybe_unused]] B& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  ::rapidproto::WireReader reader{body};
  while (!reader.at_end()) {
    const auto rp_tag = reader.read_tag();
    if (!rp_tag) { ::rapidproto::rp_fail_wire(err, reader); return false; }
    switch (rp_tag->field_number) {
      case 1: {
        if (rp_tag->wire_type == ::rapidproto::WireType::Len) {
          if (out.m_a != nullptr) { ::rapidproto::rp_fail_repeated_singular(err, 1); return false; }
          const auto rp_v = reader.read_length_delimited();
          if (!rp_v) { ::rapidproto::rp_fail_wire(err, reader); return false; }
          ::rp::xr::A* const rp_sub = arena.create<::rp::xr::A>();
          if (rp_sub == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          if (!::rapidproto::arena_detail::decode_into(*rp_sub, *rp_v, arena, depth + 1, err)) { return false; }
          out.m_a = rp_sub;
          continue;
        }
        break;
      }
      default: break;
    }
    if (!reader.skip(rp_tag->wire_type, rp_tag->field_number)) { ::rapidproto::rp_fail_wire(err, reader); return false; }
  }
  return true;
}
inline const B* B::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  B* const rp_root = arena.create<B>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

}  // namespace rp::xr
