// Generated by rapidprotoc 0.3.1 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "xref.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"

namespace rapidproto::dump {

inline const char* rp_dump_enum_name(::rp::xr::Version rp_e) {
  switch (static_cast<std::int32_t>(rp_e)) {
    case 0: return "VERSION_1";
    case 1: return "VERSION_2";
  }
  return nullptr;  // unknown (open enum): the caller renders UNKNOWN(<n>)
}

inline const char* rp_dump_enum_name(::rp::xr::Mixed rp_e) {
  switch (static_cast<std::int32_t>(rp_e)) {
    case 0: return "MIXED_A";
    case 1: return "OTHER";
  }
  return nullptr;  // unknown (open enum): the caller renders UNKNOWN(<n>)
}

inline const char* rp_dump_enum_name(::rp::xr::Stream rp_e) {
  switch (static_cast<std::int32_t>(rp_e)) {
    case 0: return "STREAM_OK";
    case 1: return "STREAM_EOF";
  }
  return nullptr;  // unknown (open enum): the caller renders UNKNOWN(<n>)
}

inline const char* rp_dump_enum_name(::rp::xr::Nested::Def::Kind rp_e) {
  switch (static_cast<std::int32_t>(rp_e)) {
    case 0: return "UNKNOWN";
    case 1: return "A";
  }
  return nullptr;  // unknown (open enum): the caller renders UNKNOWN(<n>)
}

inline const char* rp_dump_enum_name(::rp::xr::CousinB::Tag rp_e) {
  switch (static_cast<std::int32_t>(rp_e)) {
    case 0: return "NONE";
    case 1: return "X";
  }
  return nullptr;  // unknown (open enum): the caller renders UNKNOWN(<n>)
}

}  // namespace rapidproto::dump

namespace rp::xr {

inline void rp_dump_write(const ::rp::xr::A& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::B& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::Nested::User& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::Nested::Def::Inner& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::Nested::Def& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::Nested::P& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::Nested::Q& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::Nested& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::FwdMsg::Ref& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::FwdMsg::Target& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::FwdMsg& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::CousinA::Use& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::CousinA& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::CousinB::Thing& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::CousinB& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::ReservedNames& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::IntWrap& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::BoolWrap& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::rp::xr::BytesWrap& m, ::rapidproto::dump::Writer& w);

inline void rp_dump_write(const ::rp::xr::A& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.b()) {
      w.entry_sep(rp_first); w.key("b");
      rp_dump_write(*rp_p, w);
    }
    if (const auto rp_v = m.id(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("id");
      w.os() << rp_v;
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::A& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::A& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::B& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.a()) {
      w.entry_sep(rp_first); w.key("a");
      rp_dump_write(*rp_p, w);
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::B& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::B& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::Nested::User& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.single()) {
      w.entry_sep(rp_first); w.key("single");
      rp_dump_write(*rp_p, w);
    }
    if (const auto& rp_r = m.many(); !rp_r.empty()) {
      w.entry_sep(rp_first); w.key("many");
      w.group('[', ']', [&] {
        bool rp_efirst = true;
        for (const auto& rp_el : rp_r) {
          w.entry_sep(rp_efirst);
          rp_dump_write(rp_el, w);
          if (w.overflowed()) { break; }
        }
      });
    }
    if (const auto rp_v = m.kind(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("kind");
      { const auto rp_e = rp_v;
      if (const char* rp_nm = ::rapidproto::dump::rp_dump_enum_name(rp_e)) { w.os() << '"' << rp_nm << '"'; }
      else { w.os() << "\"UNKNOWN(" << static_cast<std::int32_t>(rp_e) << ")\""; } }
    }
    if (const auto& rp_r = m.kinds(); !rp_r.empty()) {
      w.entry_sep(rp_first); w.key("kinds");
      w.group('[', ']', [&] {
        bool rp_efirst = true;
        for (const auto& rp_el : rp_r) {
          w.entry_sep(rp_efirst);
          { const auto rp_e = rp_el;
          if (const char* rp_nm = ::rapidproto::dump::rp_dump_enum_name(rp_e)) { w.os() << '"' << rp_nm << '"'; }
          else { w.os() << "\"UNKNOWN(" << static_cast<std::int32_t>(rp_e) << ")\""; } }
          if (w.overflowed()) { break; }
        }
      });
    }
    if (const auto* rp_p = m.inner()) {
      w.entry_sep(rp_first); w.key("inner");
      rp_dump_write(*rp_p, w);
    }
    if (const auto& rp_r = m.inners(); !rp_r.empty()) {
      w.entry_sep(rp_first); w.key("inners");
      w.group('[', ']', [&] {
        bool rp_efirst = true;
        for (const auto& rp_el : rp_r) {
          w.entry_sep(rp_efirst);
          rp_dump_write(rp_el, w);
          if (w.overflowed()) { break; }
        }
      });
    }
    if (const auto& rp_mp = m.by_name(); !rp_mp.empty()) {
      w.entry_sep(rp_first); w.key("by_name");
      w.group('{', '}', [&] {
        bool rp_efirst = true;
        for (const auto& rp_ent : rp_mp) {
          w.entry_sep(rp_efirst);
          w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_ent.key()); w.os() << "\": ";
          if (const auto* rp_vp = rp_ent.value()) { rp_dump_write(*rp_vp, w); } else { w.os() << "null"; }
          if (w.overflowed()) { break; }
        }
      });
    }
    if (const auto& rp_mp = m.ranked(); !rp_mp.empty()) {
      w.entry_sep(rp_first); w.key("ranked");
      w.group('{', '}', [&] {
        bool rp_efirst = true;
        for (const auto& rp_ent : rp_mp) {
          w.entry_sep(rp_efirst);
          w.os() << '"' << rp_ent.key() << "\": ";
          { const auto rp_e = rp_ent.value();
          if (const char* rp_nm = ::rapidproto::dump::rp_dump_enum_name(rp_e)) { w.os() << '"' << rp_nm << '"'; }
          else { w.os() << "\"UNKNOWN(" << static_cast<std::int32_t>(rp_e) << ")\""; } }
          if (w.overflowed()) { break; }
        }
      });
    }
    m.pick([&](auto rp_tag, const auto& rp_v) {
      using RpTag = std::decay_t<decltype(rp_tag)>;
      if constexpr (std::is_same_v<RpTag, ::rp::xr::Nested::User::Pick::chosen>) {
        w.entry_sep(rp_first); w.key("chosen");
        rp_dump_write(rp_v, w);
      }
      if constexpr (std::is_same_v<RpTag, ::rp::xr::Nested::User::Pick::tagged>) {
        w.entry_sep(rp_first); w.key("tagged");
        { const auto rp_e = rp_v;
        if (const char* rp_nm = ::rapidproto::dump::rp_dump_enum_name(rp_e)) { w.os() << '"' << rp_nm << '"'; }
        else { w.os() << "\"UNKNOWN(" << static_cast<std::int32_t>(rp_e) << ")\""; } }
      }
    });
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::Nested::User& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::Nested::User& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::Nested::Def::Inner& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.s(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("s");
      w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_v); w.os() << '"';
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::Nested::Def::Inner& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::Nested::Def::Inner& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::Nested::Def& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.s(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("s");
      w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_v); w.os() << '"';
    }
    if (const auto rp_v = m.n(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("n");
      w.os() << rp_v;
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::Nested::Def& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::Nested::Def& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::Nested::P& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.q()) {
      w.entry_sep(rp_first); w.key("q");
      rp_dump_write(*rp_p, w);
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::Nested::P& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::Nested::P& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::Nested::Q& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.p()) {
      w.entry_sep(rp_first); w.key("p");
      rp_dump_write(*rp_p, w);
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::Nested::Q& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::Nested::Q& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::Nested& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::Nested& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::Nested& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::FwdMsg::Ref& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.one()) {
      w.entry_sep(rp_first); w.key("one");
      rp_dump_write(*rp_p, w);
    }
    if (const auto& rp_r = m.many(); !rp_r.empty()) {
      w.entry_sep(rp_first); w.key("many");
      w.group('[', ']', [&] {
        bool rp_efirst = true;
        for (const auto& rp_el : rp_r) {
          w.entry_sep(rp_efirst);
          rp_dump_write(rp_el, w);
          if (w.overflowed()) { break; }
        }
      });
    }
    if (const auto& rp_mp = m.by_id(); !rp_mp.empty()) {
      w.entry_sep(rp_first); w.key("by_id");
      w.group('{', '}', [&] {
        bool rp_efirst = true;
        for (const auto& rp_ent : rp_mp) {
          w.entry_sep(rp_efirst);
          w.os() << '"' << rp_ent.key() << "\": ";
          if (const auto* rp_vp = rp_ent.value()) { rp_dump_write(*rp_vp, w); } else { w.os() << "null"; }
          if (w.overflowed()) { break; }
        }
      });
    }
    m.pick([&](auto rp_tag, const auto& rp_v) {
      using RpTag = std::decay_t<decltype(rp_tag)>;
      if constexpr (std::is_same_v<RpTag, ::rp::xr::FwdMsg::Ref::Pick::chosen>) {
        w.entry_sep(rp_first); w.key("chosen");
        rp_dump_write(rp_v, w);
      }
    });
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::FwdMsg::Ref& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::FwdMsg::Ref& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::FwdMsg::Target& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.s(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("s");
      w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_v); w.os() << '"';
    }
    if (const auto rp_v = m.n(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("n");
      w.os() << rp_v;
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::FwdMsg::Target& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::FwdMsg::Target& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::FwdMsg& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::FwdMsg& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::FwdMsg& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::CousinA::Use& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.thing()) {
      w.entry_sep(rp_first); w.key("thing");
      rp_dump_write(*rp_p, w);
    }
    if (const auto& rp_r = m.things(); !rp_r.empty()) {
      w.entry_sep(rp_first); w.key("things");
      w.group('[', ']', [&] {
        bool rp_efirst = true;
        for (const auto& rp_el : rp_r) {
          w.entry_sep(rp_efirst);
          rp_dump_write(rp_el, w);
          if (w.overflowed()) { break; }
        }
      });
    }
    if (const auto rp_v = m.tag(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("tag");
      { const auto rp_e = rp_v;
      if (const char* rp_nm = ::rapidproto::dump::rp_dump_enum_name(rp_e)) { w.os() << '"' << rp_nm << '"'; }
      else { w.os() << "\"UNKNOWN(" << static_cast<std::int32_t>(rp_e) << ")\""; } }
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::CousinA::Use& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::CousinA::Use& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::CousinA& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::CousinA& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::CousinA& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::CousinB::Thing& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.s(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("s");
      w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_v); w.os() << '"';
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::CousinB::Thing& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::CousinB::Thing& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::CousinB& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::CousinB& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::CousinB& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::ReservedNames& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.value(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("value");
      w.os() << rp_v;
    }
    if (const auto rp_v = m.tag(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("tag");
      w.os() << rp_v;
    }
    if (const auto rp_v = m.status(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("status");
      w.os() << rp_v;
    }
    if (const auto rp_v = m.reader(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("reader");
      w.os() << rp_v;
    }
    if (const auto rp_v = m.dispatch(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("dispatch");
      w.os() << rp_v;
    }
    if (const auto rp_v = m.callbacks(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("callbacks");
      w.os() << rp_v;
    }
    if (const auto rp_v = m.read(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("read");
      w.os() << rp_v;
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::ReservedNames& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::ReservedNames& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::IntWrap& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.value(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("value");
      w.os() << rp_v;
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::IntWrap& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::IntWrap& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::BoolWrap& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.value(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("value");
      w.os() << rp_v;
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::BoolWrap& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::BoolWrap& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::rp::xr::BytesWrap& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.value(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("value");
      w.os() << '"'; ::rapidproto::dump::write_hex(w.os(), rp_v); w.os() << '"';
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::rp::xr::BytesWrap& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::rp::xr::BytesWrap& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

}  // namespace rp::xr
