#!/usr/bin/env python3
"""Embed the vendored well-known-type .proto sources into a generated C++ TU.

Reads every wellknown/*.proto and writes src/wellknown_generated.cpp, which defines
rapidproto::wellknown_source() (declared in include/rapidproto/wellknown.hpp). The
generated file is checked in; re-run this script whenever the vendored sources change:

    python3 wellknown/embed_wellknown.py

`--check` renders without writing and exits 1 on drift. check.sh's fixtures stage runs it, so
"re-run whenever the sources change" is a gate, not a memory: editing a vendored .proto without
regenerating used to ship a silently stale embed (test_wellknown pins the 11 names, which
catches a REMOVAL but not an edit or an addition).
"""

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = REPO / "wellknown"
OUT = REPO / "src" / "wellknown_generated.cpp"
IMPORT_PREFIX = "google/protobuf/"


# Raw-string delimiter. A source must not contain the closing sequence )DELIM" (checked below).
DELIM = "RPWK"
# Max BYTES per raw-string chunk. MSVC caps a single string literal (C2026); chunks stay well under
# it and are joined at run time, so no single literal -- and no compile-time concatenation of them --
# is ever large. gcc/clang have no such cap; the chunking is transparent to them.
CHUNK_BYTES = 8000


def _chunks(text: str) -> "list[str]":
    # Split into pieces of at most CHUNK_BYTES bytes, always on a CHARACTER boundary so a multi-byte
    # UTF-8 sequence (em-dashes etc. in the sources) is never cut -- each chunk is valid UTF-8 the
    # compiler can read, and the pieces reassemble byte-for-byte when concatenated.
    out: "list[str]" = []
    cur: "list[str]" = []
    cur_bytes = 0
    for ch in text:
        b = len(ch.encode("utf-8"))
        if cur and cur_bytes + b > CHUNK_BYTES:
            out.append("".join(cur))
            cur, cur_bytes = [], 0
        cur.append(ch)
        cur_bytes += b
    if cur:
        out.append("".join(cur))
    return out or [""]


def render() -> str:
    protos = sorted(SRC_DIR.glob("*.proto"))
    if not protos:
        sys.exit("embed_wellknown: no .proto files in wellknown/")

    out = [
        "// GENERATED by wellknown/embed_wellknown.py -- do not edit.\n",
        "// Sources are the vendored well-known types under wellknown/ (BSD-3-Clause).\n\n",
        '#include "rapidproto/wellknown.hpp"\n\n',
        "#include <array>\n",
        "#include <cstddef>\n",
        "#include <optional>\n",
        "#include <string>\n",
        "#include <string_view>\n\n",
        "namespace rapidproto {\n",
        "namespace {\n\n",
        # Each source is stored as raw-string chunks; concat joins them into one string. The caching
        # static is per SOURCE (in wellknown_source below), never here -- a static in this template
        # would be shared by every source with the same chunk count N and hand back the wrong text.
        "template <std::size_t N>\n",
        "std::string concat(const std::array<std::string_view, N>& chunks) {\n",
        "    std::string s;\n",
        "    for (const std::string_view chunk : chunks) {\n",
        "        s += chunk;\n",
        "    }\n",
        "    return s;\n",
        "}\n\n",
    ]
    entries = []
    for i, proto in enumerate(protos):
        text = proto.read_text(encoding="utf-8")
        if f"){DELIM}\"" in text:
            sys.exit(f"embed_wellknown: raw-string delimiter collision in {proto.name}")
        var = f"kWkt{i}"
        entries.append((IMPORT_PREFIX + proto.name, var))
        chunks = _chunks(text)
        out.append(f"constexpr std::array<std::string_view, {len(chunks)}> {var} = {{\n")
        for chunk in chunks:
            out.append(f'    R"{DELIM}({chunk}){DELIM}",\n')
        out.append("};\n\n")

    out.append("}  // namespace\n\n")
    out.append(
        "std::optional<std::string_view> wellknown_source(std::string_view import_path) {\n"
    )
    for import_path, var in entries:
        out.append(f'    if (import_path == "{import_path}") {{\n')
        out.append(f"        static const std::string text = concat({var});\n")
        out.append("        return text;\n")
        out.append("    }\n")
    out.append("    return std::nullopt;\n")
    out.append("}\n\n")
    out.append("}  // namespace rapidproto\n")

    return "".join(out)


def main() -> None:
    # Reject anything but the one flag: a typo'd `--chek` must not silently fall through to the
    # WRITE branch and overwrite the checked-in file where the caller meant to verify it.
    unknown = [a for a in sys.argv[1:] if a != "--check"]
    if unknown:
        sys.exit(f"embed_wellknown: unknown argument(s) {unknown}; the only flag is --check")
    text = render()
    count = text.count("constexpr std::array<std::string_view")
    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            sys.exit(f"embed_wellknown: {OUT.relative_to(REPO)} is STALE against wellknown/*.proto"
                     f" -- re-run wellknown/embed_wellknown.py and commit the result")
        print(f"embed_wellknown: {OUT.relative_to(REPO)} is current ({count} types)")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"embed_wellknown: wrote {OUT.relative_to(REPO)} ({count} types)")


if __name__ == "__main__":
    main()
