// Generated by rapidprotoc 0.3.1 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "arena_layout.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"

namespace rapidproto::dump::detail {

inline const char* rp_dump_enum_name(::al::Color rp_e) {
  switch (static_cast<std::int32_t>(rp_e)) {
    case 0: return "RED";
    case 1: return "GREEN";
    case 2: return "BLUE";
  }
  return nullptr;  // unknown (open enum): the caller renders UNKNOWN(<n>)
}

}  // namespace rapidproto::dump::detail

namespace al {

namespace rp_dump_detail {

inline void rp_dump_write(const ::al::Point& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::al::Big& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::al::HasString& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::al::BoolWrap& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::al::SelfRef& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::al::Layout& m, ::rapidproto::dump::Writer& w);

inline void rp_dump_write(const ::al::Point& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.x(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "x")) {
        w.os() << rp_v;
      }
    }
    if (const auto rp_v = m.y(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "y")) {
        w.os() << rp_v;
      }
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(const ::al::Big& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.a(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "a")) {
        w.os() << rp_v;
      }
    }
    if (const auto rp_v = m.b(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "b")) {
        w.os() << rp_v;
      }
    }
    if (const auto rp_v = m.c(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "c")) {
        w.os() << rp_v;
      }
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(const ::al::HasString& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.s(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "s")) {
        w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_v); w.os() << '"';
      }
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(const ::al::BoolWrap& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.value(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "value")) {
        w.os() << rp_v;
      }
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(const ::al::SelfRef& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.next()) {
      if (w.begin_field(rp_first, "next")) {
        w.push_path("next");
        ::al::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto rp_v = m.v(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "v")) {
        w.os() << rp_v;
      }
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(const ::al::Layout& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.b1(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "b1")) {
        w.os() << rp_v;
      }
    }
    if (const auto rp_v = m.big(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "big")) {
        w.os() << rp_v;
      }
    }
    if (const auto rp_v = m.b2(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "b2")) {
        w.os() << rp_v;
      }
    }
    if (const auto rp_v = m.small(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "small")) {
        w.os() << rp_v;
      }
    }
    if (const auto rp_v = m.opt()) {
      if (w.begin_field(rp_first, "opt")) {
        w.os() << *rp_v;
      }
    }
    if (const auto rp_v = m.name(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "name")) {
        w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_v); w.os() << '"';
      }
    }
    if (const auto rp_v = m.oname()) {
      if (w.begin_field(rp_first, "oname")) {
        w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), *rp_v); w.os() << '"';
      }
    }
    if (const auto rp_v = m.color(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "color")) {
        { const auto rp_e = rp_v;
        if (const char* rp_nm = ::rapidproto::dump::detail::rp_dump_enum_name(rp_e)) { w.os() << '"' << rp_nm << '"'; }
        else { w.os() << "\"UNKNOWN(" << static_cast<std::int32_t>(rp_e) << ")\""; } }
      }
    }
    if (const auto* rp_p = m.pt()) {
      if (w.begin_field(rp_first, "pt")) {
        w.push_path("pt");
        ::al::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto* rp_p = m.bg()) {
      if (w.begin_field(rp_first, "bg")) {
        w.push_path("bg");
        ::al::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto* rp_p = m.hs()) {
      if (w.begin_field(rp_first, "hs")) {
        w.push_path("hs");
        ::al::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto* rp_p = m.flag()) {
      if (w.begin_field(rp_first, "flag")) {
        w.push_path("flag");
        ::al::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto& rp_r = m.nums(); !rp_r.empty()) {
      if (w.begin_field(rp_first, "nums")) {
        w.group('[', ']', [&] {
          bool rp_efirst = true;
          for (const auto& rp_el : rp_r) {
            w.entry_sep(rp_efirst);
            w.os() << rp_el;
            if (w.overflowed()) { break; }
          }
        });
      }
    }
    if (const auto& rp_r = m.points(); !rp_r.empty()) {
      if (w.begin_field(rp_first, "points")) {
        w.push_path("points");
        w.group('[', ']', [&] {
          bool rp_efirst = true;
          for (const auto& rp_el : rp_r) {
            w.entry_sep(rp_efirst);
            ::al::rp_dump_detail::rp_dump_write(rp_el, w);
            if (w.overflowed()) { break; }
          }
        });
        w.pop_path();
      }
    }
    if (const auto& rp_r = m.labels(); !rp_r.empty()) {
      if (w.begin_field(rp_first, "labels")) {
        w.group('[', ']', [&] {
          bool rp_efirst = true;
          for (const auto& rp_el : rp_r) {
            w.entry_sep(rp_efirst);
            w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_el); w.os() << '"';
            if (w.overflowed()) { break; }
          }
        });
      }
    }
    if (const auto& rp_mp = m.counts(); !rp_mp.empty()) {
      if (w.begin_field(rp_first, "counts")) {
        w.group('{', '}', [&] {
          bool rp_efirst = true;
          for (const auto& rp_ent : rp_mp) {
            w.entry_sep(rp_efirst);
            w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_ent.key()); w.os() << "\": ";
            w.os() << rp_ent.value();
            if (w.overflowed()) { break; }
          }
        });
      }
    }
    if (const auto& rp_mp = m.grid(); !rp_mp.empty()) {
      if (w.begin_field(rp_first, "grid")) {
        w.push_path("grid");
        w.group('{', '}', [&] {
          bool rp_efirst = true;
          for (const auto& rp_ent : rp_mp) {
            w.entry_sep(rp_efirst);
            w.os() << '"' << rp_ent.key() << "\": ";
            if (const auto* rp_vp = rp_ent.value()) { ::al::rp_dump_detail::rp_dump_write(*rp_vp, w); } else { w.os() << "null"; }
            if (w.overflowed()) { break; }
          }
        });
        w.pop_path();
      }
    }
    m.choice([&](auto rp_tag, const auto& rp_v) {
      using RpTag = std::decay_t<decltype(rp_tag)>;
      if constexpr (std::is_same_v<RpTag, ::al::Layout::Choice::ci>) {
        if (w.begin_field(rp_first, "ci")) {
          w.os() << rp_v;
        }
      }
      if constexpr (std::is_same_v<RpTag, ::al::Layout::Choice::cs>) {
        if (w.begin_field(rp_first, "cs")) {
          w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_v); w.os() << '"';
        }
      }
      if constexpr (std::is_same_v<RpTag, ::al::Layout::Choice::cp>) {
        if (w.begin_field(rp_first, "cp")) {
          w.push_path("cp");
          ::al::rp_dump_detail::rp_dump_write(rp_v, w);
          w.pop_path();
        }
      }
    });
    (void)rp_first;
  });
}

}  // namespace rp_dump_detail

inline void rp_dump_write(std::ostream& rp_os, const ::al::Point& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_opts.width, rp_opts.indent, &rp_opts.skip);
  ::al::rp_dump_detail::rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::al::Point& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_opts); return rp_ss.str();
}

inline void rp_dump_write(std::ostream& rp_os, const ::al::Big& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_opts.width, rp_opts.indent, &rp_opts.skip);
  ::al::rp_dump_detail::rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::al::Big& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_opts); return rp_ss.str();
}

inline void rp_dump_write(std::ostream& rp_os, const ::al::HasString& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_opts.width, rp_opts.indent, &rp_opts.skip);
  ::al::rp_dump_detail::rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::al::HasString& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_opts); return rp_ss.str();
}

inline void rp_dump_write(std::ostream& rp_os, const ::al::BoolWrap& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_opts.width, rp_opts.indent, &rp_opts.skip);
  ::al::rp_dump_detail::rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::al::BoolWrap& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_opts); return rp_ss.str();
}

inline void rp_dump_write(std::ostream& rp_os, const ::al::SelfRef& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_opts.width, rp_opts.indent, &rp_opts.skip);
  ::al::rp_dump_detail::rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::al::SelfRef& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_opts); return rp_ss.str();
}

inline void rp_dump_write(std::ostream& rp_os, const ::al::Layout& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_opts.width, rp_opts.indent, &rp_opts.skip);
  ::al::rp_dump_detail::rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::al::Layout& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_opts); return rp_ss.str();
}

}  // namespace al
