// Generated by rapidprotoc 0.3.1. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/arena_runtime.hpp (Apache-2.0).
// field modes (23113b230f50018b): unknown *
#pragma once

#include <cstdint>
#include <optional>
#include <string_view>
#include <type_traits>
#include <variant>

#include "rapidproto/arena_runtime.hpp"
#include "arena_unknown.rp.common.hpp"  // IWYU pragma: export

namespace au {
inline namespace rp_modes_23113b230f50018b {

class Flag;
class Holder;

class Flag {
 public:
  bool value() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0; }
  bool has_unknown_fields() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 1)) != 0; }
  [[nodiscard]] static const Flag* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Flag& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<Flag>);

class Holder {
 public:
  const ::au::Flag* flag() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0 ? &m_flag : nullptr; }
  std::int32_t n() const noexcept { return m_n; }
  bool has_unknown_fields() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 1)) != 0; }
  [[nodiscard]] static const Holder* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class RpT> friend bool ::rapidproto::arena_detail::decode_into(RpT&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Holder& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  std::int32_t m_n;
  ::au::Flag m_flag;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<Holder>);

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
RP_FLATTEN inline bool Flag::rp_decode_into([[maybe_unused]] Flag& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(body);
  const std::uint8_t* const rp_cend = rp_c + body.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { break; }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_1;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np;
      if (::rapidproto::varint_to_bool(rp_raw)) { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0)); } else { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask & static_cast<std::uint8_t>(~(std::uint8_t{1} << 0))); }
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { break; }
    if (rp_state == ::rapidproto::wire::TagState::Error) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_1; } break; }
      default: { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 1)); break; }
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(body), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, rp_fo); return false; }
    rp_c = rp_sp;
  }
  return true;
}
inline const Flag* Flag::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (input.size() > UINT32_MAX) { ::rapidproto::rp_fail_input_too_large(err); return nullptr; }
  input = arena.adopt_input(input);
  if (input.data() == nullptr && input.size() != 0) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  Flag* const rp_root = arena.create<Flag>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
RP_FLATTEN inline bool Holder::rp_decode_into([[maybe_unused]] Holder& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(body);
  const std::uint8_t* const rp_cend = rp_c + body.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { break; }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_1;
      case ::rapidproto::raw_tag(2, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_2;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      if ((out.m_rp_mask & (std::uint8_t{1} << 0)) != 0) { ::rapidproto::rp_fail_repeated_singular(err, 1); return false; }
      ::rapidproto::ByteView rp_v;
      { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_v, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
      if (!::rapidproto::arena_detail::decode_into(out.m_flag, rp_v, arena, depth + 1, err)) { return false; }
      out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0));
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(2, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_2; }
      continue;
    }
    rp_do_2: {
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      out.m_n = ::rapidproto::varint_to_int32(rp_raw);
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { break; }
    if (rp_state == ::rapidproto::wire::TagState::Error) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_1; } break; }
      case 2: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_2; } break; }
      default: { out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 1)); break; }
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(body), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, rp_fo); return false; }
    rp_c = rp_sp;
  }
  return true;
}
inline const Holder* Holder::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (input.size() > UINT32_MAX) { ::rapidproto::rp_fail_input_too_large(err); return nullptr; }
  input = arena.adopt_input(input);
  if (input.data() == nullptr && input.size() != 0) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  Holder* const rp_root = arena.create<Holder>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

}  // namespace rp_modes_23113b230f50018b
}  // namespace au
