// Generated by rapidprotoc 0.3.1 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "arena_unknown.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"

namespace rapidproto::dump {

}  // namespace rapidproto::dump

namespace au {

inline void rp_dump_write(const ::au::Flag& m, ::rapidproto::dump::Writer& w);
inline void rp_dump_write(const ::au::Holder& m, ::rapidproto::dump::Writer& w);

inline void rp_dump_write(const ::au::Flag& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (m.has_unknown_fields()) { w.entry_sep(rp_first); w.os() << "\"has_unknown_fields\": true"; }
    if (const auto rp_v = m.value(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("value");
      w.os() << rp_v;
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::au::Flag& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::au::Flag& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

inline void rp_dump_write(const ::au::Holder& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (m.has_unknown_fields()) { w.entry_sep(rp_first); w.os() << "\"has_unknown_fields\": true"; }
    if (const auto* rp_p = m.flag()) {
      w.entry_sep(rp_first); w.key("flag");
      rp_dump_write(*rp_p, w);
    }
    if (const auto rp_v = m.n(); rp_v != decltype(rp_v){}) {
      w.entry_sep(rp_first); w.key("n");
      w.os() << rp_v;
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(std::ostream& rp_os, const ::au::Holder& m, std::size_t rp_width = 120) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_width);
  rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::au::Holder& m, std::size_t rp_width = 120) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_width); return rp_ss.str();
}

}  // namespace au
