// Generated by rapidprotoc 0.3.1 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "dep.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"

namespace rapidproto::dump::detail {

inline const char* rp_dump_enum_name(::dep::DepEnum rp_e) {
  switch (static_cast<std::int32_t>(rp_e)) {
    case 0: return "DEP_ZERO";
    case 1: return "DEP_ONE";
  }
  return nullptr;  // unknown (open enum): the caller renders UNKNOWN(<n>)
}

}  // namespace rapidproto::dump::detail

namespace dep {

namespace rp_dump_detail {

inline void rp_dump_write(const ::dep::Dep& m, ::rapidproto::dump::Writer& w);

inline void rp_dump_write(const ::dep::Dep& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.v()) {
      if (w.begin_field(rp_first, "v")) {
        w.os() << *rp_v;
      }
    }
    if (const auto rp_v = m.de()) {
      if (w.begin_field(rp_first, "de")) {
        { const auto rp_e = *rp_v;
        if (const char* rp_nm = ::rapidproto::dump::detail::rp_dump_enum_name(rp_e)) { w.os() << '"' << rp_nm << '"'; }
        else { w.os() << "\"UNKNOWN(" << static_cast<std::int32_t>(rp_e) << ")\""; } }
      }
    }
    (void)rp_first;
  });
}

}  // namespace rp_dump_detail

inline void rp_dump_write(std::ostream& rp_os, const ::dep::Dep& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  rp_os << std::boolalpha;
  ::rapidproto::dump::Writer w(rp_os, rp_opts.width, rp_opts.indent, &rp_opts.skip);
  ::dep::rp_dump_detail::rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::dep::Dep& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_opts); return rp_ss.str();
}

}  // namespace dep
