// Generated by rapidprotoc 0.3.1. DO NOT EDIT.
// Shared schema types (enums) for the generated decoders (Apache-2.0).
#pragma once

#include <cstdint>

namespace ed23 {

enum class E : std::int32_t {
  ZERO = 0,
  ONE = 1,
  rp_known_min = 0,
  rp_known_max = 1,
  rp_non_exhaustive_min = INT32_MIN,
  rp_non_exhaustive_max = INT32_MAX,
};

}  // namespace ed23
