// Generated by rapidprotoc 0.3.1 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstdint>
#include <ostream>
#include <type_traits>

#include "editions2023.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"

namespace rapidproto::dump_detail {

inline const char* rp_dump_enum_name(::rp::common::ed23::E rp_e) {
  switch (static_cast<std::int32_t>(rp_e)) {
    case 0: return "ZERO";
    case 1: return "ONE";
  }
  return nullptr;  // unknown (open enum): the caller renders UNKNOWN(<n>)
}

inline const char* rp_dump_enum_name(::rp::common::ed23::M::Inner rp_e) {
  switch (static_cast<std::int32_t>(rp_e)) {
    case 0: return "ZERO";
  }
  return nullptr;  // unknown (open enum): the caller renders UNKNOWN(<n>)
}

}  // namespace rapidproto::dump_detail

namespace rp::arena::ed23 {

namespace rp_dump_detail {

inline void rp_dump_write(const ::rp::arena::ed23::M& m, ::rapidproto::dump_detail::Writer& w);

inline void rp_dump_write(const ::rp::arena::ed23::M& m, ::rapidproto::dump_detail::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.implicit_scalar(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "implicit_scalar")) {
        ::rapidproto::dump_detail::write_int(w.os(), rp_v);
      }
    }
    if (const auto rp_v = m.explicit_scalar()) {
      if (w.begin_field(rp_first, "explicit_scalar")) {
        ::rapidproto::dump_detail::write_int(w.os(), *rp_v);
      }
    }
    if (const auto* rp_p = m.child()) {
      if (w.begin_field(rp_first, "child")) {
        w.push_path("child");
        ::rp::arena::ed23::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto& rp_r = m.packed_nums(); !rp_r.empty()) {
      if (w.begin_field(rp_first, "packed_nums")) {
        w.group('[', ']', [&] {
          bool rp_efirst = true;
          for (const auto& rp_el : rp_r) {
            w.entry_sep(rp_efirst);
            ::rapidproto::dump_detail::write_int(w.os(), rp_el);
            if (w.overflowed()) { break; }
          }
        });
      }
    }
    if (const auto& rp_r = m.expanded_nums(); !rp_r.empty()) {
      if (w.begin_field(rp_first, "expanded_nums")) {
        w.group('[', ']', [&] {
          bool rp_efirst = true;
          for (const auto& rp_el : rp_r) {
            w.entry_sep(rp_efirst);
            ::rapidproto::dump_detail::write_int(w.os(), rp_el);
            if (w.overflowed()) { break; }
          }
        });
      }
    }
    if (const auto* rp_p = m.delim()) {
      if (w.begin_field(rp_first, "delim")) {
        w.push_path("delim");
        ::rp::arena::ed23::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    (void)rp_first;
  });
}

}  // namespace rp_dump_detail

}  // namespace rp::arena::ed23

namespace rapidproto::dump_detail {

template <>
struct dumper<::rp::arena::ed23::M> {
  static void write(const ::rp::arena::ed23::M& m, Writer& w) { ::rp::arena::ed23::rp_dump_detail::rp_dump_write(m, w); }
};

}  // namespace rapidproto::dump_detail
