// Generated by rapidprotoc 0.4.0 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstdint>
#include <ostream>
#include <type_traits>

#include "forward.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"
#include "pub.rp.dump.hpp"

namespace rp::arena::fwd {

namespace rp_dump_detail {

inline void rp_dump_write(const ::rp::arena::fwd::Fwd& m, ::rapidproto::dump_detail::Writer& w);

inline void rp_dump_write(const ::rp::arena::fwd::Fwd& m, ::rapidproto::dump_detail::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.z()) {
      if (w.begin_field(rp_first, "z")) {
        ::rapidproto::dump_detail::write_int(w.os(), *rp_v);
      }
    }
    (void)rp_first;
  });
}

}  // namespace rp_dump_detail

}  // namespace rp::arena::fwd

namespace rapidproto::dump_detail {

template <>
struct dumper<::rp::arena::fwd::Fwd> {
  static void write(const ::rp::arena::fwd::Fwd& m, Writer& w) { ::rp::arena::fwd::rp_dump_detail::rp_dump_write(m, w); }
};

}  // namespace rapidproto::dump_detail
