// Generated by rapidprotoc 0.3.1 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "main.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"
#include "dep.rp.dump.hpp"
#include "forward.rp.dump.hpp"

namespace rp::arena::main {

namespace rp_dump_detail {

inline void rp_dump_write(const ::rp::arena::main::Main& m, ::rapidproto::dump_detail::Writer& w);

inline void rp_dump_write(const ::rp::arena::main::Main& m, ::rapidproto::dump_detail::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.d()) {
      if (w.begin_field(rp_first, "d")) {
        w.push_path("d");
        ::rp::arena::dep::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto* rp_p = m.p()) {
      if (w.begin_field(rp_first, "p")) {
        w.push_path("p");
        ::rp::arena::pub::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto* rp_p = m.f()) {
      if (w.begin_field(rp_first, "f")) {
        w.push_path("f");
        ::rp::arena::fwd::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto rp_v = m.e()) {
      if (w.begin_field(rp_first, "e")) {
        { const auto rp_e = *rp_v;
        if (const char* rp_nm = ::rapidproto::dump_detail::rp_dump_enum_name(rp_e)) { w.os() << '"' << rp_nm << '"'; }
        else { w.os() << "\"UNKNOWN("; ::rapidproto::dump_detail::write_int(w.os(), static_cast<std::int32_t>(rp_e)); w.os() << ")\""; } }
      }
    }
    if (const auto& rp_r = m.ds(); !rp_r.empty()) {
      if (w.begin_field(rp_first, "ds")) {
        w.push_path("ds");
        w.group('[', ']', [&] {
          bool rp_efirst = true;
          for (const auto& rp_el : rp_r) {
            w.entry_sep(rp_efirst);
            ::rp::arena::dep::rp_dump_detail::rp_dump_write(rp_el, w);
            if (w.overflowed()) { break; }
          }
        });
        w.pop_path();
      }
    }
    if (const auto& rp_mp = m.dm(); !rp_mp.empty()) {
      if (w.begin_field(rp_first, "dm")) {
        w.push_path("dm");
        w.group('{', '}', [&] {
          bool rp_efirst = true;
          for (const auto& rp_ent : rp_mp) {
            w.entry_sep(rp_efirst);
            w.os() << '"'; ::rapidproto::dump_detail::write_int(w.os(), rp_ent.key()); w.os() << "\": ";
            if (const auto* rp_vp = rp_ent.value()) { ::rp::arena::dep::rp_dump_detail::rp_dump_write(*rp_vp, w); } else { w.os() << "null"; }
            if (w.overflowed()) { break; }
          }
        });
        w.pop_path();
      }
    }
    m.choice([&](auto rp_tag, const auto& rp_v) {
      using rp_Tag = std::decay_t<decltype(rp_tag)>;
      if constexpr (std::is_same_v<rp_Tag, ::rp::arena::main::Main::Choice::od>) {
        if (w.begin_field(rp_first, "od")) {
          w.push_path("od");
          ::rp::arena::dep::rp_dump_detail::rp_dump_write(rp_v, w);
          w.pop_path();
        }
      }
      if constexpr (std::is_same_v<rp_Tag, ::rp::arena::main::Main::Choice::oi>) {
        if (w.begin_field(rp_first, "oi")) {
          ::rapidproto::dump_detail::write_int(w.os(), rp_v);
        }
      }
    });
    (void)rp_first;
  });
}

}  // namespace rp_dump_detail

}  // namespace rp::arena::main

namespace rapidproto::dump_detail {

template <>
struct dumper<::rp::arena::main::Main> {
  static void write(const ::rp::arena::main::Main& m, Writer& w) { ::rp::arena::main::rp_dump_detail::rp_dump_write(m, w); }
};

}  // namespace rapidproto::dump_detail
