// Generated by rapidprotoc 0.4.0. DO NOT EDIT.
// Generated from your schema; depends on rapidproto/arena_runtime.hpp (Apache-2.0).
#pragma once

#include <cstdint>
#include <optional>
#include <string_view>
#include <type_traits>
#include <variant>

#include "rapidproto/arena_runtime.hpp"
#include "proto3.rp.common.hpp"  // IWYU pragma: export

namespace rp::arena::p3 {

using ::rp::common::p3::State;

class Msg;

class Msg {
 public:
  struct Pick {
    struct a { using Value = std::int32_t; };
    struct b { using Value = std::string_view; };
    struct c { using Value = bool; };
    struct d { using Value = double; };
  };
  struct CountsEntry {
    std::string_view key() const noexcept { return rp_key.view(); }
    std::int32_t value() const noexcept { return rp_value; }
    friend class Msg;
   private:
    ::rapidproto::ArenaString rp_key;
    std::int32_t rp_value;
  };
  struct FlagsEntry {
    bool key() const noexcept { return rp_key; }
    std::string_view value() const noexcept { return rp_value.view(); }
    friend class Msg;
   private:
    ::rapidproto::ArenaString rp_value;
    bool rp_key;
  };
  struct TogglesEntry {
    std::string_view key() const noexcept { return rp_key.view(); }
    bool value() const noexcept { return rp_value; }
    friend class Msg;
   private:
    ::rapidproto::ArenaString rp_key;
    bool rp_value;
  };
  struct RatiosEntry {
    std::string_view key() const noexcept { return rp_key.view(); }
    double value() const noexcept { return rp_value; }
    friend class Msg;
   private:
    double rp_value;
    ::rapidproto::ArenaString rp_key;
  };
  std::int32_t implicit_i() const noexcept { return m_implicit_i; }
  std::optional<std::int32_t> explicit_i() const noexcept { return (m_rp_mask & (std::uint8_t{1} << 0)) != 0 ? std::optional<std::int32_t>(m_explicit_i) : std::nullopt; }
  std::string_view name() const noexcept { return m_name.view(); }
  ::rp::common::p3::State state() const noexcept { return m_state; }
  const ::rp::arena::p3::Msg* self() const noexcept { return m_self; }
  ::rapidproto::ArrayView<std::int32_t> nums() const noexcept { return m_nums; }
  ::rapidproto::ArrayView<std::int32_t> unpacked() const noexcept { return m_unpacked; }
  ::rapidproto::ArrayView<::rp::common::p3::State> states() const noexcept { return m_states; }
  ::rapidproto::ArrayView<double> reals() const noexcept { return m_reals; }
  ::rapidproto::ArrayView<std::uint32_t> codes() const noexcept { return m_codes; }
  ::rapidproto::ArrayView<bool> bools() const noexcept { return m_bools; }
  double ratio() const noexcept { return m_ratio; }
  float scale() const noexcept { return m_scale; }
  ::rapidproto::MapView<CountsEntry> counts() const noexcept { return m_counts; }
  ::rapidproto::MapView<FlagsEntry> flags() const noexcept { return m_flags; }
  ::rapidproto::MapView<TogglesEntry> toggles() const noexcept { return m_toggles; }
  ::rapidproto::MapView<RatiosEntry> ratios() const noexcept { return m_ratios; }
  template <class... rp_Fs> void pick(rp_Fs&&... rp_fs) const {
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<rp_Fs, Pick::a, typename Pick::a::Value>)) <= 1U, "oneof member 'Msg::a' is handled by more than one callback");
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<rp_Fs, Pick::a, typename Pick::a::Value>)) <= 1U, "oneof member 'Msg::a' is matched by more than one catch-all callback");
    static_assert((true && ... && !::rapidproto::is_partial_generic<rp_Fs, Pick::a, typename Pick::a::Value>), "a callback for oneof member 'Msg::a' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
    static_assert((true && ... && !(::rapidproto::targets<rp_Fs, Pick::a, typename Pick::a::Value> && !::rapidproto::specifically_handles<rp_Fs, Pick::a, typename Pick::a::Value>)), "a callback for oneof member 'Msg::a' has the wrong value type (expected Pick::a::Value)");
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<rp_Fs, Pick::b, typename Pick::b::Value>)) <= 1U, "oneof member 'Msg::b' is handled by more than one callback");
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<rp_Fs, Pick::b, typename Pick::b::Value>)) <= 1U, "oneof member 'Msg::b' is matched by more than one catch-all callback");
    static_assert((true && ... && !::rapidproto::is_partial_generic<rp_Fs, Pick::b, typename Pick::b::Value>), "a callback for oneof member 'Msg::b' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
    static_assert((true && ... && !(::rapidproto::targets<rp_Fs, Pick::b, typename Pick::b::Value> && !::rapidproto::specifically_handles<rp_Fs, Pick::b, typename Pick::b::Value>)), "a callback for oneof member 'Msg::b' has the wrong value type (expected Pick::b::Value)");
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<rp_Fs, Pick::c, typename Pick::c::Value>)) <= 1U, "oneof member 'Msg::c' is handled by more than one callback");
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<rp_Fs, Pick::c, typename Pick::c::Value>)) <= 1U, "oneof member 'Msg::c' is matched by more than one catch-all callback");
    static_assert((true && ... && !::rapidproto::is_partial_generic<rp_Fs, Pick::c, typename Pick::c::Value>), "a callback for oneof member 'Msg::c' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
    static_assert((true && ... && !(::rapidproto::targets<rp_Fs, Pick::c, typename Pick::c::Value> && !::rapidproto::specifically_handles<rp_Fs, Pick::c, typename Pick::c::Value>)), "a callback for oneof member 'Msg::c' has the wrong value type (expected Pick::c::Value)");
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<rp_Fs, Pick::d, typename Pick::d::Value>)) <= 1U, "oneof member 'Msg::d' is handled by more than one callback");
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<rp_Fs, Pick::d, typename Pick::d::Value>)) <= 1U, "oneof member 'Msg::d' is matched by more than one catch-all callback");
    static_assert((true && ... && !::rapidproto::is_partial_generic<rp_Fs, Pick::d, typename Pick::d::Value>), "a callback for oneof member 'Msg::d' is partially generic; use a concrete (Tag, Value) callback or a fully generic (auto, auto) catch-all");
    static_assert((true && ... && !(::rapidproto::targets<rp_Fs, Pick::d, typename Pick::d::Value> && !::rapidproto::specifically_handles<rp_Fs, Pick::d, typename Pick::d::Value>)), "a callback for oneof member 'Msg::d' has the wrong value type (expected Pick::d::Value)");
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::specifically_handles<rp_Fs, std::monostate>)) <= 1U, "a oneof's unset (std::monostate) state is handled by more than one callback");
    static_assert((0U + ... + static_cast<unsigned>(::rapidproto::is_catch_all<rp_Fs, std::monostate>)) <= 1U, "a oneof's unset (std::monostate) state is matched by more than one catch-all callback");
    static_assert((true && ... && !(::rapidproto::targets<rp_Fs, std::monostate> && !::rapidproto::specifically_handles<rp_Fs, std::monostate>)), "a callback for a oneof's unset (std::monostate) state must take exactly (std::monostate)");
    static_assert((true && ... && !::rapidproto::is_stray_handler<rp_Fs, Pick::a, Pick::b, Pick::c, Pick::d, std::monostate>), "a callback matches no member of oneof 'pick' (and is not a catch-all or the std::monostate unset handler)");
    auto rp_d = ::rapidproto::combine(static_cast<rp_Fs&&>(rp_fs)...);
    switch (m_rp_pick_case) {
      case 1:
        if constexpr ((false || ... || ::rapidproto::handles_one<rp_Fs, Pick::a, typename Pick::a::Value>)) {
        ::rapidproto::invoke_handler(rp_d, Pick::a{}, m_rp_pick.a);
        }
        break;
      case 2:
        if constexpr ((false || ... || ::rapidproto::handles_one<rp_Fs, Pick::b, typename Pick::b::Value>)) {
        ::rapidproto::invoke_handler(rp_d, Pick::b{}, m_rp_pick.b.view());
        }
        break;
      case 3:
        if constexpr ((false || ... || ::rapidproto::handles_one<rp_Fs, Pick::c, typename Pick::c::Value>)) {
        ::rapidproto::invoke_handler(rp_d, Pick::c{}, m_rp_pick.c);
        }
        break;
      case 4:
        if constexpr ((false || ... || ::rapidproto::handles_one<rp_Fs, Pick::d, typename Pick::d::Value>)) {
        ::rapidproto::invoke_handler(rp_d, Pick::d{}, m_rp_pick.d);
        }
        break;
      default:
        if constexpr ((false || ... || ::rapidproto::handles_one<rp_Fs, std::monostate>)) {
        ::rapidproto::invoke_handler(rp_d, std::monostate{});
        }
        break;
    }
  }
  [[nodiscard]] static const Msg* decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err = nullptr) noexcept;
 private:
  template <class rp_T> friend bool ::rapidproto::arena_detail::decode_into(rp_T&, ::rapidproto::ByteView, ::rapidproto::Arena&, int, ::rapidproto::ArenaDecodeError*) noexcept;
  static bool rp_decode_into(Msg& out, ::rapidproto::ByteView body, ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept;
  union rp_pick_union {
    std::int32_t a;
    ::rapidproto::ArenaString b;
    bool c;
    double d;
    rp_pick_union() noexcept {}
  };
  rp_pick_union m_rp_pick;
  const ::rp::arena::p3::Msg* m_self;
  double m_ratio;
  ::rapidproto::ArenaString m_name;
  ::rapidproto::ArrayView<std::int32_t> m_nums;
  ::rapidproto::ArrayView<std::int32_t> m_unpacked;
  ::rapidproto::ArrayView<::rp::common::p3::State> m_states;
  ::rapidproto::MapView<CountsEntry> m_counts;
  ::rapidproto::ArrayView<double> m_reals;
  ::rapidproto::ArrayView<std::uint32_t> m_codes;
  ::rapidproto::MapView<FlagsEntry> m_flags;
  ::rapidproto::ArrayView<bool> m_bools;
  ::rapidproto::MapView<TogglesEntry> m_toggles;
  ::rapidproto::MapView<RatiosEntry> m_ratios;
  std::int32_t m_implicit_i;
  std::int32_t m_explicit_i;
  ::rp::common::p3::State m_state;
  float m_scale;
  std::uint8_t m_rp_pick_case;
  std::uint8_t m_rp_mask;
};
static_assert(::std::is_trivially_destructible_v<Msg>);

// NOLINTNEXTLINE(readability-function-cognitive-complexity): generated field dispatch
RP_FLATTEN RP_NOINLINE inline bool ::rp::arena::p3::Msg::rp_decode_into([[maybe_unused]] ::rp::arena::p3::Msg& out, ::rapidproto::ByteView body, [[maybe_unused]] ::rapidproto::Arena& arena, int depth, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (depth > ::rapidproto::kMaxDecodeDepth) { ::rapidproto::rp_fail_recursion(err); return false; }
  std::int32_t* rp_acc_nums = nullptr;
  std::size_t rp_n_nums = 0;
  std::size_t rp_cap_nums = 0;
  const auto rp_slot_nums = [&]() noexcept -> std::int32_t* {
    if (rp_n_nums == rp_cap_nums) {
      const std::size_t rp_nc = rp_cap_nums == 0 ? std::size_t{4} : rp_cap_nums * 2;
      std::int32_t* const rp_nb = arena.allocate_array<std::int32_t>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_nums; ++rp_i) { rp_nb[rp_i] = rp_acc_nums[rp_i]; }
      rp_acc_nums = rp_nb;
      rp_cap_nums = rp_nc;
    }
    return &rp_acc_nums[rp_n_nums++];
  };
  std::int32_t* rp_acc_unpacked = nullptr;
  std::size_t rp_n_unpacked = 0;
  std::size_t rp_cap_unpacked = 0;
  const auto rp_slot_unpacked = [&]() noexcept -> std::int32_t* {
    if (rp_n_unpacked == rp_cap_unpacked) {
      const std::size_t rp_nc = rp_cap_unpacked == 0 ? std::size_t{4} : rp_cap_unpacked * 2;
      std::int32_t* const rp_nb = arena.allocate_array<std::int32_t>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_unpacked; ++rp_i) { rp_nb[rp_i] = rp_acc_unpacked[rp_i]; }
      rp_acc_unpacked = rp_nb;
      rp_cap_unpacked = rp_nc;
    }
    return &rp_acc_unpacked[rp_n_unpacked++];
  };
  ::rp::common::p3::State* rp_acc_states = nullptr;
  std::size_t rp_n_states = 0;
  std::size_t rp_cap_states = 0;
  const auto rp_slot_states = [&]() noexcept -> ::rp::common::p3::State* {
    if (rp_n_states == rp_cap_states) {
      const std::size_t rp_nc = rp_cap_states == 0 ? std::size_t{4} : rp_cap_states * 2;
      ::rp::common::p3::State* const rp_nb = arena.allocate_array<::rp::common::p3::State>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_states; ++rp_i) { rp_nb[rp_i] = rp_acc_states[rp_i]; }
      rp_acc_states = rp_nb;
      rp_cap_states = rp_nc;
    }
    return &rp_acc_states[rp_n_states++];
  };
  double* rp_acc_reals = nullptr;
  std::size_t rp_n_reals = 0;
  std::size_t rp_cap_reals = 0;
  const auto rp_slot_reals = [&]() noexcept -> double* {
    if (rp_n_reals == rp_cap_reals) {
      const std::size_t rp_nc = rp_cap_reals == 0 ? std::size_t{4} : rp_cap_reals * 2;
      double* const rp_nb = arena.allocate_array<double>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_reals; ++rp_i) { rp_nb[rp_i] = rp_acc_reals[rp_i]; }
      rp_acc_reals = rp_nb;
      rp_cap_reals = rp_nc;
    }
    return &rp_acc_reals[rp_n_reals++];
  };
  std::uint32_t* rp_acc_codes = nullptr;
  std::size_t rp_n_codes = 0;
  std::size_t rp_cap_codes = 0;
  const auto rp_slot_codes = [&]() noexcept -> std::uint32_t* {
    if (rp_n_codes == rp_cap_codes) {
      const std::size_t rp_nc = rp_cap_codes == 0 ? std::size_t{4} : rp_cap_codes * 2;
      std::uint32_t* const rp_nb = arena.allocate_array<std::uint32_t>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_codes; ++rp_i) { rp_nb[rp_i] = rp_acc_codes[rp_i]; }
      rp_acc_codes = rp_nb;
      rp_cap_codes = rp_nc;
    }
    return &rp_acc_codes[rp_n_codes++];
  };
  bool* rp_acc_bools = nullptr;
  std::size_t rp_n_bools = 0;
  std::size_t rp_cap_bools = 0;
  const auto rp_slot_bools = [&]() noexcept -> bool* {
    if (rp_n_bools == rp_cap_bools) {
      const std::size_t rp_nc = rp_cap_bools == 0 ? std::size_t{4} : rp_cap_bools * 2;
      bool* const rp_nb = arena.allocate_array<bool>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_bools; ++rp_i) { rp_nb[rp_i] = rp_acc_bools[rp_i]; }
      rp_acc_bools = rp_nb;
      rp_cap_bools = rp_nc;
    }
    return &rp_acc_bools[rp_n_bools++];
  };
  CountsEntry* rp_acc_counts = nullptr;
  std::size_t rp_n_counts = 0;
  std::size_t rp_cap_counts = 0;
  const auto rp_slot_counts = [&]() noexcept -> CountsEntry* {
    if (rp_n_counts == rp_cap_counts) {
      const std::size_t rp_nc = rp_cap_counts == 0 ? std::size_t{4} : rp_cap_counts * 2;
      CountsEntry* const rp_nb = arena.allocate_array<CountsEntry>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_counts; ++rp_i) { rp_nb[rp_i] = rp_acc_counts[rp_i]; }
      rp_acc_counts = rp_nb;
      rp_cap_counts = rp_nc;
    }
    return &rp_acc_counts[rp_n_counts++];
  };
  FlagsEntry* rp_acc_flags = nullptr;
  std::size_t rp_n_flags = 0;
  std::size_t rp_cap_flags = 0;
  const auto rp_slot_flags = [&]() noexcept -> FlagsEntry* {
    if (rp_n_flags == rp_cap_flags) {
      const std::size_t rp_nc = rp_cap_flags == 0 ? std::size_t{4} : rp_cap_flags * 2;
      FlagsEntry* const rp_nb = arena.allocate_array<FlagsEntry>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_flags; ++rp_i) { rp_nb[rp_i] = rp_acc_flags[rp_i]; }
      rp_acc_flags = rp_nb;
      rp_cap_flags = rp_nc;
    }
    return &rp_acc_flags[rp_n_flags++];
  };
  TogglesEntry* rp_acc_toggles = nullptr;
  std::size_t rp_n_toggles = 0;
  std::size_t rp_cap_toggles = 0;
  const auto rp_slot_toggles = [&]() noexcept -> TogglesEntry* {
    if (rp_n_toggles == rp_cap_toggles) {
      const std::size_t rp_nc = rp_cap_toggles == 0 ? std::size_t{4} : rp_cap_toggles * 2;
      TogglesEntry* const rp_nb = arena.allocate_array<TogglesEntry>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_toggles; ++rp_i) { rp_nb[rp_i] = rp_acc_toggles[rp_i]; }
      rp_acc_toggles = rp_nb;
      rp_cap_toggles = rp_nc;
    }
    return &rp_acc_toggles[rp_n_toggles++];
  };
  RatiosEntry* rp_acc_ratios = nullptr;
  std::size_t rp_n_ratios = 0;
  std::size_t rp_cap_ratios = 0;
  const auto rp_slot_ratios = [&]() noexcept -> RatiosEntry* {
    if (rp_n_ratios == rp_cap_ratios) {
      const std::size_t rp_nc = rp_cap_ratios == 0 ? std::size_t{4} : rp_cap_ratios * 2;
      RatiosEntry* const rp_nb = arena.allocate_array<RatiosEntry>(rp_nc);
      if (rp_nb == nullptr) { return nullptr; }
      for (std::size_t rp_i = 0; rp_i < rp_n_ratios; ++rp_i) { rp_nb[rp_i] = rp_acc_ratios[rp_i]; }
      rp_acc_ratios = rp_nb;
      rp_cap_ratios = rp_nc;
    }
    return &rp_acc_ratios[rp_n_ratios++];
  };
  const std::uint8_t* rp_c = ::rapidproto::wire::byte_ptr(body);
  const std::uint8_t* const rp_cend = rp_c + body.size();
  ::rapidproto::Tag rp_tag{};
  ::rapidproto::WireError rp_we = ::rapidproto::WireError::None;
  for (;;) {
    if (rp_c >= rp_cend) { break; }
    switch (*rp_c) {  // peek the 1-byte tag; threaded fields jump to their label
      case ::rapidproto::raw_tag(1, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_1;
      case ::rapidproto::raw_tag(2, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_2;
      case ::rapidproto::raw_tag(3, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_3;
      case ::rapidproto::raw_tag(4, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_4;
      case ::rapidproto::raw_tag(5, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_5;
      case ::rapidproto::raw_tag(6, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_6;
      case ::rapidproto::raw_tag(6, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_6_p;
      case ::rapidproto::raw_tag(7, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_7;
      case ::rapidproto::raw_tag(7, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_7_p;
      case ::rapidproto::raw_tag(8, ::rapidproto::WireType::Varint): ++rp_c; goto rp_do_8;
      case ::rapidproto::raw_tag(8, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_8_p;
      case ::rapidproto::raw_tag(12, ::rapidproto::WireType::I64): ++rp_c; goto rp_do_12;
      case ::rapidproto::raw_tag(12, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_12_p;
      case ::rapidproto::raw_tag(13, ::rapidproto::WireType::I32): ++rp_c; goto rp_do_13;
      case ::rapidproto::raw_tag(13, ::rapidproto::WireType::Len): ++rp_c; goto rp_do_13_p;
      default: break;
    }
    goto rp_field_general;
    rp_do_1: {
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      out.m_implicit_i = ::rapidproto::varint_to_int32(rp_raw);
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(2, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_2; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(3, ::rapidproto::WireType::Len)) { ++rp_c; goto rp_do_3; }
      continue;
    }
    rp_do_2: {
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      out.m_explicit_i = ::rapidproto::varint_to_int32(rp_raw);
      out.m_rp_mask = static_cast<std::uint8_t>(out.m_rp_mask | (std::uint8_t{1} << 0));
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(3, ::rapidproto::WireType::Len)) { ++rp_c; goto rp_do_3; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(4, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_4; }
      continue;
    }
    rp_do_3: {
      ::rapidproto::ByteView rp_v;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_v, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      out.m_name = ::rapidproto::ArenaString::make(rp_v, arena);
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(4, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_4; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(5, ::rapidproto::WireType::Len)) { ++rp_c; goto rp_do_5; }
      continue;
    }
    rp_do_4: {
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      out.m_state = static_cast<::rp::common::p3::State>(::rapidproto::varint_to_int32(rp_raw));
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(5, ::rapidproto::WireType::Len)) { ++rp_c; goto rp_do_5; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(6, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_6; }
      continue;
    }
    rp_do_5: {
      if (out.m_self != nullptr) { ::rapidproto::rp_fail_repeated_singular(err, 5); return false; }
      ::rapidproto::ByteView rp_v;
      { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_v, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
      ::rp::arena::p3::Msg* const rp_sub = arena.create<::rp::arena::p3::Msg>();
      if (rp_sub == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
      if (!::rapidproto::arena_detail::decode_into(*rp_sub, rp_v, arena, depth + 1, err)) { return false; }
      out.m_self = rp_sub;
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(6, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_6; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(7, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_7; }
      continue;
    }
    rp_do_6: {
      std::int32_t* const rp_slot = rp_slot_nums();
      if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      *rp_slot = ::rapidproto::varint_to_int32(rp_raw);
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(6, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_6; }  // another element of the same field
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(7, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_7; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(8, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_8; }
      continue;
    }
    rp_do_6_p: {
      ::rapidproto::ByteView rp_p;
      { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_p, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
      const std::size_t rp_ub = rp_p.size();
      if (rp_ub != 0 && rp_cap_nums < rp_n_nums + rp_ub) {
        const std::size_t rp_nc = rp_n_nums + rp_ub;
        std::int32_t* const rp_nb = arena.allocate_array<std::int32_t>(rp_nc);
        if (rp_nb == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
        for (std::size_t rp_i = 0; rp_i < rp_n_nums; ++rp_i) { rp_nb[rp_i] = rp_acc_nums[rp_i]; }
        rp_acc_nums = rp_nb;
        rp_cap_nums = rp_nc;
      }
      const std::uint8_t* rp_vp = ::rapidproto::wire::byte_ptr(rp_p);
      const std::uint8_t* const rp_ve = rp_vp + rp_p.size();
      if (rp_p.size() >= ::rapidproto::wire::kPackedKernelMinSpan) {
        const std::size_t rp_dc = ::rapidproto::arena_detail::decode_packed_varints_large<std::int32_t, ::rapidproto::wire::conv_int32>(rp_vp, rp_ve, rp_acc_nums + rp_n_nums, err);
        if (rp_dc == static_cast<std::size_t>(-1)) { return false; }
        rp_n_nums += rp_dc;
      } else {
        const std::size_t rp_dc = ::rapidproto::arena_detail::decode_packed_varints_small<std::int32_t, ::rapidproto::wire::conv_int32>(rp_vp, rp_ve, rp_acc_nums + rp_n_nums, err);
        if (rp_dc == static_cast<std::size_t>(-1)) { return false; }
        rp_n_nums += rp_dc;
      }
      arena.shrink_last(rp_acc_nums, rp_cap_nums * sizeof(std::int32_t), rp_n_nums * sizeof(std::int32_t));
      rp_cap_nums = rp_n_nums;
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(7, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_7; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(8, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_8; }
      continue;
    }
    rp_do_7: {
      std::int32_t* const rp_slot = rp_slot_unpacked();
      if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      *rp_slot = ::rapidproto::varint_to_int32(rp_raw);
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(7, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_7; }  // another element of the same field
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(8, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_8; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(12, ::rapidproto::WireType::I64)) { ++rp_c; goto rp_do_12; }
      continue;
    }
    rp_do_7_p: {
      ::rapidproto::ByteView rp_p;
      { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_p, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
      const std::size_t rp_ub = rp_p.size();
      if (rp_ub != 0 && rp_cap_unpacked < rp_n_unpacked + rp_ub) {
        const std::size_t rp_nc = rp_n_unpacked + rp_ub;
        std::int32_t* const rp_nb = arena.allocate_array<std::int32_t>(rp_nc);
        if (rp_nb == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
        for (std::size_t rp_i = 0; rp_i < rp_n_unpacked; ++rp_i) { rp_nb[rp_i] = rp_acc_unpacked[rp_i]; }
        rp_acc_unpacked = rp_nb;
        rp_cap_unpacked = rp_nc;
      }
      const std::uint8_t* rp_vp = ::rapidproto::wire::byte_ptr(rp_p);
      const std::uint8_t* const rp_ve = rp_vp + rp_p.size();
      if (rp_p.size() >= ::rapidproto::wire::kPackedKernelMinSpan) {
        const std::size_t rp_dc = ::rapidproto::arena_detail::decode_packed_varints_large<std::int32_t, ::rapidproto::wire::conv_int32>(rp_vp, rp_ve, rp_acc_unpacked + rp_n_unpacked, err);
        if (rp_dc == static_cast<std::size_t>(-1)) { return false; }
        rp_n_unpacked += rp_dc;
      } else {
        const std::size_t rp_dc = ::rapidproto::arena_detail::decode_packed_varints_small<std::int32_t, ::rapidproto::wire::conv_int32>(rp_vp, rp_ve, rp_acc_unpacked + rp_n_unpacked, err);
        if (rp_dc == static_cast<std::size_t>(-1)) { return false; }
        rp_n_unpacked += rp_dc;
      }
      arena.shrink_last(rp_acc_unpacked, rp_cap_unpacked * sizeof(std::int32_t), rp_n_unpacked * sizeof(std::int32_t));
      rp_cap_unpacked = rp_n_unpacked;
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(8, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_8; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(12, ::rapidproto::WireType::I64)) { ++rp_c; goto rp_do_12; }
      continue;
    }
    rp_do_8: {
      ::rp::common::p3::State* const rp_slot = rp_slot_states();
      if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      *rp_slot = static_cast<::rp::common::p3::State>(::rapidproto::varint_to_int32(rp_raw));
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(8, ::rapidproto::WireType::Varint)) { ++rp_c; goto rp_do_8; }  // another element of the same field
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(12, ::rapidproto::WireType::I64)) { ++rp_c; goto rp_do_12; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(13, ::rapidproto::WireType::I32)) { ++rp_c; goto rp_do_13; }
      continue;
    }
    rp_do_8_p: {
      ::rapidproto::ByteView rp_p;
      { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_p, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
      const std::size_t rp_ub = rp_p.size();
      if (rp_ub != 0 && rp_cap_states < rp_n_states + rp_ub) {
        const std::size_t rp_nc = rp_n_states + rp_ub;
        ::rp::common::p3::State* const rp_nb = arena.allocate_array<::rp::common::p3::State>(rp_nc);
        if (rp_nb == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
        for (std::size_t rp_i = 0; rp_i < rp_n_states; ++rp_i) { rp_nb[rp_i] = rp_acc_states[rp_i]; }
        rp_acc_states = rp_nb;
        rp_cap_states = rp_nc;
      }
      const std::uint8_t* rp_vp = ::rapidproto::wire::byte_ptr(rp_p);
      const std::uint8_t* const rp_ve = rp_vp + rp_p.size();
      if (rp_p.size() >= ::rapidproto::wire::kPackedKernelMinSpan) {
        const std::size_t rp_dc = ::rapidproto::arena_detail::decode_packed_varints_large<::rp::common::p3::State, ::rapidproto::wire::conv_enum<::rp::common::p3::State>>(rp_vp, rp_ve, rp_acc_states + rp_n_states, err);
        if (rp_dc == static_cast<std::size_t>(-1)) { return false; }
        rp_n_states += rp_dc;
      } else {
        const std::size_t rp_dc = ::rapidproto::arena_detail::decode_packed_varints_small<::rp::common::p3::State, ::rapidproto::wire::conv_enum<::rp::common::p3::State>>(rp_vp, rp_ve, rp_acc_states + rp_n_states, err);
        if (rp_dc == static_cast<std::size_t>(-1)) { return false; }
        rp_n_states += rp_dc;
      }
      arena.shrink_last(rp_acc_states, rp_cap_states * sizeof(::rp::common::p3::State), rp_n_states * sizeof(::rp::common::p3::State));
      rp_cap_states = rp_n_states;
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(12, ::rapidproto::WireType::I64)) { ++rp_c; goto rp_do_12; }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(13, ::rapidproto::WireType::I32)) { ++rp_c; goto rp_do_13; }
      continue;
    }
    rp_do_12: {
      double* const rp_slot = rp_slot_reals();
      if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_fixed64(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      *rp_slot = ::rapidproto::bit_cast_double(rp_raw);
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(12, ::rapidproto::WireType::I64)) { ++rp_c; goto rp_do_12; }  // another element of the same field
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(13, ::rapidproto::WireType::I32)) { ++rp_c; goto rp_do_13; }
      if (rp_c + 1 < rp_cend && rp_c[0] == 161 && rp_c[1] == 1) { rp_c += 2; goto rp_do_20; }
      continue;
    }
    rp_do_12_p: {
      ::rapidproto::ByteView rp_p;
      { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_p, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
      const std::size_t rp_ub = rp_p.size() / 8;
      if (rp_ub != 0 && rp_cap_reals < rp_n_reals + rp_ub) {
        const std::size_t rp_nc = rp_n_reals + rp_ub;
        double* const rp_nb = arena.allocate_array<double>(rp_nc);
        if (rp_nb == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
        for (std::size_t rp_i = 0; rp_i < rp_n_reals; ++rp_i) { rp_nb[rp_i] = rp_acc_reals[rp_i]; }
        rp_acc_reals = rp_nb;
        rp_cap_reals = rp_nc;
      }
      if constexpr (::rapidproto::arena_detail::kFixedIsNativeLE) {
        if (rp_p.size() % sizeof(double) == 0) {
          if (rp_ub != 0) { std::memcpy(rp_acc_reals + rp_n_reals, rp_p.data(), rp_p.size()); }
          rp_n_reals += rp_ub;
          continue;
        }
      }
      const std::uint8_t* rp_vp = ::rapidproto::wire::byte_ptr(rp_p);
      const std::uint8_t* const rp_vbeg = rp_vp;
      const std::uint8_t* const rp_ve = rp_vp + rp_p.size();
      while (rp_vp < rp_ve) {
        std::uint64_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_fixed64(rp_vp, rp_ve, &rp_raw, &rp_we);
        if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_vp - rp_vbeg)); return false; }
        rp_vp = rp_np;
        rp_acc_reals[rp_n_reals] = ::rapidproto::bit_cast_double(rp_raw);
        ++rp_n_reals;
      }
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(13, ::rapidproto::WireType::I32)) { ++rp_c; goto rp_do_13; }
      if (rp_c + 1 < rp_cend && rp_c[0] == 161 && rp_c[1] == 1) { rp_c += 2; goto rp_do_20; }
      continue;
    }
    rp_do_13: {
      std::uint32_t* const rp_slot = rp_slot_codes();
      if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
      std::uint32_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_fixed32(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      *rp_slot = rp_raw;
      if (rp_c < rp_cend && *rp_c == ::rapidproto::raw_tag(13, ::rapidproto::WireType::I32)) { ++rp_c; goto rp_do_13; }  // another element of the same field
      if (rp_c + 1 < rp_cend && rp_c[0] == 161 && rp_c[1] == 1) { rp_c += 2; goto rp_do_20; }
      if (rp_c + 1 < rp_cend && rp_c[0] == 173 && rp_c[1] == 1) { rp_c += 2; goto rp_do_21; }
      continue;
    }
    rp_do_13_p: {
      ::rapidproto::ByteView rp_p;
      { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_p, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
      const std::size_t rp_ub = rp_p.size() / 4;
      if (rp_ub != 0 && rp_cap_codes < rp_n_codes + rp_ub) {
        const std::size_t rp_nc = rp_n_codes + rp_ub;
        std::uint32_t* const rp_nb = arena.allocate_array<std::uint32_t>(rp_nc);
        if (rp_nb == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
        for (std::size_t rp_i = 0; rp_i < rp_n_codes; ++rp_i) { rp_nb[rp_i] = rp_acc_codes[rp_i]; }
        rp_acc_codes = rp_nb;
        rp_cap_codes = rp_nc;
      }
      if constexpr (::rapidproto::arena_detail::kFixedIsNativeLE) {
        if (rp_p.size() % sizeof(std::uint32_t) == 0) {
          if (rp_ub != 0) { std::memcpy(rp_acc_codes + rp_n_codes, rp_p.data(), rp_p.size()); }
          rp_n_codes += rp_ub;
          continue;
        }
      }
      const std::uint8_t* rp_vp = ::rapidproto::wire::byte_ptr(rp_p);
      const std::uint8_t* const rp_vbeg = rp_vp;
      const std::uint8_t* const rp_ve = rp_vp + rp_p.size();
      while (rp_vp < rp_ve) {
        std::uint32_t rp_raw = 0;
        const std::uint8_t* const rp_np = ::rapidproto::wire::read_fixed32(rp_vp, rp_ve, &rp_raw, &rp_we);
        if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_vp - rp_vbeg)); return false; }
        rp_vp = rp_np;
        rp_acc_codes[rp_n_codes] = rp_raw;
        ++rp_n_codes;
      }
      if (rp_c + 1 < rp_cend && rp_c[0] == 161 && rp_c[1] == 1) { rp_c += 2; goto rp_do_20; }
      if (rp_c + 1 < rp_cend && rp_c[0] == 173 && rp_c[1] == 1) { rp_c += 2; goto rp_do_21; }
      continue;
    }
    rp_do_20: {
      std::uint64_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_fixed64(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      out.m_ratio = ::rapidproto::bit_cast_double(rp_raw);
      if (rp_c + 1 < rp_cend && rp_c[0] == 173 && rp_c[1] == 1) { rp_c += 2; goto rp_do_21; }
      continue;
    }
    rp_do_21: {
      std::uint32_t rp_raw = 0;
      const std::uint8_t* const rp_np = ::rapidproto::wire::read_fixed32(rp_c, rp_cend, &rp_raw, &rp_we);
      if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
      rp_c = rp_np;
      out.m_scale = ::rapidproto::bit_cast_float(rp_raw);
      continue;
    }
    rp_field_general:;
    ::rapidproto::wire::TagState rp_state = ::rapidproto::wire::TagState::End;
    const std::uint8_t* const rp_tp = ::rapidproto::wire::read_tag_or_end(rp_c, rp_cend, &rp_tag, &rp_we, &rp_state);
    if (rp_state == ::rapidproto::wire::TagState::End) { break; }
    if (rp_state == ::rapidproto::wire::TagState::Error) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
    rp_c = rp_tp;
    switch (rp_tag.field_number) {
      case 1: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_1; } break; }
      case 2: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_2; } break; }
      case 3: { if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_3; } break; }
      case 4: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_4; } break; }
      case 5: { if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_5; } break; }
      case 6: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_6; } if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_6_p; } break; }
      case 7: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_7; } if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_7_p; } break; }
      case 8: { if (rp_tag.wire_type == ::rapidproto::WireType::Varint) { goto rp_do_8; } if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_8_p; } break; }
      case 12: { if (rp_tag.wire_type == ::rapidproto::WireType::I64) { goto rp_do_12; } if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_12_p; } break; }
      case 13: { if (rp_tag.wire_type == ::rapidproto::WireType::I32) { goto rp_do_13; } if (rp_tag.wire_type == ::rapidproto::WireType::Len) { goto rp_do_13_p; } break; }
      case 17: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Varint) {
          bool* const rp_slot = rp_slot_bools();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          std::uint64_t rp_raw = 0;
          const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
          if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
          rp_c = rp_np;
          *rp_slot = ::rapidproto::varint_to_bool(rp_raw);
          continue;
        }
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          ::rapidproto::ByteView rp_p;
          { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_p, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
          const std::size_t rp_ub = rp_p.size();
          if (rp_ub != 0 && rp_cap_bools < rp_n_bools + rp_ub) {
            const std::size_t rp_nc = rp_n_bools + rp_ub;
            bool* const rp_nb = arena.allocate_array<bool>(rp_nc);
            if (rp_nb == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
            for (std::size_t rp_i = 0; rp_i < rp_n_bools; ++rp_i) { rp_nb[rp_i] = rp_acc_bools[rp_i]; }
            rp_acc_bools = rp_nb;
            rp_cap_bools = rp_nc;
          }
          const std::uint8_t* rp_vp = ::rapidproto::wire::byte_ptr(rp_p);
          const std::uint8_t* const rp_ve = rp_vp + rp_p.size();
          if (rp_p.size() >= ::rapidproto::wire::kPackedKernelMinSpan) {
            const std::size_t rp_dc = ::rapidproto::arena_detail::decode_packed_varints_large<bool, ::rapidproto::wire::conv_bool>(rp_vp, rp_ve, rp_acc_bools + rp_n_bools, err);
            if (rp_dc == static_cast<std::size_t>(-1)) { return false; }
            rp_n_bools += rp_dc;
          } else {
            const std::size_t rp_dc = ::rapidproto::arena_detail::decode_packed_varints_small<bool, ::rapidproto::wire::conv_bool>(rp_vp, rp_ve, rp_acc_bools + rp_n_bools, err);
            if (rp_dc == static_cast<std::size_t>(-1)) { return false; }
            rp_n_bools += rp_dc;
          }
          arena.shrink_last(rp_acc_bools, rp_cap_bools * sizeof(bool), rp_n_bools * sizeof(bool));
          rp_cap_bools = rp_n_bools;
          continue;
        }
        break;
      }
      case 20: { if (rp_tag.wire_type == ::rapidproto::WireType::I64) { goto rp_do_20; } break; }
      case 21: { if (rp_tag.wire_type == ::rapidproto::WireType::I32) { goto rp_do_21; } break; }
      case 9: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          ::rapidproto::ByteView rp_ent;
          { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_ent, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
          CountsEntry* const rp_slot = rp_slot_counts();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          *rp_slot = CountsEntry{};
          const std::uint8_t* rp_ec = ::rapidproto::wire::byte_ptr(rp_ent);
          const std::uint8_t* const rp_ee = rp_ec + rp_ent.size();
          ::rapidproto::Tag rp_et{};
          for (;;) {
            ::rapidproto::wire::TagState rp_st = ::rapidproto::wire::TagState::End;
            const std::uint8_t* const rp_etp = ::rapidproto::wire::read_tag_or_end(rp_ec, rp_ee, &rp_et, &rp_we, &rp_st);
            if (rp_st == ::rapidproto::wire::TagState::End) { break; }
            if (rp_st == ::rapidproto::wire::TagState::Error) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
            rp_ec = rp_etp;
            if (rp_et.field_number == 1 && rp_et.wire_type == ::rapidproto::WireType::Len) {
              ::rapidproto::ByteView rp_v;
              const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_ec, rp_ee, &rp_v, &rp_we);
              if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
              rp_ec = rp_np;
              rp_slot->rp_key = ::rapidproto::ArenaString::make(rp_v, arena);
            } else if (rp_et.field_number == 2 && rp_et.wire_type == ::rapidproto::WireType::Varint) {
              std::uint64_t rp_raw = 0;
              const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_ec, rp_ee, &rp_raw, &rp_we);
              if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
              rp_ec = rp_np;
              rp_slot->rp_value = ::rapidproto::varint_to_int32(rp_raw);
            } else {
              std::size_t rp_fo = 0;
              const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_ec, rp_ee, ::rapidproto::wire::byte_ptr(rp_ent), rp_et, 0, &rp_we, &rp_fo);
              if (rp_sp == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, rp_fo); return false; }
              rp_ec = rp_sp;
            }
          }
          continue;
        }
        break;
      }
      case 14: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          ::rapidproto::ByteView rp_ent;
          { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_ent, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
          FlagsEntry* const rp_slot = rp_slot_flags();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          *rp_slot = FlagsEntry{};
          const std::uint8_t* rp_ec = ::rapidproto::wire::byte_ptr(rp_ent);
          const std::uint8_t* const rp_ee = rp_ec + rp_ent.size();
          ::rapidproto::Tag rp_et{};
          for (;;) {
            ::rapidproto::wire::TagState rp_st = ::rapidproto::wire::TagState::End;
            const std::uint8_t* const rp_etp = ::rapidproto::wire::read_tag_or_end(rp_ec, rp_ee, &rp_et, &rp_we, &rp_st);
            if (rp_st == ::rapidproto::wire::TagState::End) { break; }
            if (rp_st == ::rapidproto::wire::TagState::Error) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
            rp_ec = rp_etp;
            if (rp_et.field_number == 1 && rp_et.wire_type == ::rapidproto::WireType::Varint) {
              std::uint64_t rp_raw = 0;
              const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_ec, rp_ee, &rp_raw, &rp_we);
              if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
              rp_ec = rp_np;
              rp_slot->rp_key = ::rapidproto::varint_to_bool(rp_raw);
            } else if (rp_et.field_number == 2 && rp_et.wire_type == ::rapidproto::WireType::Len) {
              ::rapidproto::ByteView rp_v;
              const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_ec, rp_ee, &rp_v, &rp_we);
              if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
              rp_ec = rp_np;
              rp_slot->rp_value = ::rapidproto::ArenaString::make(rp_v, arena);
            } else {
              std::size_t rp_fo = 0;
              const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_ec, rp_ee, ::rapidproto::wire::byte_ptr(rp_ent), rp_et, 0, &rp_we, &rp_fo);
              if (rp_sp == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, rp_fo); return false; }
              rp_ec = rp_sp;
            }
          }
          continue;
        }
        break;
      }
      case 18: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          ::rapidproto::ByteView rp_ent;
          { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_ent, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
          TogglesEntry* const rp_slot = rp_slot_toggles();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          *rp_slot = TogglesEntry{};
          const std::uint8_t* rp_ec = ::rapidproto::wire::byte_ptr(rp_ent);
          const std::uint8_t* const rp_ee = rp_ec + rp_ent.size();
          ::rapidproto::Tag rp_et{};
          for (;;) {
            ::rapidproto::wire::TagState rp_st = ::rapidproto::wire::TagState::End;
            const std::uint8_t* const rp_etp = ::rapidproto::wire::read_tag_or_end(rp_ec, rp_ee, &rp_et, &rp_we, &rp_st);
            if (rp_st == ::rapidproto::wire::TagState::End) { break; }
            if (rp_st == ::rapidproto::wire::TagState::Error) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
            rp_ec = rp_etp;
            if (rp_et.field_number == 1 && rp_et.wire_type == ::rapidproto::WireType::Len) {
              ::rapidproto::ByteView rp_v;
              const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_ec, rp_ee, &rp_v, &rp_we);
              if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
              rp_ec = rp_np;
              rp_slot->rp_key = ::rapidproto::ArenaString::make(rp_v, arena);
            } else if (rp_et.field_number == 2 && rp_et.wire_type == ::rapidproto::WireType::Varint) {
              std::uint64_t rp_raw = 0;
              const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_ec, rp_ee, &rp_raw, &rp_we);
              if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
              rp_ec = rp_np;
              rp_slot->rp_value = ::rapidproto::varint_to_bool(rp_raw);
            } else {
              std::size_t rp_fo = 0;
              const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_ec, rp_ee, ::rapidproto::wire::byte_ptr(rp_ent), rp_et, 0, &rp_we, &rp_fo);
              if (rp_sp == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, rp_fo); return false; }
              rp_ec = rp_sp;
            }
          }
          continue;
        }
        break;
      }
      case 19: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          ::rapidproto::ByteView rp_ent;
          { const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_ent, &rp_we); if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; } rp_c = rp_np; }
          RatiosEntry* const rp_slot = rp_slot_ratios();
          if (rp_slot == nullptr) { ::rapidproto::rp_fail_oom(err); return false; }
          *rp_slot = RatiosEntry{};
          const std::uint8_t* rp_ec = ::rapidproto::wire::byte_ptr(rp_ent);
          const std::uint8_t* const rp_ee = rp_ec + rp_ent.size();
          ::rapidproto::Tag rp_et{};
          for (;;) {
            ::rapidproto::wire::TagState rp_st = ::rapidproto::wire::TagState::End;
            const std::uint8_t* const rp_etp = ::rapidproto::wire::read_tag_or_end(rp_ec, rp_ee, &rp_et, &rp_we, &rp_st);
            if (rp_st == ::rapidproto::wire::TagState::End) { break; }
            if (rp_st == ::rapidproto::wire::TagState::Error) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
            rp_ec = rp_etp;
            if (rp_et.field_number == 1 && rp_et.wire_type == ::rapidproto::WireType::Len) {
              ::rapidproto::ByteView rp_v;
              const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_ec, rp_ee, &rp_v, &rp_we);
              if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
              rp_ec = rp_np;
              rp_slot->rp_key = ::rapidproto::ArenaString::make(rp_v, arena);
            } else if (rp_et.field_number == 2 && rp_et.wire_type == ::rapidproto::WireType::I64) {
              std::uint64_t rp_raw = 0;
              const std::uint8_t* const rp_np = ::rapidproto::wire::read_fixed64(rp_ec, rp_ee, &rp_raw, &rp_we);
              if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_ec - ::rapidproto::wire::byte_ptr(rp_ent))); return false; }
              rp_ec = rp_np;
              rp_slot->rp_value = ::rapidproto::bit_cast_double(rp_raw);
            } else {
              std::size_t rp_fo = 0;
              const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_ec, rp_ee, ::rapidproto::wire::byte_ptr(rp_ent), rp_et, 0, &rp_we, &rp_fo);
              if (rp_sp == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, rp_fo); return false; }
              rp_ec = rp_sp;
            }
          }
          continue;
        }
        break;
      }
      case 10: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Varint) {
          std::uint64_t rp_raw = 0;
          const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
          if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
          rp_c = rp_np;
          out.m_rp_pick.a = ::rapidproto::varint_to_int32(rp_raw);
          out.m_rp_pick_case = 1;
          continue;
        }
        break;
      }
      case 11: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Len) {
          ::rapidproto::ByteView rp_v;
          const std::uint8_t* const rp_np = ::rapidproto::wire::read_length_delimited(rp_c, rp_cend, &rp_v, &rp_we);
          if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
          rp_c = rp_np;
          out.m_rp_pick.b = ::rapidproto::ArenaString::make(rp_v, arena);
          out.m_rp_pick_case = 2;
          continue;
        }
        break;
      }
      case 15: {
        if (rp_tag.wire_type == ::rapidproto::WireType::Varint) {
          std::uint64_t rp_raw = 0;
          const std::uint8_t* const rp_np = ::rapidproto::wire::read_varint(rp_c, rp_cend, &rp_raw, &rp_we);
          if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
          rp_c = rp_np;
          out.m_rp_pick.c = ::rapidproto::varint_to_bool(rp_raw);
          out.m_rp_pick_case = 3;
          continue;
        }
        break;
      }
      case 16: {
        if (rp_tag.wire_type == ::rapidproto::WireType::I64) {
          std::uint64_t rp_raw = 0;
          const std::uint8_t* const rp_np = ::rapidproto::wire::read_fixed64(rp_c, rp_cend, &rp_raw, &rp_we);
          if (rp_np == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, static_cast<std::size_t>(rp_c - ::rapidproto::wire::byte_ptr(body))); return false; }
          rp_c = rp_np;
          out.m_rp_pick.d = ::rapidproto::bit_cast_double(rp_raw);
          out.m_rp_pick_case = 4;
          continue;
        }
        break;
      }
      default: break;
    }
    std::size_t rp_fo = 0;
    const std::uint8_t* const rp_sp = ::rapidproto::wire::skip_value(rp_c, rp_cend, ::rapidproto::wire::byte_ptr(body), rp_tag, 0, &rp_we, &rp_fo);
    if (rp_sp == nullptr) { ::rapidproto::rp_fail_wire_at(err, rp_we, rp_fo); return false; }
    rp_c = rp_sp;
  }
  out.m_nums = ::rapidproto::ArrayView<std::int32_t>(rp_acc_nums, rp_n_nums);
  out.m_unpacked = ::rapidproto::ArrayView<std::int32_t>(rp_acc_unpacked, rp_n_unpacked);
  out.m_states = ::rapidproto::ArrayView<::rp::common::p3::State>(rp_acc_states, rp_n_states);
  out.m_reals = ::rapidproto::ArrayView<double>(rp_acc_reals, rp_n_reals);
  out.m_codes = ::rapidproto::ArrayView<std::uint32_t>(rp_acc_codes, rp_n_codes);
  out.m_bools = ::rapidproto::ArrayView<bool>(rp_acc_bools, rp_n_bools);
  out.m_counts = ::rapidproto::MapView<CountsEntry>(::rapidproto::ArrayView<CountsEntry>(rp_acc_counts, rp_n_counts));
  out.m_flags = ::rapidproto::MapView<FlagsEntry>(::rapidproto::ArrayView<FlagsEntry>(rp_acc_flags, rp_n_flags));
  out.m_toggles = ::rapidproto::MapView<TogglesEntry>(::rapidproto::ArrayView<TogglesEntry>(rp_acc_toggles, rp_n_toggles));
  out.m_ratios = ::rapidproto::MapView<RatiosEntry>(::rapidproto::ArrayView<RatiosEntry>(rp_acc_ratios, rp_n_ratios));
  return true;
}
inline const ::rp::arena::p3::Msg* ::rp::arena::p3::Msg::decode(::rapidproto::ByteView input, ::rapidproto::Arena& arena, ::rapidproto::ArenaDecodeError* err) noexcept {
  if (input.size() > UINT32_MAX) { ::rapidproto::rp_fail_input_too_large(err); return nullptr; }
  ::rp::arena::p3::Msg* const rp_root = arena.create<::rp::arena::p3::Msg>();
  if (rp_root == nullptr) { ::rapidproto::rp_fail_oom(err); return nullptr; }
  if (!rp_decode_into(*rp_root, input, arena, 0, err)) { return nullptr; }
  return rp_root;
}

}  // namespace rp::arena::p3
