// Generated by rapidprotoc 0.3.1 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "pub.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"

namespace rp::arena::pub {

namespace rp_dump_detail {

inline void rp_dump_write(const ::rp::arena::pub::Pub& m, ::rapidproto::dump_detail::Writer& w);

inline void rp_dump_write(const ::rp::arena::pub::Pub& m, ::rapidproto::dump_detail::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.w()) {
      if (w.begin_field(rp_first, "w")) {
        ::rapidproto::dump_detail::write_int(w.os(), *rp_v);
      }
    }
    (void)rp_first;
  });
}

}  // namespace rp_dump_detail

}  // namespace rp::arena::pub

namespace rapidproto::dump_detail {

template <>
struct dumper<::rp::arena::pub::Pub> {
  static void write(const ::rp::arena::pub::Pub& m, Writer& w) { ::rp::arena::pub::rp_dump_detail::rp_dump_write(m, w); }
};

}  // namespace rapidproto::dump_detail
