// Generated by rapidprotoc 0.4.0 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstdint>
#include <ostream>
#include <type_traits>

#include "samepkg_a.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"
#include "samepkg_b.rp.dump.hpp"

namespace rp::arena::samepkg {

namespace rp_dump_detail {

inline void rp_dump_write(const ::rp::arena::samepkg::FirstA& m, ::rapidproto::dump_detail::Writer& w);

inline void rp_dump_write(const ::rp::arena::samepkg::FirstA& m, ::rapidproto::dump_detail::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto* rp_p = m.b()) {
      if (w.begin_field(rp_first, "b")) {
        w.push_path("b");
        ::rp::arena::samepkg::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    (void)rp_first;
  });
}

}  // namespace rp_dump_detail

}  // namespace rp::arena::samepkg

namespace rapidproto::dump_detail {

template <>
struct dumper<::rp::arena::samepkg::FirstA> {
  static void write(const ::rp::arena::samepkg::FirstA& m, Writer& w) { ::rp::arena::samepkg::rp_dump_detail::rp_dump_write(m, w); }
};

}  // namespace rapidproto::dump_detail
