// Generated by rapidprotoc 0.3.1 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "stdpkg.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"

namespace std_ {

namespace rp_dump_detail {

inline void rp_dump_write(const ::std_::Types& m, ::rapidproto::dump::Writer& w);

inline void rp_dump_write(const ::std_::Types& m, ::rapidproto::dump::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.n(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "n")) {
        ::rapidproto::dump::write_int(w.os(), rp_v);
      }
    }
    if (const auto rp_v = m.s(); rp_v != decltype(rp_v){}) {
      if (w.begin_field(rp_first, "s")) {
        w.os() << '"'; ::rapidproto::dump::write_json_escaped(w.os(), rp_v); w.os() << '"';
      }
    }
    if (const auto& rp_r = m.many(); !rp_r.empty()) {
      if (w.begin_field(rp_first, "many")) {
        w.group('[', ']', [&] {
          bool rp_efirst = true;
          for (const auto& rp_el : rp_r) {
            w.entry_sep(rp_efirst);
            ::rapidproto::dump::write_int(w.os(), rp_el);
            if (w.overflowed()) { break; }
          }
        });
      }
    }
    (void)rp_first;
  });
}

}  // namespace rp_dump_detail

inline void rp_dump_write(std::ostream& rp_os, const ::std_::Types& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  ::rapidproto::dump::Writer w(rp_os, rp_opts.width, rp_opts.indent, &rp_opts.skip);
  ::std_::rp_dump_detail::rp_dump_write(m, w);
}

inline std::string rp_dump_string(const ::std_::Types& m, const ::rapidproto::dump::DumpOptions& rp_opts = {}) {
  std::ostringstream rp_ss; rp_dump_write(rp_ss, m, rp_opts); return rp_ss.str();
}

}  // namespace std_
