// Generated by rapidprotoc 0.3.1 (debug dumper). DO NOT EDIT.
#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>

#include "wire_all.rp.hpp"  // IWYU pragma: export
#include "rapidproto/dump_runtime.hpp"

namespace rp::arena::wire {

namespace rp_dump_detail {

inline void rp_dump_write(const ::rp::arena::wire::AllWire::G& m, ::rapidproto::dump_detail::Writer& w);
inline void rp_dump_write(const ::rp::arena::wire::AllWire& m, ::rapidproto::dump_detail::Writer& w);

inline void rp_dump_write(const ::rp::arena::wire::AllWire::G& m, ::rapidproto::dump_detail::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.a()) {
      if (w.begin_field(rp_first, "a")) {
        ::rapidproto::dump_detail::write_int(w.os(), *rp_v);
      }
    }
    (void)rp_first;
  });
}

inline void rp_dump_write(const ::rp::arena::wire::AllWire& m, ::rapidproto::dump_detail::Writer& w) {
  (void)m;
  w.group('{', '}', [&] {
    bool rp_first = true;
    if (const auto rp_v = m.zz()) {
      if (w.begin_field(rp_first, "zz")) {
        ::rapidproto::dump_detail::write_int(w.os(), *rp_v);
      }
    }
    if (const auto rp_v = m.db()) {
      if (w.begin_field(rp_first, "db")) {
        ::rapidproto::dump_detail::write_float(w.os(), *rp_v);
      }
    }
    if (const auto rp_v = m.fx()) {
      if (w.begin_field(rp_first, "fx")) {
        ::rapidproto::dump_detail::write_int(w.os(), *rp_v);
      }
    }
    if (const auto rp_v = m.s()) {
      if (w.begin_field(rp_first, "s")) {
        w.os() << '"'; ::rapidproto::dump_detail::write_json_escaped(w.os(), *rp_v); w.os() << '"';
      }
    }
    if (const auto rp_v = m.by()) {
      if (w.begin_field(rp_first, "by")) {
        w.os() << '"'; ::rapidproto::dump_detail::write_hex(w.os(), *rp_v); w.os() << '"';
      }
    }
    if (const auto* rp_p = m.nested()) {
      if (w.begin_field(rp_first, "nested")) {
        w.push_path("nested");
        ::rp::arena::wire::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    if (const auto& rp_r = m.packed(); !rp_r.empty()) {
      if (w.begin_field(rp_first, "packed")) {
        w.group('[', ']', [&] {
          bool rp_efirst = true;
          for (const auto& rp_el : rp_r) {
            w.entry_sep(rp_efirst);
            ::rapidproto::dump_detail::write_int(w.os(), rp_el);
            if (w.overflowed()) { break; }
          }
        });
      }
    }
    if (const auto* rp_p = m.g()) {
      if (w.begin_field(rp_first, "g")) {
        w.push_path("g");
        ::rp::arena::wire::rp_dump_detail::rp_dump_write(*rp_p, w);
        w.pop_path();
      }
    }
    m.pick([&](auto rp_tag, const auto& rp_v) {
      using rp_Tag = std::decay_t<decltype(rp_tag)>;
      if constexpr (std::is_same_v<rp_Tag, ::rp::arena::wire::AllWire::Pick::oi>) {
        if (w.begin_field(rp_first, "oi")) {
          ::rapidproto::dump_detail::write_int(w.os(), rp_v);
        }
      }
      if constexpr (std::is_same_v<rp_Tag, ::rp::arena::wire::AllWire::Pick::os>) {
        if (w.begin_field(rp_first, "os")) {
          w.os() << '"'; ::rapidproto::dump_detail::write_json_escaped(w.os(), rp_v); w.os() << '"';
        }
      }
    });
    (void)rp_first;
  });
}

}  // namespace rp_dump_detail

}  // namespace rp::arena::wire

namespace rapidproto::dump_detail {

template <>
struct dumper<::rp::arena::wire::AllWire::G> {
  static void write(const ::rp::arena::wire::AllWire::G& m, Writer& w) { ::rp::arena::wire::rp_dump_detail::rp_dump_write(m, w); }
};

template <>
struct dumper<::rp::arena::wire::AllWire> {
  static void write(const ::rp::arena::wire::AllWire& m, Writer& w) { ::rp::arena::wire::rp_dump_detail::rp_dump_write(m, w); }
};

}  // namespace rapidproto::dump_detail
